#
# Module manifest for module 'Microsoft.Graph.Identity.DirectoryManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 3/7/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Identity.DirectoryManagement.psm1'

# Version number of this module.
ModuleVersion = '2.16.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'c767240d-585c-42cb-bb2f-6e76e6d639d4'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.16.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Identity.DirectoryManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Identity.DirectoryManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Confirm-MgContactMemberGroup', 'Confirm-MgContactMemberObject', 
               'Confirm-MgContractMemberGroup', 'Confirm-MgContractMemberObject', 
               'Confirm-MgDeviceMemberGroup', 'Confirm-MgDeviceMemberObject', 
               'Confirm-MgDirectoryDeletedItemMemberGroup', 
               'Confirm-MgDirectoryDeletedItemMemberObject', 
               'Confirm-MgDirectoryRoleMemberGroup', 
               'Confirm-MgDirectoryRoleMemberObject', 
               'Confirm-MgDirectoryRoleTemplateMemberGroup', 
               'Confirm-MgDirectoryRoleTemplateMemberObject', 'Confirm-MgDomain', 
               'Confirm-MgOrganizationMemberGroup', 
               'Confirm-MgOrganizationMemberObject', 'Get-MgAdminPeople', 
               'Get-MgAdminPeopleProfileCardProperty', 
               'Get-MgAdminPeopleProfileCardPropertyCount', 
               'Get-MgAdminPeoplePronoun', 'Get-MgContact', 'Get-MgContactById', 
               'Get-MgContactCount', 'Get-MgContactDelta', 
               'Get-MgContactDirectReport', 
               'Get-MgContactDirectReportAsOrgContact', 
               'Get-MgContactDirectReportAsUser', 'Get-MgContactDirectReportCount', 
               'Get-MgContactDirectReportCountAsOrgContact', 
               'Get-MgContactDirectReportCountAsUser', 'Get-MgContactManager', 
               'Get-MgContactMemberGroup', 'Get-MgContactMemberObject', 
               'Get-MgContactMemberOf', 
               'Get-MgContactMemberOfAsAdministrativeUnit', 
               'Get-MgContactMemberOfAsGroup', 'Get-MgContactMemberOfCount', 
               'Get-MgContactMemberOfCountAsAdministrativeUnit', 
               'Get-MgContactMemberOfCountAsGroup', 
               'Get-MgContactServiceProvisioningError', 
               'Get-MgContactServiceProvisioningErrorCount', 
               'Get-MgContactTransitiveMemberOf', 
               'Get-MgContactTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgContactTransitiveMemberOfAsGroup', 
               'Get-MgContactTransitiveMemberOfCount', 
               'Get-MgContactTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgContactTransitiveMemberOfCountAsGroup', 'Get-MgContract', 
               'Get-MgContractById', 'Get-MgContractCount', 'Get-MgContractDelta', 
               'Get-MgContractMemberGroup', 'Get-MgContractMemberObject', 
               'Get-MgDevice', 'Get-MgDeviceByDeviceId', 'Get-MgDeviceById', 
               'Get-MgDeviceCount', 'Get-MgDeviceDelta', 'Get-MgDeviceExtension', 
               'Get-MgDeviceExtensionCount', 'Get-MgDeviceMemberGroup', 
               'Get-MgDeviceMemberObject', 'Get-MgDeviceMemberOf', 
               'Get-MgDeviceMemberOfAsAdministrativeUnit', 
               'Get-MgDeviceMemberOfAsGroup', 'Get-MgDeviceMemberOfCount', 
               'Get-MgDeviceMemberOfCountAsAdministrativeUnit', 
               'Get-MgDeviceMemberOfCountAsGroup', 'Get-MgDeviceRegisteredOwner', 
               'Get-MgDeviceRegisteredOwnerAsAppRoleAssignment', 
               'Get-MgDeviceRegisteredOwnerAsEndpoint', 
               'Get-MgDeviceRegisteredOwnerAsServicePrincipal', 
               'Get-MgDeviceRegisteredOwnerAsUser', 
               'Get-MgDeviceRegisteredOwnerByRef', 
               'Get-MgDeviceRegisteredOwnerCount', 
               'Get-MgDeviceRegisteredOwnerCountAsAppRoleAssignment', 
               'Get-MgDeviceRegisteredOwnerCountAsEndpoint', 
               'Get-MgDeviceRegisteredOwnerCountAsServicePrincipal', 
               'Get-MgDeviceRegisteredOwnerCountAsUser', 
               'Get-MgDeviceRegisteredUser', 
               'Get-MgDeviceRegisteredUserAsAppRoleAssignment', 
               'Get-MgDeviceRegisteredUserAsEndpoint', 
               'Get-MgDeviceRegisteredUserAsServicePrincipal', 
               'Get-MgDeviceRegisteredUserAsUser', 
               'Get-MgDeviceRegisteredUserByRef', 
               'Get-MgDeviceRegisteredUserCount', 
               'Get-MgDeviceRegisteredUserCountAsAppRoleAssignment', 
               'Get-MgDeviceRegisteredUserCountAsEndpoint', 
               'Get-MgDeviceRegisteredUserCountAsServicePrincipal', 
               'Get-MgDeviceRegisteredUserCountAsUser', 
               'Get-MgDeviceTransitiveMemberOf', 
               'Get-MgDeviceTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgDeviceTransitiveMemberOfAsGroup', 
               'Get-MgDeviceTransitiveMemberOfCount', 
               'Get-MgDeviceTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgDeviceTransitiveMemberOfCountAsGroup', 'Get-MgDirectory', 
               'Get-MgDirectoryAdministrativeUnit', 
               'Get-MgDirectoryAdministrativeUnitCount', 
               'Get-MgDirectoryAdministrativeUnitDelta', 
               'Get-MgDirectoryAdministrativeUnitExtension', 
               'Get-MgDirectoryAdministrativeUnitExtensionCount', 
               'Get-MgDirectoryAdministrativeUnitMember', 
               'Get-MgDirectoryAdministrativeUnitMemberAsApplication', 
               'Get-MgDirectoryAdministrativeUnitMemberAsDevice', 
               'Get-MgDirectoryAdministrativeUnitMemberAsGroup', 
               'Get-MgDirectoryAdministrativeUnitMemberAsOrgContact', 
               'Get-MgDirectoryAdministrativeUnitMemberAsServicePrincipal', 
               'Get-MgDirectoryAdministrativeUnitMemberAsUser', 
               'Get-MgDirectoryAdministrativeUnitMemberByRef', 
               'Get-MgDirectoryAdministrativeUnitMemberCount', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsApplication', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsDevice', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsGroup', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsOrgContact', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsServicePrincipal', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsUser', 
               'Get-MgDirectoryAdministrativeUnitScopedRoleMember', 
               'Get-MgDirectoryAdministrativeUnitScopedRoleMemberCount', 
               'Get-MgDirectoryAttributeSet', 'Get-MgDirectoryAttributeSetCount', 
               'Get-MgDirectoryCustomSecurityAttributeDefinition', 
               'Get-MgDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Get-MgDirectoryCustomSecurityAttributeDefinitionAllowedValueCount', 
               'Get-MgDirectoryCustomSecurityAttributeDefinitionCount', 
               'Get-MgDirectoryDeletedItem', 
               'Get-MgDirectoryDeletedItemAsAdministrativeUnit', 
               'Get-MgDirectoryDeletedItemAsApplication', 
               'Get-MgDirectoryDeletedItemAsDevice', 
               'Get-MgDirectoryDeletedItemAsGroup', 
               'Get-MgDirectoryDeletedItemAsServicePrincipal', 
               'Get-MgDirectoryDeletedItemAsUser', 
               'Get-MgDirectoryDeletedItemById', 
               'Get-MgDirectoryDeletedItemCountAsAdministrativeUnit', 
               'Get-MgDirectoryDeletedItemCountAsApplication', 
               'Get-MgDirectoryDeletedItemCountAsDevice', 
               'Get-MgDirectoryDeletedItemCountAsGroup', 
               'Get-MgDirectoryDeletedItemCountAsServicePrincipal', 
               'Get-MgDirectoryDeletedItemCountAsUser', 
               'Get-MgDirectoryDeletedItemMemberGroup', 
               'Get-MgDirectoryDeletedItemMemberObject', 
               'Get-MgDirectoryDeviceLocalCredential', 
               'Get-MgDirectoryDeviceLocalCredentialCount', 
               'Get-MgDirectoryFederationConfiguration', 
               'Get-MgDirectoryFederationConfigurationCount', 
               'Get-MgDirectoryOnPremiseSynchronization', 
               'Get-MgDirectoryOnPremiseSynchronizationCount', 
               'Get-MgDirectoryRole', 'Get-MgDirectoryRoleById', 
               'Get-MgDirectoryRoleByRoleTemplateId', 'Get-MgDirectoryRoleCount', 
               'Get-MgDirectoryRoleDelta', 'Get-MgDirectoryRoleMember', 
               'Get-MgDirectoryRoleMemberAsApplication', 
               'Get-MgDirectoryRoleMemberAsDevice', 
               'Get-MgDirectoryRoleMemberAsGroup', 
               'Get-MgDirectoryRoleMemberAsOrgContact', 
               'Get-MgDirectoryRoleMemberAsServicePrincipal', 
               'Get-MgDirectoryRoleMemberAsUser', 'Get-MgDirectoryRoleMemberByRef', 
               'Get-MgDirectoryRoleMemberCount', 
               'Get-MgDirectoryRoleMemberCountAsApplication', 
               'Get-MgDirectoryRoleMemberCountAsDevice', 
               'Get-MgDirectoryRoleMemberCountAsGroup', 
               'Get-MgDirectoryRoleMemberCountAsOrgContact', 
               'Get-MgDirectoryRoleMemberCountAsServicePrincipal', 
               'Get-MgDirectoryRoleMemberCountAsUser', 
               'Get-MgDirectoryRoleMemberGroup', 'Get-MgDirectoryRoleMemberObject', 
               'Get-MgDirectoryRoleScopedMember', 
               'Get-MgDirectoryRoleScopedMemberCount', 
               'Get-MgDirectoryRoleTemplate', 'Get-MgDirectoryRoleTemplateById', 
               'Get-MgDirectoryRoleTemplateCount', 
               'Get-MgDirectoryRoleTemplateDelta', 
               'Get-MgDirectoryRoleTemplateMemberGroup', 
               'Get-MgDirectoryRoleTemplateMemberObject', 'Get-MgDomain', 
               'Get-MgDomainCount', 'Get-MgDomainFederationConfiguration', 
               'Get-MgDomainFederationConfigurationCount', 
               'Get-MgDomainNameReference', 'Get-MgDomainNameReferenceCount', 
               'Get-MgDomainServiceConfigurationRecord', 
               'Get-MgDomainServiceConfigurationRecordCount', 
               'Get-MgDomainVerificationDnsRecord', 
               'Get-MgDomainVerificationDnsRecordCount', 'Get-MgOrganization', 
               'Get-MgOrganizationBranding', 
               'Get-MgOrganizationBrandingBackgroundImage', 
               'Get-MgOrganizationBrandingBannerLogo', 
               'Get-MgOrganizationBrandingCustomCss', 
               'Get-MgOrganizationBrandingFavicon', 
               'Get-MgOrganizationBrandingHeaderLogo', 
               'Get-MgOrganizationBrandingLocalization', 
               'Get-MgOrganizationBrandingLocalizationBackgroundImage', 
               'Get-MgOrganizationBrandingLocalizationBannerLogo', 
               'Get-MgOrganizationBrandingLocalizationCount', 
               'Get-MgOrganizationBrandingLocalizationCustomCss', 
               'Get-MgOrganizationBrandingLocalizationFavicon', 
               'Get-MgOrganizationBrandingLocalizationHeaderLogo', 
               'Get-MgOrganizationBrandingLocalizationSquareLogo', 
               'Get-MgOrganizationBrandingLocalizationSquareLogoDark', 
               'Get-MgOrganizationBrandingSquareLogo', 
               'Get-MgOrganizationBrandingSquareLogoDark', 
               'Get-MgOrganizationById', 'Get-MgOrganizationCount', 
               'Get-MgOrganizationExtension', 'Get-MgOrganizationExtensionCount', 
               'Get-MgOrganizationMemberGroup', 'Get-MgOrganizationMemberObject', 
               'Get-MgSubscribedSku', 'Get-MgUserScopedRoleMemberOf', 
               'Get-MgUserScopedRoleMemberOfCount', 
               'Invoke-MgAvailableDirectoryFederationConfigurationProviderType', 
               'Invoke-MgForceDomainDelete', 'Invoke-MgPromoteDomain', 
               'Invoke-MgRetryContactServiceProvisioning', 
               'New-MgAdminPeopleProfileCardProperty', 'New-MgContact', 
               'New-MgContract', 'New-MgDevice', 'New-MgDeviceExtension', 
               'New-MgDeviceRegisteredOwnerByRef', 
               'New-MgDeviceRegisteredUserByRef', 
               'New-MgDirectoryAdministrativeUnit', 
               'New-MgDirectoryAdministrativeUnitExtension', 
               'New-MgDirectoryAdministrativeUnitMember', 
               'New-MgDirectoryAdministrativeUnitMemberByRef', 
               'New-MgDirectoryAdministrativeUnitScopedRoleMember', 
               'New-MgDirectoryAttributeSet', 
               'New-MgDirectoryCustomSecurityAttributeDefinition', 
               'New-MgDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'New-MgDirectoryDeviceLocalCredential', 
               'New-MgDirectoryFederationConfiguration', 
               'New-MgDirectoryOnPremiseSynchronization', 'New-MgDirectoryRole', 
               'New-MgDirectoryRoleMemberByRef', 'New-MgDirectoryRoleScopedMember', 
               'New-MgDirectoryRoleTemplate', 'New-MgDomain', 
               'New-MgDomainFederationConfiguration', 
               'New-MgDomainServiceConfigurationRecord', 
               'New-MgDomainVerificationDnsRecord', 'New-MgOrganization', 
               'New-MgOrganizationBrandingLocalization', 
               'New-MgOrganizationExtension', 'New-MgSubscribedSku', 
               'New-MgUserScopedRoleMemberOf', 
               'Remove-MgAdminPeopleProfileCardProperty', 'Remove-MgContact', 
               'Remove-MgContract', 'Remove-MgDevice', 'Remove-MgDeviceByDeviceId', 
               'Remove-MgDeviceExtension', 'Remove-MgDeviceRegisteredOwnerByRef', 
               'Remove-MgDeviceRegisteredUserByRef', 
               'Remove-MgDirectoryAdministrativeUnit', 
               'Remove-MgDirectoryAdministrativeUnitExtension', 
               'Remove-MgDirectoryAdministrativeUnitMemberByRef', 
               'Remove-MgDirectoryAdministrativeUnitScopedRoleMember', 
               'Remove-MgDirectoryAttributeSet', 
               'Remove-MgDirectoryCustomSecurityAttributeDefinition', 
               'Remove-MgDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Remove-MgDirectoryDeletedItem', 
               'Remove-MgDirectoryDeviceLocalCredential', 
               'Remove-MgDirectoryFederationConfiguration', 
               'Remove-MgDirectoryOnPremiseSynchronization', 
               'Remove-MgDirectoryRole', 'Remove-MgDirectoryRoleByRoleTemplateId', 
               'Remove-MgDirectoryRoleMemberByRef', 
               'Remove-MgDirectoryRoleScopedMember', 
               'Remove-MgDirectoryRoleTemplate', 'Remove-MgDomain', 
               'Remove-MgDomainFederationConfiguration', 
               'Remove-MgDomainServiceConfigurationRecord', 
               'Remove-MgDomainVerificationDnsRecord', 'Remove-MgOrganization', 
               'Remove-MgOrganizationBranding', 
               'Remove-MgOrganizationBrandingLocalization', 
               'Remove-MgOrganizationExtension', 'Remove-MgSubscribedSku', 
               'Remove-MgUserScopedRoleMemberOf', 'Restore-MgDirectoryDeletedItem', 
               'Set-MgOrganizationBrandingBackgroundImage', 
               'Set-MgOrganizationBrandingBannerLogo', 
               'Set-MgOrganizationBrandingCustomCss', 
               'Set-MgOrganizationBrandingFavicon', 
               'Set-MgOrganizationBrandingHeaderLogo', 
               'Set-MgOrganizationBrandingLocalizationBackgroundImage', 
               'Set-MgOrganizationBrandingLocalizationBannerLogo', 
               'Set-MgOrganizationBrandingLocalizationCustomCss', 
               'Set-MgOrganizationBrandingLocalizationFavicon', 
               'Set-MgOrganizationBrandingLocalizationHeaderLogo', 
               'Set-MgOrganizationBrandingLocalizationSquareLogo', 
               'Set-MgOrganizationBrandingLocalizationSquareLogoDark', 
               'Set-MgOrganizationBrandingSquareLogo', 
               'Set-MgOrganizationBrandingSquareLogoDark', 
               'Set-MgOrganizationMobileDeviceManagementAuthority', 
               'Test-MgContactProperty', 'Test-MgContractProperty', 
               'Test-MgDeviceProperty', 'Test-MgDirectoryDeletedItemProperty', 
               'Test-MgDirectoryRoleProperty', 
               'Test-MgDirectoryRoleTemplateProperty', 
               'Test-MgOrganizationProperty', 
               'Update-MgAdminPeopleProfileCardProperty', 
               'Update-MgAdminPeoplePronoun', 'Update-MgContact', 
               'Update-MgContract', 'Update-MgDevice', 'Update-MgDeviceByDeviceId', 
               'Update-MgDeviceExtension', 'Update-MgDirectory', 
               'Update-MgDirectoryAdministrativeUnit', 
               'Update-MgDirectoryAdministrativeUnitExtension', 
               'Update-MgDirectoryAdministrativeUnitScopedRoleMember', 
               'Update-MgDirectoryAttributeSet', 
               'Update-MgDirectoryCustomSecurityAttributeDefinition', 
               'Update-MgDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Update-MgDirectoryDeviceLocalCredential', 
               'Update-MgDirectoryFederationConfiguration', 
               'Update-MgDirectoryOnPremiseSynchronization', 
               'Update-MgDirectoryRole', 'Update-MgDirectoryRoleByRoleTemplateId', 
               'Update-MgDirectoryRoleScopedMember', 
               'Update-MgDirectoryRoleTemplate', 'Update-MgDomain', 
               'Update-MgDomainFederationConfiguration', 
               'Update-MgDomainServiceConfigurationRecord', 
               'Update-MgDomainVerificationDnsRecord', 'Update-MgOrganization', 
               'Update-MgOrganizationBranding', 
               'Update-MgOrganizationBrandingLocalization', 
               'Update-MgOrganizationExtension', 'Update-MgSubscribedSku', 
               'Update-MgUserScopedRoleMemberOf'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-MgDirectoryDeletedAdministrativeUnit', 
               'Get-MgDirectoryDeletedApplication', 'Get-MgDirectoryDeletedDevice', 
               'Get-MgDirectoryDeletedGroup', 
               'Get-MgDirectoryDeletedServicePrincipal', 
               'Get-MgDirectoryDeletedUser'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInvwYJKoZIhvcNAQcCoIInsDCCJ6wCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAduKLc1ErJDRpn
# l4UY8UwSE68KG0YIgAUUYxkgYU5KbKCCDXYwggX0MIID3KADAgECAhMzAAADrzBA
# DkyjTQVBAAAAAAOvMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMxMTE2MTkwOTAwWhcNMjQxMTE0MTkwOTAwWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDOS8s1ra6f0YGtg0OhEaQa/t3Q+q1MEHhWJhqQVuO5amYXQpy8MDPNoJYk+FWA
# hePP5LxwcSge5aen+f5Q6WNPd6EDxGzotvVpNi5ve0H97S3F7C/axDfKxyNh21MG
# 0W8Sb0vxi/vorcLHOL9i+t2D6yvvDzLlEefUCbQV/zGCBjXGlYJcUj6RAzXyeNAN
# xSpKXAGd7Fh+ocGHPPphcD9LQTOJgG7Y7aYztHqBLJiQQ4eAgZNU4ac6+8LnEGAL
# go1ydC5BJEuJQjYKbNTy959HrKSu7LO3Ws0w8jw6pYdC1IMpdTkk2puTgY2PDNzB
# tLM4evG7FYer3WX+8t1UMYNTAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQURxxxNPIEPGSO8kqz+bgCAQWGXsEw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMTgyNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAISxFt/zR2frTFPB45Yd
# mhZpB2nNJoOoi+qlgcTlnO4QwlYN1w/vYwbDy/oFJolD5r6FMJd0RGcgEM8q9TgQ
# 2OC7gQEmhweVJ7yuKJlQBH7P7Pg5RiqgV3cSonJ+OM4kFHbP3gPLiyzssSQdRuPY
# 1mIWoGg9i7Y4ZC8ST7WhpSyc0pns2XsUe1XsIjaUcGu7zd7gg97eCUiLRdVklPmp
# XobH9CEAWakRUGNICYN2AgjhRTC4j3KJfqMkU04R6Toyh4/Toswm1uoDcGr5laYn
# TfcX3u5WnJqJLhuPe8Uj9kGAOcyo0O1mNwDa+LhFEzB6CB32+wfJMumfr6degvLT
# e8x55urQLeTjimBQgS49BSUkhFN7ois3cZyNpnrMca5AZaC7pLI72vuqSsSlLalG
# OcZmPHZGYJqZ0BacN274OZ80Q8B11iNokns9Od348bMb5Z4fihxaBWebl8kWEi2O
# PvQImOAeq3nt7UWJBzJYLAGEpfasaA3ZQgIcEXdD+uwo6ymMzDY6UamFOfYqYWXk
# ntxDGu7ngD2ugKUuccYKJJRiiz+LAUcj90BVcSHRLQop9N8zoALr/1sJuwPrVAtx
# HNEgSW+AKBqIxYWM4Ev32l6agSUAezLMbq5f3d8x9qzT031jMDT+sUAoCw0M5wVt
# CUQcqINPuYjbS1WgJyZIiEkBMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGZ8wghmbAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAOvMEAOTKNNBUEAAAAAA68wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIHlpTXaajUDLP0OiSarEGtUP
# 9C37l0QEL8DSRcd4RCOFMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAw2MEvrMWZPGiKaPATcJgY8DDH0XrG1g3YFqxobZXVytbjCuQLajYZU55
# oz82HF+lAWa+3bWsKlmeKGdrdM6AwXdD66BsdDTxorCGTHassgTpKlSY1IgpjjjM
# bEuWlBFsOQqDQUUEiU89ZBuUW/FXAiQVP33ZI/gyCZaxaz8SSztFdA+xK2kHlcgg
# 5fOQN99i7jbwEMfh1sN+kqbspqrGKcdLkUDOb7PnoUryUQEyuHu4FjGff8NmIXor
# oXexCB5BZzLBsph/KpcbAwYHMb0X21QqYYMJWS/psg6GdYDqr2xHLNgkWhe4kBHb
# Ngnqs5qyN6gzTnC9toquLpYwQv4Rg6GCFykwghclBgorBgEEAYI3AwMBMYIXFTCC
# FxEGCSqGSIb3DQEHAqCCFwIwghb+AgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsq
# hkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCB4YZJEEdgQLQwzd+DlIf4qFinclQMesAYG9WbZ+X9qvgIGZdX+JY+x
# GBMyMDI0MDMwNzE4NTA1My43NzFaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNO
# OjNCRDQtNEI4MC02OUMzMSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBT
# ZXJ2aWNloIIReDCCBycwggUPoAMCAQICEzMAAAHlj2rA8z20C6MAAQAAAeUwDQYJ
# KoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjMx
# MDEyMTkwNzM1WhcNMjUwMTEwMTkwNzM1WjCB0jELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3Bl
# cmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjozQkQ0LTRC
# ODAtNjlDMzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKl74Drau2O6LLrJO3HyTvO9
# aXai//eNyP5MLWZrmUGNOJMPwMI08V9zBfRPNcucreIYSyJHjkMIUGmuh0rPV5/2
# +UCLGrN1P77n9fq/mdzXMN1FzqaPHdKElKneJQ8R6cP4dru2Gymmt1rrGcNe800C
# cD6d/Ndoommkd196VqOtjZFA1XWu+GsFBeWHiez/PllqcM/eWntkQMs0lK0zmCfH
# +Bu7i1h+FDRR8F7WzUr/7M3jhVdPpAfq2zYCA8ZVLNgEizY+vFmgx+zDuuU/GChD
# K7klDcCw+/gVoEuSOl5clQsydWQjJJX7Z2yV+1KC6G1JVqpP3dpKPAP/4udNqpR5
# HIeb8Ta1JfjRUzSv3qSje5y9RYT/AjWNYQ7gsezuDWM/8cZ11kco1JvUyOQ8x/JD
# kMFqSRwj1v+mc6LKKlj//dWCG/Hw9ppdlWJX6psDesQuQR7FV7eCqV/lfajoLpPN
# x/9zF1dv8yXBdzmWJPeCie2XaQnrAKDqlG3zXux9tNQmz2L96TdxnIO2OGmYxBAA
# ZAWoKbmtYI+Ciz4CYyO0Fm5Z3T40a5d7KJuftF6CToccc/Up/jpFfQitLfjd71cS
# +cLCeoQ+q0n0IALvV+acbENouSOrjv/QtY4FIjHlI5zdJzJnGskVJ5ozhji0YRsc
# v1WwJFAuyyCMQvLdmPddAgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQU3/+fh7tNczEi
# fEXlCQgFOXgMh6owHwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYD
# VR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
# CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIw
# MjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBADP6whOFjD1ad8Gk
# EJ9oLBuvfjndMyGQ9R4HgBKSlPt3pa0XVLcimrJlDnKGgFBiWwI6XOgw82hdolDi
# MDBLLWRMTJHWVeUY1gU4XB8OOIxBc9/Q83zb1c0RWEupgC48I+b+2x2VNgGJUsQI
# yPR2PiXQhT5PyerMgag9OSodQjFwpNdGirna2rpV23EUwFeO5+3oSX4JeCNZvgyU
# OzKpyMvqVaubo+Glf/psfW5tIcMjZVt0elswfq0qJNQgoYipbaTvv7xmixUJGTbi
# xYifTwAivPcKNdeisZmtts7OHbAM795ZvKLSEqXiRUjDYZyeHyAysMEALbIhdXgH
# Eh60KoZyzlBXz3VxEirE7nhucNwM2tViOlwI7EkeU5hudctnXCG55JuMw/wb7c71
# RKimZA/KXlWpmBvkJkB0BZES8OCGDd+zY/T9BnTp8si36Tql84VfpYe9iHmy7Pqq
# xqMF2Cn4q2a0mEMnpBruDGE/gR9c8SVJ2ntkARy5SfluuJ/MB61yRvT1mUx3lypp
# O22ePjBjnwoEvVxbDjT1jhdMNdevOuDeJGzRLK9HNmTDC+TdZQlj+VMgIm8ZeEIR
# NF0oaviF+QZcUZLWzWbYq6yDok8EZKFiRR5otBoGLvaYFpxBZUE8mnLKuDlYobjr
# xh7lnwrxV/fMy0F9fSo2JxFmtLgtMIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJ
# mQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
# dGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgzMjI1
# WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjK
# NVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhg
# fWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJp
# rx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/d
# vI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6BVWYbWg7mka9
# 7aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdbZ2De+JKR
# Hh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn427DZM9itu
# qBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEzOUyO
# ArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2ZItb
# oKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
# bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
# AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQW
# BBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacb
# UzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYz
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnku
# aHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
# QwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFNX2
# VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwu
# bWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
# MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
# XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6
# U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVt
# I1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis
# 9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTp
# kbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0
# sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lUZNlz138e
# W0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQTHa1V1QJ
# sWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLBgqJ7
# Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0llOZ0
# dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
# tB1VM1izoXBm8qGCAtQwggI9AgEBMIIBAKGB2KSB1TCB0jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjoz
# QkQ0LTRCODAtNjlDMzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
# dmljZaIjCgEBMAcGBSsOAwIaAxUA942iGuYFrsE4wzWDd85EpM6RiwqggYMwgYCk
# fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQUFAAIF
# AOmUQH8wIhgPMjAyNDAzMDcyMTMyNDdaGA8yMDI0MDMwODIxMzI0N1owdDA6Bgor
# BgEEAYRZCgQBMSwwKjAKAgUA6ZRAfwIBADAHAgEAAgIMMTAHAgEAAgIR/zAKAgUA
# 6ZWR/wIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAID
# B6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUAA4GBAJt4Hm6F5qAoKr5nAmTR
# eBWuHwyRVuLuUKAdWffKLrzMU1TJL8jbAr64WsIcYj31J/9hKpfaTx3iMPaZHH5/
# k4e7p0xHYibhgAFJWXH8zKbpqMT35CvHIFu1ANJFlfZYyv06T5+leffz5sQUHCJx
# pNFpNVetoUJ9yBYn5ISuyTX0MYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgUENBIDIwMTACEzMAAAHlj2rA8z20C6MAAQAAAeUwDQYJYIZIAWUDBAIB
# BQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQx
# IgQgc4ROAfPWbaLpwdCRmHQvrc467MHBYgWkS3TCQ6ZwPb8wgfoGCyqGSIb3DQEJ
# EAIvMYHqMIHnMIHkMIG9BCAVqdP//qjxGFhe2YboEXeb8I/pAof01CwhbxUH9U69
# 7TCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB5Y9q
# wPM9tAujAAEAAAHlMCIEIChU0S/z79iCH5mGtyYJ7+2wUNgU4rueFLKo94yj+t+V
# MA0GCSqGSIb3DQEBCwUABIICAB2oCuPzTQXHWsiy19wzPWT29U5wbOa8zhUWW0lG
# AbTR0oSPYqdjV/pqrAq4JL63T2b2duwshgxcrD9x57mhVfFXp5bixCDm5dB93UG+
# v+xgMGjAxAai93aQfdJj/FrdZrapQL3sNqj/BgyqWbL0OKe+lJnfoHgbFt+LONNd
# OV/dNnDuMhyqAlcFjprUgZXhpql09GaL+nz0nZpZoRXXRSVMPadkKSjSox2SmQDG
# z6Pp+TFG0gRl7djhOWmgG9XMp3TDh/Fva0ndhqFM36chggK70rMeb3E8982U626T
# GrxpF1kOe70e2ScB/JePBqqK9a+eXR/QTC/DlKnhnRUk8dP/JMRR96geDfV32J8i
# KDDpOrZwVKNIcYeQdYkWuihs3dUNOS2fe2ly14TfmMKOZHIEYTZIg3e6L2Zwr0MR
# NSw6jolLYbqLqsEdsDIbfMc40VTRkhr03l+2bECNE/5gfkFroT2SgbbyzJHC3uSV
# IxaNh8Mzc25GUS6Va/POTSQXdfs0P0BcNEf9bO1A9SfgbrGTaBhXjaXKHvkYMNQ3
# om1IvKx2aoqn58hoFJSuXVSW5I3JqaZra72XZNRgW8fpUmIPMsGYhLepsr8PcEJJ
# A41tqcwcpaOL7NM2aSJQpxecIXUZOBx6eLV/TI9zMINkmQV6uo3bdKuhFYPUIkew
# 6deS
# SIG # End signature block
