#
# Module manifest for module 'Microsoft.Graph.Beta.ManagedTenants'
#
# Generated by: Microsoft Corporation
#
# Generated on: 3/26/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.ManagedTenants.psm1'

# Version number of this module.
ModuleVersion = '2.17.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'e5ddb308-d7d6-4bb1-82ed-cc467c794955'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.17.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Beta.ManagedTenants.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Beta.ManagedTenants.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-MgBetaTenantRelationshipManagedTenant', 
               'Get-MgBetaTenantRelationshipManagedTenantAggregatedPolicyCompliance', 
               'Get-MgBetaTenantRelationshipManagedTenantAggregatedPolicyComplianceCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAlert', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertApiNotification', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertApiNotificationCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertEmailNotification', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertEmailNotificationCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertLog', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertLogAlert', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertLogCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertRule', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertRuleAlert', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertRuleAlertCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertRuleCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertRuleDefinition', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertRuleDefinitionAlertRule', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertRuleDefinitionAlertRuleCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAlertRuleDefinitionCount', 
               'Get-MgBetaTenantRelationshipManagedTenantApiNotification', 
               'Get-MgBetaTenantRelationshipManagedTenantApiNotificationAlert', 
               'Get-MgBetaTenantRelationshipManagedTenantApiNotificationCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAppPerformance', 
               'Get-MgBetaTenantRelationshipManagedTenantAppPerformanceCount', 
               'Get-MgBetaTenantRelationshipManagedTenantAuditEvent', 
               'Get-MgBetaTenantRelationshipManagedTenantAuditEventCount', 
               'Get-MgBetaTenantRelationshipManagedTenantCloudPcConnection', 
               'Get-MgBetaTenantRelationshipManagedTenantCloudPcConnectionCount', 
               'Get-MgBetaTenantRelationshipManagedTenantCloudPcDevice', 
               'Get-MgBetaTenantRelationshipManagedTenantCloudPcDeviceCount', 
               'Get-MgBetaTenantRelationshipManagedTenantCloudPcOverview', 
               'Get-MgBetaTenantRelationshipManagedTenantCloudPcOverviewCount', 
               'Get-MgBetaTenantRelationshipManagedTenantConditionalAccessPolicyCoverage', 
               'Get-MgBetaTenantRelationshipManagedTenantConditionalAccessPolicyCoverageCount', 
               'Get-MgBetaTenantRelationshipManagedTenantCount', 
               'Get-MgBetaTenantRelationshipManagedTenantCredentialUserRegistrationSummary', 
               'Get-MgBetaTenantRelationshipManagedTenantCredentialUserRegistrationSummaryCount', 
               'Get-MgBetaTenantRelationshipManagedTenantCustomizedInformation', 
               'Get-MgBetaTenantRelationshipManagedTenantCustomizedInformationCount', 
               'Get-MgBetaTenantRelationshipManagedTenantDetailedInformation', 
               'Get-MgBetaTenantRelationshipManagedTenantDetailedInformationCount', 
               'Get-MgBetaTenantRelationshipManagedTenantDeviceAppPerformance', 
               'Get-MgBetaTenantRelationshipManagedTenantDeviceAppPerformanceCount', 
               'Get-MgBetaTenantRelationshipManagedTenantDeviceCompliancePolicySettingStateSummary', 
               'Get-MgBetaTenantRelationshipManagedTenantDeviceCompliancePolicySettingStateSummaryCount', 
               'Get-MgBetaTenantRelationshipManagedTenantDeviceHealthStatus', 
               'Get-MgBetaTenantRelationshipManagedTenantDeviceHealthStatusCount', 
               'Get-MgBetaTenantRelationshipManagedTenantEmailNotification', 
               'Get-MgBetaTenantRelationshipManagedTenantEmailNotificationAlert', 
               'Get-MgBetaTenantRelationshipManagedTenantEmailNotificationCount', 
               'Get-MgBetaTenantRelationshipManagedTenantGroup', 
               'Get-MgBetaTenantRelationshipManagedTenantGroupCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagedDeviceCompliance', 
               'Get-MgBetaTenantRelationshipManagedTenantManagedDeviceComplianceCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagedDeviceComplianceTrend', 
               'Get-MgBetaTenantRelationshipManagedTenantManagedDeviceComplianceTrendCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementAction', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementActionCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementActionTenantDeploymentStatus', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementActionTenantDeploymentStatusCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementIntent', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementIntentCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplate', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateCollection', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateCollectionCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateCollectionManagementTemplate', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateCollectionManagementTemplateCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateCollectionTenantSummary', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateCollectionTenantSummaryCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStep', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepAcceptedVersion', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepManagementTemplate', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepTenantSummary', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepTenantSummaryCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersion', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionAcceptedFor', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionDeployment', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionDeploymentCount', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionDeploymentTemplateStepVersion', 
               'Get-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionTemplateStep', 
               'Get-MgBetaTenantRelationshipManagedTenantMyRole', 
               'Get-MgBetaTenantRelationshipManagedTenantMyRoleCount', 
               'Get-MgBetaTenantRelationshipManagedTenantTag', 
               'Get-MgBetaTenantRelationshipManagedTenantTagCount', 
               'Get-MgBetaTenantRelationshipManagedTenantTicketingEndpoint', 
               'Get-MgBetaTenantRelationshipManagedTenantTicketingEndpointCount', 
               'Get-MgBetaTenantRelationshipManagedTenantWindowsDeviceMalwareState', 
               'Get-MgBetaTenantRelationshipManagedTenantWindowsDeviceMalwareStateCount', 
               'Get-MgBetaTenantRelationshipManagedTenantWindowsProtectionState', 
               'Get-MgBetaTenantRelationshipManagedTenantWindowsProtectionStateCount', 
               'New-MgBetaTenantRelationshipManagedTenant', 
               'New-MgBetaTenantRelationshipManagedTenantAggregatedPolicyCompliance', 
               'New-MgBetaTenantRelationshipManagedTenantAlert', 
               'New-MgBetaTenantRelationshipManagedTenantAlertLog', 
               'New-MgBetaTenantRelationshipManagedTenantAlertRule', 
               'New-MgBetaTenantRelationshipManagedTenantAlertRuleDefinition', 
               'New-MgBetaTenantRelationshipManagedTenantApiNotification', 
               'New-MgBetaTenantRelationshipManagedTenantAppPerformance', 
               'New-MgBetaTenantRelationshipManagedTenantAuditEvent', 
               'New-MgBetaTenantRelationshipManagedTenantCloudPcConnection', 
               'New-MgBetaTenantRelationshipManagedTenantCloudPcDevice', 
               'New-MgBetaTenantRelationshipManagedTenantCloudPcOverview', 
               'New-MgBetaTenantRelationshipManagedTenantConditionalAccessPolicyCoverage', 
               'New-MgBetaTenantRelationshipManagedTenantCredentialUserRegistrationSummary', 
               'New-MgBetaTenantRelationshipManagedTenantCustomizedInformation', 
               'New-MgBetaTenantRelationshipManagedTenantDetailedInformation', 
               'New-MgBetaTenantRelationshipManagedTenantDeviceAppPerformance', 
               'New-MgBetaTenantRelationshipManagedTenantDeviceCompliancePolicySettingStateSummary', 
               'New-MgBetaTenantRelationshipManagedTenantDeviceHealthStatus', 
               'New-MgBetaTenantRelationshipManagedTenantEmailNotification', 
               'New-MgBetaTenantRelationshipManagedTenantGroup', 
               'New-MgBetaTenantRelationshipManagedTenantManagedDeviceCompliance', 
               'New-MgBetaTenantRelationshipManagedTenantManagedDeviceComplianceTrend', 
               'New-MgBetaTenantRelationshipManagedTenantManagementAction', 
               'New-MgBetaTenantRelationshipManagedTenantManagementActionTenantDeploymentStatus', 
               'New-MgBetaTenantRelationshipManagedTenantManagementIntent', 
               'New-MgBetaTenantRelationshipManagedTenantManagementTemplate', 
               'New-MgBetaTenantRelationshipManagedTenantManagementTemplateCollection', 
               'New-MgBetaTenantRelationshipManagedTenantManagementTemplateCollectionTenantSummary', 
               'New-MgBetaTenantRelationshipManagedTenantManagementTemplateStep', 
               'New-MgBetaTenantRelationshipManagedTenantManagementTemplateStepTenantSummary', 
               'New-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersion', 
               'New-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionDeployment', 
               'New-MgBetaTenantRelationshipManagedTenantMyRole', 
               'New-MgBetaTenantRelationshipManagedTenantTag', 
               'New-MgBetaTenantRelationshipManagedTenantTicketingEndpoint', 
               'New-MgBetaTenantRelationshipManagedTenantWindowsDeviceMalwareState', 
               'New-MgBetaTenantRelationshipManagedTenantWindowsProtectionState', 
               'Remove-MgBetaTenantRelationshipManagedTenant', 
               'Remove-MgBetaTenantRelationshipManagedTenantAggregatedPolicyCompliance', 
               'Remove-MgBetaTenantRelationshipManagedTenantAlert', 
               'Remove-MgBetaTenantRelationshipManagedTenantAlertLog', 
               'Remove-MgBetaTenantRelationshipManagedTenantAlertRule', 
               'Remove-MgBetaTenantRelationshipManagedTenantAlertRuleDefinition', 
               'Remove-MgBetaTenantRelationshipManagedTenantApiNotification', 
               'Remove-MgBetaTenantRelationshipManagedTenantAppPerformance', 
               'Remove-MgBetaTenantRelationshipManagedTenantAuditEvent', 
               'Remove-MgBetaTenantRelationshipManagedTenantCloudPcConnection', 
               'Remove-MgBetaTenantRelationshipManagedTenantCloudPcDevice', 
               'Remove-MgBetaTenantRelationshipManagedTenantCloudPcOverview', 
               'Remove-MgBetaTenantRelationshipManagedTenantConditionalAccessPolicyCoverage', 
               'Remove-MgBetaTenantRelationshipManagedTenantCredentialUserRegistrationSummary', 
               'Remove-MgBetaTenantRelationshipManagedTenantCustomizedInformation', 
               'Remove-MgBetaTenantRelationshipManagedTenantDetailedInformation', 
               'Remove-MgBetaTenantRelationshipManagedTenantDeviceAppPerformance', 
               'Remove-MgBetaTenantRelationshipManagedTenantDeviceCompliancePolicySettingStateSummary', 
               'Remove-MgBetaTenantRelationshipManagedTenantDeviceHealthStatus', 
               'Remove-MgBetaTenantRelationshipManagedTenantEmailNotification', 
               'Remove-MgBetaTenantRelationshipManagedTenantGroup', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagedDeviceCompliance', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagedDeviceComplianceTrend', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementAction', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementActionTenantDeploymentStatus', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementIntent', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementTemplate', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementTemplateCollection', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementTemplateCollectionTenantSummary', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementTemplateStep', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementTemplateStepTenantSummary', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersion', 
               'Remove-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionDeployment', 
               'Remove-MgBetaTenantRelationshipManagedTenantMyRole', 
               'Remove-MgBetaTenantRelationshipManagedTenantTag', 
               'Remove-MgBetaTenantRelationshipManagedTenantTicketingEndpoint', 
               'Remove-MgBetaTenantRelationshipManagedTenantWindowsDeviceMalwareState', 
               'Remove-MgBetaTenantRelationshipManagedTenantWindowsProtectionState', 
               'Update-MgBetaTenantRelationshipManagedTenant', 
               'Update-MgBetaTenantRelationshipManagedTenantAggregatedPolicyCompliance', 
               'Update-MgBetaTenantRelationshipManagedTenantAlert', 
               'Update-MgBetaTenantRelationshipManagedTenantAlertLog', 
               'Update-MgBetaTenantRelationshipManagedTenantAlertRule', 
               'Update-MgBetaTenantRelationshipManagedTenantAlertRuleDefinition', 
               'Update-MgBetaTenantRelationshipManagedTenantApiNotification', 
               'Update-MgBetaTenantRelationshipManagedTenantAppPerformance', 
               'Update-MgBetaTenantRelationshipManagedTenantAuditEvent', 
               'Update-MgBetaTenantRelationshipManagedTenantCloudPcConnection', 
               'Update-MgBetaTenantRelationshipManagedTenantCloudPcDevice', 
               'Update-MgBetaTenantRelationshipManagedTenantCloudPcOverview', 
               'Update-MgBetaTenantRelationshipManagedTenantConditionalAccessPolicyCoverage', 
               'Update-MgBetaTenantRelationshipManagedTenantCredentialUserRegistrationSummary', 
               'Update-MgBetaTenantRelationshipManagedTenantCustomizedInformation', 
               'Update-MgBetaTenantRelationshipManagedTenantDetailedInformation', 
               'Update-MgBetaTenantRelationshipManagedTenantDeviceAppPerformance', 
               'Update-MgBetaTenantRelationshipManagedTenantDeviceCompliancePolicySettingStateSummary', 
               'Update-MgBetaTenantRelationshipManagedTenantDeviceHealthStatus', 
               'Update-MgBetaTenantRelationshipManagedTenantEmailNotification', 
               'Update-MgBetaTenantRelationshipManagedTenantGroup', 
               'Update-MgBetaTenantRelationshipManagedTenantManagedDeviceCompliance', 
               'Update-MgBetaTenantRelationshipManagedTenantManagedDeviceComplianceTrend', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementAction', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementActionTenantDeploymentStatus', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementIntent', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementTemplate', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementTemplateCollection', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementTemplateCollectionTenantSummary', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementTemplateStep', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementTemplateStepTenantSummary', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersion', 
               'Update-MgBetaTenantRelationshipManagedTenantManagementTemplateStepVersionDeployment', 
               'Update-MgBetaTenantRelationshipManagedTenantMyRole', 
               'Update-MgBetaTenantRelationshipManagedTenantTag', 
               'Update-MgBetaTenantRelationshipManagedTenantTicketingEndpoint', 
               'Update-MgBetaTenantRelationshipManagedTenantWindowsDeviceMalwareState', 
               'Update-MgBetaTenantRelationshipManagedTenantWindowsProtectionState'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInzwYJKoZIhvcNAQcCoIInwDCCJ7wCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDw30M4YLEFETWe
# Kl7olLChkOdL/72hQSHjbHwMt3CCpKCCDYUwggYDMIID66ADAgECAhMzAAADri01
# UchTj1UdAAAAAAOuMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMxMTE2MTkwODU5WhcNMjQxMTE0MTkwODU5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQD0IPymNjfDEKg+YyE6SjDvJwKW1+pieqTjAY0CnOHZ1Nj5irGjNZPMlQ4HfxXG
# yAVCZcEWE4x2sZgam872R1s0+TAelOtbqFmoW4suJHAYoTHhkznNVKpscm5fZ899
# QnReZv5WtWwbD8HAFXbPPStW2JKCqPcZ54Y6wbuWV9bKtKPImqbkMcTejTgEAj82
# 6GQc6/Th66Koka8cUIvz59e/IP04DGrh9wkq2jIFvQ8EDegw1B4KyJTIs76+hmpV
# M5SwBZjRs3liOQrierkNVo11WuujB3kBf2CbPoP9MlOyyezqkMIbTRj4OHeKlamd
# WaSFhwHLJRIQpfc8sLwOSIBBAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUhx/vdKmXhwc4WiWXbsf0I53h8T8w
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMTgzNjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AGrJYDUS7s8o0yNprGXRXuAnRcHKxSjFmW4wclcUTYsQZkhnbMwthWM6cAYb/h2W
# 5GNKtlmj/y/CThe3y/o0EH2h+jwfU/9eJ0fK1ZO/2WD0xi777qU+a7l8KjMPdwjY
# 0tk9bYEGEZfYPRHy1AGPQVuZlG4i5ymJDsMrcIcqV8pxzsw/yk/O4y/nlOjHz4oV
# APU0br5t9tgD8E08GSDi3I6H57Ftod9w26h0MlQiOr10Xqhr5iPLS7SlQwj8HW37
# ybqsmjQpKhmWul6xiXSNGGm36GarHy4Q1egYlxhlUnk3ZKSr3QtWIo1GGL03hT57
# xzjL25fKiZQX/q+II8nuG5M0Qmjvl6Egltr4hZ3e3FQRzRHfLoNPq3ELpxbWdH8t
# Nuj0j/x9Crnfwbki8n57mJKI5JVWRWTSLmbTcDDLkTZlJLg9V1BIJwXGY3i2kR9i
# 5HsADL8YlW0gMWVSlKB1eiSlK6LmFi0rVH16dde+j5T/EaQtFz6qngN7d1lvO7uk
# 6rtX+MLKG4LDRsQgBTi6sIYiKntMjoYFHMPvI/OMUip5ljtLitVbkFGfagSqmbxK
# 7rJMhC8wiTzHanBg1Rrbff1niBbnFbbV4UDmYumjs1FIpFCazk6AADXxoKCo5TsO
# zSHqr9gHgGYQC2hMyX9MGLIpowYCURx3L7kUiGbOiMwaMIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGaAwghmcAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAOuLTVRyFOPVR0AAAAA
# A64wDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIDnw
# cn6qKImGlHcDmnf4ScmELyz1ZyQjHSrvhdT1WAV4MEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAhANLArzUrf+VaQXJWYmjG5ahqmdR6/KEg+de
# Y8uUjRnuplhepL5cTVqrB5RgcnlhVrwJbteS6FIo0f9+XX36RhBQ7vwRne77fvo3
# QRnKKU2rTFRL/O8fnI7ElmeX43JMtZFeuElzzQ83ZciYwpqLuGxkR2X4XNH/QK47
# F6tm8MfPyC0zsUOiauV/miUAOEW/147TxfoxPaRpLG6/xKRICWsEoQnvA84oq9mU
# 1XE4511YPS3zHd/gk90XkRFoKjMNHUZc0FNe2kQUX9M/4ubxnglU67AzKe1vhIDf
# EYoANCaQ4dhdMurMYkbDAdKk0N9dTlCYXQ/UAOUY+wu7dxJxzqGCFyowghcmBgor
# BgEEAYI3AwMBMYIXFjCCFxIGCSqGSIb3DQEHAqCCFwMwghb/AgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFXBgsqhkiG9w0BCRABBKCCAUYEggFCMIIBPgIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCBcnPzuMmGchZsozO/yBAVJa8Nh2w8Zj0qN
# SFVF5LT12gIGZfyAlFu6GBEyMDI0MDMyNjExNDkyMi4yWjAEgAIB9KCB2KSB1TCB
# 0jELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMk
# TWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1U
# aGFsZXMgVFNTIEVTTjo4NkRGLTRCQkMtOTMzNTElMCMGA1UEAxMcTWljcm9zb2Z0
# IFRpbWUtU3RhbXAgU2VydmljZaCCEXswggcnMIIFD6ADAgECAhMzAAAB3V1XHZXU
# raobAAEAAAHdMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
# EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
# QSAyMDEwMB4XDTIzMTAxMjE5MDcwOVoXDTI1MDExMDE5MDcwOVowgdIxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29m
# dCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEmMCQGA1UECxMdVGhhbGVzIFRT
# UyBFU046ODZERi00QkJDLTkzMzUxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0
# YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCoTgOU
# ROoud5x1ER+JZ3yi6fvSb4qbk7XLWoqwsTFEqz0suQlitg7a4kD/k+dh12zdoOwJ
# LUNaUGW0wxhcyundN72GDawj7iSvj0bD9hT1Q4wV8uZqy0RcyBxy2ogGqGxObxSb
# qMWdGVnSjArPGnI4R1Jn2mPu/fwke7jfgePsYyasL3aVP5qdJgKt3mq8h/gCpr+p
# ZK0DfM4K3GwoB8LKr76k+pRBamKYu7ip+zAGG0ni3tKTHWrVeRFujVZ1zGDk0Srh
# j38nwSnUobmpS6PPJBu6mtpmwOZe+/l9OiQHrDJKMmK+P/QoAxYx1KXB0jg7o5RQ
# SjItevM0XS3q3aVtGwV/RA7sdswTDGhCvDcsWsAhLgKu/vu5LRQG5d4VCrbs2AtR
# VGblJdgaulNe0uAirKkd4rS0/ajXG9qQCeI6yA3ZZeU4KKnn+YKb/mHLwTPN+G1x
# TcMrXd7oww9uD/Q3fMX1Sb7po7AUEJCuU/6stx60CfLndZx0r7RVYuUmv7mxrmBK
# UvIBehg1jefym73hZHbKE1SD6PKZFoYz7NEO5wOfrgcUAeM5YxIys+VluwQOMKZh
# ZtuH4QZkY1eDW6fp+/HIAI7w0n05QOg2AXL9pMdSR9nSIWkZ0njl3j0+oTBdCJef
# fCzLtK8N+VYlFnAEJFDVE8UZ6hhcc+cPmbrDAwIDAQABo4IBSTCCAUUwHQYDVR0O
# BBYEFG6i9baMj1HaRcsh0gylo9COJcPxMB8GA1UdIwQYMBaAFJ+nFV0AXmJdg/Tl
# 0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0
# LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAy
# MDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1T
# dGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/
# BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IC
# AQAuVNmyDS4FyB1mzHKlbn/Y5FE/yvM8iwb7uYfCa6mEds/3mjtsqNTqHPUocr8W
# 3vRmQ7u5JFM8UsidSGZLGWcOhQ6usmTU9zxIwBJ0RKUQS/Evpm14PjuFS0tC0pm/
# FyGYi7GqmdHwxHL9x3gPv8v6ipwkFpF4IaWhDMBjEM0ZIRsHBnV69cxqUOx08b37
# ue8RcWV9TJCp1hRDSerq3fuLXlIF49J4CDsf/5d1zCtx7fE9vs7xiTQBfuf+agZO
# 569O/cyAmxV78bYnTTeXqF3VvvawCJEvlBg9fQGXQa7benWfjnQKrgYg5GEOZFX1
# DCkt9ch0DhoJhcbgjs06Vh2pa6qXSJZbMvCjbI+VPbDjYlgHfTzZchBx20GQ5ovf
# wTZTmMk7dGHoS2w6L5mVDWs5O/TnfwPde5qgnU6qxMcARlD2zD/v73WFKmibKbqQ
# Z1LYzn/++gwIVcvHv3us0ffD5KZZpYjtm6y90N6w+vmQlXaxjPUZuoVAwQZL2Ifm
# I5hnXEORwelk/UXnPPqgx5m4S4V+GXWmq3efzl3i24Mdn+y+EEEI9yoKo6gzliJ1
# YTRNYGLU1ix3uPPNnf5Oy7otCtYPBGayg+5mjq7CSyjypXoHHifRQqmNbA1ClIUW
# tBB1FvmZCi5aISq0uxcI3ayDVpDwYG0M5wo3RNpuO0I02zCCB3EwggVZoAMCAQIC
# EzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
# AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBS
# b290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoX
# DTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
# b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
# dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC
# 0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VG
# Iwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP
# 2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/P
# XfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361
# VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwB
# Sru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9
# X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269e
# wvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDw
# wvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr
# 9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+e
# FnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAj
# BgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+n
# FV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEw
# PwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9j
# cy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3
# FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAf
# BgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBH
# hkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNS
# b29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUF
# BzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0Nl
# ckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4Swf
# ZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTC
# j/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu
# 2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/
# GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3D
# YXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbO
# xnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqO
# Cb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I
# 6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0
# zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaM
# mdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNT
# TY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggLXMIICQAIBATCCAQChgdikgdUwgdIx
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1p
# Y3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEmMCQGA1UECxMdVGhh
# bGVzIFRTUyBFU046ODZERi00QkJDLTkzMzUxJTAjBgNVBAMTHE1pY3Jvc29mdCBU
# aW1lLVN0YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVADYjRxll2zWgz8Z8og2x
# DnIkoxYQoIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
# b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
# dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwDQYJ
# KoZIhvcNAQEFBQACBQDprO2aMCIYDzIwMjQwMzI2MTQ0NTQ2WhgPMjAyNDAzMjcx
# NDQ1NDZaMHcwPQYKKwYBBAGEWQoEATEvMC0wCgIFAOms7ZoCAQAwCgIBAAICB/kC
# Af8wBwIBAAICEdgwCgIFAOmuPxoCAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYKKwYB
# BAGEWQoDAqAKMAgCAQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQUFAAOB
# gQBx8c218WlsaBk3sROIvnA8IYzIx/bQXqtPITRsQMIwZBvmtlumcBfC2LrCPzPB
# iUEISGQBqDOrK2nA9LZzqiHHIGdImCT0/p6KucWHniOWRoBonnxtC8xeOTn+Ytg1
# VVPoONexMi0agZjZ9VYLdSvmVmUS3kVuLyi2FveyVtIO7jGCBA0wggQJAgEBMIGT
# MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
# HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB3V1XHZXUraobAAEA
# AAHdMA0GCWCGSAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQ
# AQQwLwYJKoZIhvcNAQkEMSIEIAEDAAmuC5WUMkDgpvgjlCyysBFXAA9WLV6Wd16w
# TrxpMIH6BgsqhkiG9w0BCRACLzGB6jCB5zCB5DCBvQQgYf8OLZplrE94mZx7R9FZ
# N+1AjdNpUcWPkYjjesAxY2YwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQ
# Q0EgMjAxMAITMwAAAd1dVx2V1K2qGwABAAAB3TAiBCDvfrEg9dbTy/srKIXoRYh8
# FvLjkIK9nUrXSka2TKPMuTANBgkqhkiG9w0BAQsFAASCAgAfBFChjKpat9TCM4kE
# jaCPn2lnRyRGr35qK2r3lZ7/SAv33NalX/hBt9sQWX2Ituq6yrCyHYJLpqzuutHs
# 6bB7BK4ydUoGVRk3DvxtxSv7XmvCHlGDKgEafh3qhx/p+UcAWC8tPsssIj5hZmSU
# lLG6lLn246PrhO/vPIjUbcl/WmHirHP+nTK0MAbChEpdwMuCYzLZzqy24dcHtfmz
# 7HOCSkDLUZp++ufkyo+LTxQNs8F6eu0NJYFQzZz4tV5Vfp4yZhN02f6XAfSq4Q0e
# w8kSnmtPl7hIhejF/fFopZd+pKpVR6mceG1GPhvj6oqV/ZwkAT1DHWxtWtn4QF7C
# KnNX6TXK2NEuN1dAl78X1uLGZfGoJb5PzP87VjkYPve0O9vdumR5WYfGxiifAZB9
# h+Ja3whuY6hAwn+EA9RfQcQAlZWWTKAF2PQ3IO2sRzeopiEYUuLP4dsh3rNggytl
# 6ZGe0h51e44J/DoHHBtPDiEuygxKD5c6bopEUQj8jO0svHqKIWSxlIUfp89QKEAE
# omRRuRdyg3UPlnuhQS/qWdGR5UDHM4UeJECHo1NIxCsv8LiQTtXdnYODHP55jb/Y
# N+41sTVRz1X6Aj3cYuw2eRn/I/umZWiAZWNP0fTANa7Msh9BSYEqHElvRiv3KIuY
# +v2pTdseSyMUTfzUY+5QLTUERw==
# SIG # End signature block
