#
# Module manifest for module 'Microsoft.Graph.DeviceManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 3/26/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.DeviceManagement.psm1'

# Version number of this module.
ModuleVersion = '2.17.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '4131557d-8635-4903-9cfd-d59ddef4a597'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.17.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.DeviceManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.DeviceManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-MgAdminEdge', 'Get-MgAdminEdgeInternetExplorerMode', 
               'Get-MgAdminEdgeInternetExplorerModeSiteList', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListCount', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListSharedCookieCount', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListSite', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListSiteCount', 
               'Get-MgDeviceManagement', 'Get-MgDeviceManagementDetectedApp', 
               'Get-MgDeviceManagementDetectedAppCount', 
               'Get-MgDeviceManagementDetectedAppManagedDevice', 
               'Get-MgDeviceManagementDetectedAppManagedDeviceCount', 
               'Get-MgDeviceManagementDeviceCategory', 
               'Get-MgDeviceManagementDeviceCategoryCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicy', 
               'Get-MgDeviceManagementDeviceCompliancePolicyAssignment', 
               'Get-MgDeviceManagementDeviceCompliancePolicyAssignmentCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummaryCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceStatusCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Get-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Get-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Get-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfigurationCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Get-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Get-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingStateCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Get-MgDeviceManagementDeviceCompliancePolicyUserStatusCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Get-MgDeviceManagementDeviceConfiguration', 
               'Get-MgDeviceManagementDeviceConfigurationAssignment', 
               'Get-MgDeviceManagementDeviceConfigurationAssignmentCount', 
               'Get-MgDeviceManagementDeviceConfigurationCount', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummaryCount', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceStatus', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceStatusCount', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Get-MgDeviceManagementDeviceConfigurationUserStatus', 
               'Get-MgDeviceManagementDeviceConfigurationUserStatusCount', 
               'Get-MgDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Get-MgDeviceManagementManagedDevice', 
               'Get-MgDeviceManagementManagedDeviceCategory', 
               'Get-MgDeviceManagementManagedDeviceCompliancePolicyState', 
               'Get-MgDeviceManagementManagedDeviceCompliancePolicyStateCount', 
               'Get-MgDeviceManagementManagedDeviceConfigurationState', 
               'Get-MgDeviceManagementManagedDeviceConfigurationStateCount', 
               'Get-MgDeviceManagementManagedDeviceCount', 
               'Get-MgDeviceManagementManagedDeviceLogCollectionRequest', 
               'Get-MgDeviceManagementManagedDeviceLogCollectionRequestCount', 
               'Get-MgDeviceManagementManagedDeviceOverview', 
               'Get-MgDeviceManagementManagedDeviceUser', 
               'Get-MgDeviceManagementManagedDeviceWindowsProtectionState', 
               'Get-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Get-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareStateCount', 
               'Get-MgDeviceManagementMobileAppTroubleshootingEvent', 
               'Get-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Get-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequestCount', 
               'Get-MgDeviceManagementMobileAppTroubleshootingEventCount', 
               'Get-MgDeviceManagementNotificationMessageTemplate', 
               'Get-MgDeviceManagementNotificationMessageTemplateCount', 
               'Get-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Get-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessageCount', 
               'Get-MgDeviceManagementSoftwareUpdateStatusSummary', 
               'Get-MgDeviceManagementTroubleshootingEvent', 
               'Get-MgDeviceManagementTroubleshootingEventCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetail', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetailCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceId', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversionCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformance', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformanceCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformance', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetail', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetailCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformance', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformanceCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthOverview', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValue', 
               'Get-MgDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValueCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaseline', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaselineAppHealthMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaselineBatteryHealthMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaselineBestPracticeMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaselineCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaselineDeviceBootPerformanceMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaselineRebootAnalyticMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaselineResourcePerformanceMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticBaselineWorkFromAnywhereMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticCategory', 
               'Get-MgDeviceManagementUserExperienceAnalyticCategoryCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticCategoryMetricValue', 
               'Get-MgDeviceManagementUserExperienceAnalyticCategoryMetricValueCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticDevicePerformance', 
               'Get-MgDeviceManagementUserExperienceAnalyticDevicePerformanceCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticDeviceScore', 
               'Get-MgDeviceManagementUserExperienceAnalyticDeviceScoreCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticDeviceStartupHistory', 
               'Get-MgDeviceManagementUserExperienceAnalyticDeviceStartupHistoryCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcess', 
               'Get-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcessCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformance', 
               'Get-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformanceCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticMetricHistory', 
               'Get-MgDeviceManagementUserExperienceAnalyticMetricHistoryCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticModelScore', 
               'Get-MgDeviceManagementUserExperienceAnalyticModelScoreCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticOverview', 
               'Get-MgDeviceManagementUserExperienceAnalyticScoreHistory', 
               'Get-MgDeviceManagementUserExperienceAnalyticScoreHistoryCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereHardwareReadinessMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetric', 
               'Get-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDevice', 
               'Get-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDeviceCount', 
               'Get-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformance', 
               'Get-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformanceCount', 
               'Get-MgDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Get-MgDeviceManagementWindowsInformationProtectionAppLearningSummaryCount', 
               'Get-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Get-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummaryCount', 
               'Get-MgDeviceManagementWindowsMalwareInformation', 
               'Get-MgDeviceManagementWindowsMalwareInformationCount', 
               'Get-MgDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Get-MgDeviceManagementWindowsMalwareInformationDeviceMalwareStateCount', 
               'New-MgAdminEdgeInternetExplorerModeSiteList', 
               'New-MgAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'New-MgAdminEdgeInternetExplorerModeSiteListSite', 
               'New-MgDeviceManagementDetectedApp', 
               'New-MgDeviceManagementDeviceCategory', 
               'New-MgDeviceManagementDeviceCompliancePolicy', 
               'New-MgDeviceManagementDeviceCompliancePolicyAssignment', 
               'New-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'New-MgDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'New-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'New-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'New-MgDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'New-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'New-MgDeviceManagementDeviceCompliancePolicyUserStatus', 
               'New-MgDeviceManagementDeviceConfiguration', 
               'New-MgDeviceManagementDeviceConfigurationAssignment', 
               'New-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'New-MgDeviceManagementDeviceConfigurationDeviceStatus', 
               'New-MgDeviceManagementDeviceConfigurationUserStatus', 
               'New-MgDeviceManagementManagedDevice', 
               'New-MgDeviceManagementManagedDeviceCompliancePolicyState', 
               'New-MgDeviceManagementManagedDeviceConfigurationState', 
               'New-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'New-MgDeviceManagementMobileAppTroubleshootingEvent', 
               'New-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'New-MgDeviceManagementNotificationMessageTemplate', 
               'New-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'New-MgDeviceManagementTroubleshootingEvent', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetail', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceId', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformance', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformance', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetail', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformance', 
               'New-MgDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValue', 
               'New-MgDeviceManagementUserExperienceAnalyticBaseline', 
               'New-MgDeviceManagementUserExperienceAnalyticCategory', 
               'New-MgDeviceManagementUserExperienceAnalyticCategoryMetricValue', 
               'New-MgDeviceManagementUserExperienceAnalyticDevicePerformance', 
               'New-MgDeviceManagementUserExperienceAnalyticDeviceScore', 
               'New-MgDeviceManagementUserExperienceAnalyticDeviceStartupHistory', 
               'New-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcess', 
               'New-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformance', 
               'New-MgDeviceManagementUserExperienceAnalyticMetricHistory', 
               'New-MgDeviceManagementUserExperienceAnalyticModelScore', 
               'New-MgDeviceManagementUserExperienceAnalyticScoreHistory', 
               'New-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetric', 
               'New-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDevice', 
               'New-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformance', 
               'New-MgDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'New-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'New-MgDeviceManagementWindowsMalwareInformation', 
               'New-MgDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Remove-MgAdminEdge', 'Remove-MgAdminEdgeInternetExplorerMode', 
               'Remove-MgAdminEdgeInternetExplorerModeSiteList', 
               'Remove-MgAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Remove-MgAdminEdgeInternetExplorerModeSiteListSite', 
               'Remove-MgDeviceManagementDetectedApp', 
               'Remove-MgDeviceManagementDeviceCategory', 
               'Remove-MgDeviceManagementDeviceCompliancePolicy', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyAssignment', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Remove-MgDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Remove-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Remove-MgDeviceManagementDeviceConfiguration', 
               'Remove-MgDeviceManagementDeviceConfigurationAssignment', 
               'Remove-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Remove-MgDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Remove-MgDeviceManagementDeviceConfigurationDeviceStatus', 
               'Remove-MgDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Remove-MgDeviceManagementDeviceConfigurationUserStatus', 
               'Remove-MgDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Remove-MgDeviceManagementManagedDevice', 
               'Remove-MgDeviceManagementManagedDeviceCategory', 
               'Remove-MgDeviceManagementManagedDeviceCompliancePolicyState', 
               'Remove-MgDeviceManagementManagedDeviceConfigurationState', 
               'Remove-MgDeviceManagementManagedDeviceLogCollectionRequest', 
               'Remove-MgDeviceManagementManagedDeviceWindowsProtectionState', 
               'Remove-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Remove-MgDeviceManagementMobileAppTroubleshootingEvent', 
               'Remove-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Remove-MgDeviceManagementNotificationMessageTemplate', 
               'Remove-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Remove-MgDeviceManagementTroubleshootingEvent', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetail', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceId', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformance', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformance', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetail', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformance', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthOverview', 
               'Remove-MgDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValue', 
               'Remove-MgDeviceManagementUserExperienceAnalyticBaseline', 
               'Remove-MgDeviceManagementUserExperienceAnalyticCategory', 
               'Remove-MgDeviceManagementUserExperienceAnalyticCategoryMetricValue', 
               'Remove-MgDeviceManagementUserExperienceAnalyticDevicePerformance', 
               'Remove-MgDeviceManagementUserExperienceAnalyticDeviceScore', 
               'Remove-MgDeviceManagementUserExperienceAnalyticDeviceStartupHistory', 
               'Remove-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcess', 
               'Remove-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformance', 
               'Remove-MgDeviceManagementUserExperienceAnalyticMetricHistory', 
               'Remove-MgDeviceManagementUserExperienceAnalyticModelScore', 
               'Remove-MgDeviceManagementUserExperienceAnalyticOverview', 
               'Remove-MgDeviceManagementUserExperienceAnalyticScoreHistory', 
               'Remove-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereHardwareReadinessMetric', 
               'Remove-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetric', 
               'Remove-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDevice', 
               'Remove-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformance', 
               'Remove-MgDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Remove-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Remove-MgDeviceManagementWindowsMalwareInformation', 
               'Remove-MgDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Update-MgAdminEdge', 'Update-MgAdminEdgeInternetExplorerMode', 
               'Update-MgAdminEdgeInternetExplorerModeSiteList', 
               'Update-MgAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Update-MgAdminEdgeInternetExplorerModeSiteListSite', 
               'Update-MgDeviceManagement', 'Update-MgDeviceManagementDetectedApp', 
               'Update-MgDeviceManagementDeviceCategory', 
               'Update-MgDeviceManagementDeviceCompliancePolicy', 
               'Update-MgDeviceManagementDeviceCompliancePolicyAssignment', 
               'Update-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Update-MgDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Update-MgDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Update-MgDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Update-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Update-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Update-MgDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Update-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Update-MgDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Update-MgDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Update-MgDeviceManagementDeviceConfiguration', 
               'Update-MgDeviceManagementDeviceConfigurationAssignment', 
               'Update-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Update-MgDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Update-MgDeviceManagementDeviceConfigurationDeviceStatus', 
               'Update-MgDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Update-MgDeviceManagementDeviceConfigurationUserStatus', 
               'Update-MgDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Update-MgDeviceManagementManagedDevice', 
               'Update-MgDeviceManagementManagedDeviceCategory', 
               'Update-MgDeviceManagementManagedDeviceCompliancePolicyState', 
               'Update-MgDeviceManagementManagedDeviceConfigurationState', 
               'Update-MgDeviceManagementManagedDeviceLogCollectionRequest', 
               'Update-MgDeviceManagementManagedDeviceWindowsProtectionState', 
               'Update-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Update-MgDeviceManagementMobileAppTroubleshootingEvent', 
               'Update-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Update-MgDeviceManagementNotificationMessageTemplate', 
               'Update-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Update-MgDeviceManagementTroubleshootingEvent', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetail', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceId', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformance', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformance', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetail', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformance', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthOverview', 
               'Update-MgDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValue', 
               'Update-MgDeviceManagementUserExperienceAnalyticBaseline', 
               'Update-MgDeviceManagementUserExperienceAnalyticCategory', 
               'Update-MgDeviceManagementUserExperienceAnalyticCategoryMetricValue', 
               'Update-MgDeviceManagementUserExperienceAnalyticDevicePerformance', 
               'Update-MgDeviceManagementUserExperienceAnalyticDeviceScore', 
               'Update-MgDeviceManagementUserExperienceAnalyticDeviceStartupHistory', 
               'Update-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcess', 
               'Update-MgDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformance', 
               'Update-MgDeviceManagementUserExperienceAnalyticMetricHistory', 
               'Update-MgDeviceManagementUserExperienceAnalyticModelScore', 
               'Update-MgDeviceManagementUserExperienceAnalyticOverview', 
               'Update-MgDeviceManagementUserExperienceAnalyticScoreHistory', 
               'Update-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereHardwareReadinessMetric', 
               'Update-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetric', 
               'Update-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDevice', 
               'Update-MgDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformance', 
               'Update-MgDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Update-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Update-MgDeviceManagementWindowsMalwareInformation', 
               'Update-MgDeviceManagementWindowsMalwareInformationDeviceMalwareState'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIn0QYJKoZIhvcNAQcCoIInwjCCJ74CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCJxxgXZ/xcNtgp
# zBbCk1fyvEX1XlpLv5I+cpc3gn8mwaCCDYUwggYDMIID66ADAgECAhMzAAADri01
# UchTj1UdAAAAAAOuMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMxMTE2MTkwODU5WhcNMjQxMTE0MTkwODU5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQD0IPymNjfDEKg+YyE6SjDvJwKW1+pieqTjAY0CnOHZ1Nj5irGjNZPMlQ4HfxXG
# yAVCZcEWE4x2sZgam872R1s0+TAelOtbqFmoW4suJHAYoTHhkznNVKpscm5fZ899
# QnReZv5WtWwbD8HAFXbPPStW2JKCqPcZ54Y6wbuWV9bKtKPImqbkMcTejTgEAj82
# 6GQc6/Th66Koka8cUIvz59e/IP04DGrh9wkq2jIFvQ8EDegw1B4KyJTIs76+hmpV
# M5SwBZjRs3liOQrierkNVo11WuujB3kBf2CbPoP9MlOyyezqkMIbTRj4OHeKlamd
# WaSFhwHLJRIQpfc8sLwOSIBBAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUhx/vdKmXhwc4WiWXbsf0I53h8T8w
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMTgzNjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AGrJYDUS7s8o0yNprGXRXuAnRcHKxSjFmW4wclcUTYsQZkhnbMwthWM6cAYb/h2W
# 5GNKtlmj/y/CThe3y/o0EH2h+jwfU/9eJ0fK1ZO/2WD0xi777qU+a7l8KjMPdwjY
# 0tk9bYEGEZfYPRHy1AGPQVuZlG4i5ymJDsMrcIcqV8pxzsw/yk/O4y/nlOjHz4oV
# APU0br5t9tgD8E08GSDi3I6H57Ftod9w26h0MlQiOr10Xqhr5iPLS7SlQwj8HW37
# ybqsmjQpKhmWul6xiXSNGGm36GarHy4Q1egYlxhlUnk3ZKSr3QtWIo1GGL03hT57
# xzjL25fKiZQX/q+II8nuG5M0Qmjvl6Egltr4hZ3e3FQRzRHfLoNPq3ELpxbWdH8t
# Nuj0j/x9Crnfwbki8n57mJKI5JVWRWTSLmbTcDDLkTZlJLg9V1BIJwXGY3i2kR9i
# 5HsADL8YlW0gMWVSlKB1eiSlK6LmFi0rVH16dde+j5T/EaQtFz6qngN7d1lvO7uk
# 6rtX+MLKG4LDRsQgBTi6sIYiKntMjoYFHMPvI/OMUip5ljtLitVbkFGfagSqmbxK
# 7rJMhC8wiTzHanBg1Rrbff1niBbnFbbV4UDmYumjs1FIpFCazk6AADXxoKCo5TsO
# zSHqr9gHgGYQC2hMyX9MGLIpowYCURx3L7kUiGbOiMwaMIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGaIwghmeAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAOuLTVRyFOPVR0AAAAA
# A64wDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEILgg
# kf8vV5+Gmft5L1pOzHFN3H02UoamSDqzTE8JwA8NMEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAC/oYvs8UunigijKIMv0Sn0qEg//oZq+fLdoe
# HFTKD0GKyPLUxig6xpzk3dpe6r8cK/UjEt3qClk+Pq8EXg6CcB6AtPFBKDUAkE9L
# s5gR0TSIoPyDojkc8tOrpOpCU2TKYoqFmH3fJdOR7Am82VwluHB2/fdQgdKNzaPD
# bvq+KOzdan8mmUG/IQQknLF7nEsyJhqTk5V5rL8IJb2jMQv1aa52rPEnJunA8KBa
# CWmXN8Piqa9wTQOxwF7fgpbb+UvB1sf+Q/0MEDy/012Ky6u7cUlFI2Uh5l77aj54
# MgPA3/g6hJ+Ng8ARV58ixWqB3MFBWw/AGn7MG46rj+22QdZV1qGCFywwghcoBgor
# BgEEAYI3AwMBMYIXGDCCFxQGCSqGSIb3DQEHAqCCFwUwghcBAgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFZBgsqhkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCDl2pqREHrrTsHicV8EnWMUxXMbrXPAD58Y
# jOduGfGTBwIGZfxnLw8sGBMyMDI0MDMyNjExNDkyMi41NDVaMASAAgH0oIHYpIHV
# MIHSMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsT
# HVRoYWxlcyBUU1MgRVNOOjE3OUUtNEJCMC04MjQ2MSUwIwYDVQQDExxNaWNyb3Nv
# ZnQgVGltZS1TdGFtcCBTZXJ2aWNloIIRezCCBycwggUPoAMCAQICEzMAAAHg1Pwf
# ExUffl0AAQAAAeAwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# UENBIDIwMTAwHhcNMjMxMDEyMTkwNzE5WhcNMjUwMTEwMTkwNzE5WjCB0jELMAkG
# A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
# HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9z
# b2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMg
# VFNTIEVTTjoxNzlFLTRCQjAtODI0NjElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgU2VydmljZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKyH
# nPOhxbvRATnGjb/6fuBhh3ZLzotAxAgdLaZ/zkRFUdeSKzyNt3tqorMK7GDvcXdK
# s+qIMUbvenlH+w53ssPa6rYP760ZuFrABrfserf0kFayNXVzwT7jarJOEjnFMBp+
# yi+uwQ2TnJuxczceG5FDHrII6sF6F879lP6ydY0BBZkZ9t39e/svNRieA5gUnv/Y
# cM/bIMY/QYmd9F0B+ebFYi+PH4AkXahNkFgK85OIaRrDGvhnxOa/5zGL7Oiii7+J
# 9/QHkdJGlfnRfbQ3QXM/5/umBOKG4JoFY1niZ5RVH5PT0+uCjwcqhTbnvUtfK+N+
# yB2b9rEZvp2Tv4ZwYzEd9A9VsYMuZiCSbaFMk77LwVbklpnw4aHWJXJkEYmJvxRb
# cThE8FQyOoVkSuKc5OWZ2+WM/j50oblA0tCU53AauvUOZRoQBh89nHK+m5pOXKXd
# YMJ+ceuLYF8h5y/cXLQMOmqLJz5l7MLqGwU0zHV+MEO8L1Fo2zEEQ4iL4BX8YknK
# XonHGQacSCaLZot2kyJVRsFSxn0PlPvHVp0YdsCMzdeiw9jAZ7K9s1WxsZGEBrK/
# obipX6uxjEpyUA9mbVPljlb3R4MWI0E2xI/NM6F4Ac8Ceax3YWLT+aWCZeqiIMLx
# yyWZg+i1KY8ZEzMeNTKCEI5wF1wxqr6T1/MQo+8tAgMBAAGjggFJMIIBRTAdBgNV
# HQ4EFgQUcF4XP26dV+8SusoA1XXQ2TDSmdIwHwYDVR0jBBgwFoAUn6cVXQBeYl2D
# 9OXSZacbUzUZ6XIwXwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3Nv
# ZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUy
# MDIwMTAoMSkuY3JsMGwGCCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1l
# LVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUB
# Af8EDDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQAD
# ggIBAMATzg6R/A0ldO7MqGxD1VJji5yVA1hHb0Hc0Yjtv7WkxQ8iwfflulX5Us64
# tD3+3NT1JkphWzaAWf2wKdAw35RxtQG1iON3HEZ0X23nde4Kg/Wfbx5rEHkZ9bzK
# nR/2N5A16+w/1pbwJzdfRcnJT3cLyawr/kYjMWd63OP0Glq70ua4WUE/Po5pU7rQ
# RbWEoQozY24hAqOcwuRcm6Cb0JBeTOCeRBntEKgjKep4pRaQt7b9vusT97WeJcfa
# VosmmPtsZsawgnpIjbBa55tHfuk0vDkZtbIXjU4mr5dns9dnanBdBS2PY3N3hIfC
# PEOszquwHLkfkFZ/9bxw8/eRJldtoukHo16afE/AqP/smmGJh5ZR0pmgW6QcX+61
# rdi5kDJTzCFaoMyYzUS0SEbyrDZ/p2KOuKAYNngljiOlllct0uJVz2agfczGjjsK
# i2AS1WaXvOhgZNmGw42SFB1qaloa8Kaux9Q2HHLE8gee/5rgOnx9zSbfVUc7IcRN
# odq6R7v+Rz+P6XKtOgyCqW/+rhPmp/n7Fq2BGTRkcy//hmS32p6qyglr2K4OoJDJ
# XxFs6lwc8D86qlUeGjUyo7hVy5VvyA+y0mGnEAuA85tsOcUPlzwWF5sv+B5fz35O
# W3X4Spk5SiNulnLFRPM5XCsSHqvcbC8R3qwj2w1evPhZxDuNMIIHcTCCBVmgAwIB
# AgITMwAAABXF52ueAptJmQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UE
# BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
# BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0
# IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1
# WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O
# 1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZn
# hUYjDLWNE893MsAQGOhgfWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t
# 1w/YJlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxq
# D89d9P6OU8/W7IVWTe/dvI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmP
# frVUj9z6BVWYbWg7mka97aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSW
# rAFKu75xqRdbZ2De+JKRHh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv
# 231fgLrbqn427DZM9ituqBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zb
# r17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYcten
# IPDC+hIK12NvDMk2ZItboKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQc
# xWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17a
# j54WcmnGrnu3tz5q4i6tAgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQAB
# MCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQU
# n6cVXQBeYl2D9OXSZacbUzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEw
# QTA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9E
# b2NzL1JlcG9zaXRvcnkuaHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQB
# gjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/
# MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJ
# oEeGRWh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01p
# Y1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYB
# BQUHMAKGPmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9v
# Q2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3h
# LB9nATEkW+Geckv8qW/qXBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x
# 5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74p
# y27YP0h1AdkY3m2CDPVtI1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1A
# oL8ZthISEV09J+BAljis9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbC
# HcNhcy4sa3tuPywJeBTpkbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB
# 9s7GdP32THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNt
# yo4JvbMBV0lUZNlz138eW0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3
# rsjoiV5PndLQTHa1V1QJsWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcV
# v7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A24
# 5oyZ1uEi6vAnQj0llOZ0dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lw
# Y1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCAtcwggJAAgEBMIIBAKGB2KSB1TCB
# 0jELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMk
# TWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1U
# aGFsZXMgVFNTIEVTTjoxNzlFLTRCQjAtODI0NjElMCMGA1UEAxMcTWljcm9zb2Z0
# IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsOAwIaAxUAbfPR1fBX6HxYfyPx
# 8zYzJU5fIQyggYMwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAN
# BgkqhkiG9w0BAQUFAAIFAOms04kwIhgPMjAyNDAzMjYxMjU0MzNaGA8yMDI0MDMy
# NzEyNTQzM1owdzA9BgorBgEEAYRZCgQBMS8wLTAKAgUA6azTiQIBADAKAgEAAgIx
# YQIB/zAHAgEAAgISfjAKAgUA6a4lCQIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgor
# BgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUA
# A4GBAK3Z9Vzg21cTFWo/VZISMrFXOT22FE/62JsKmMIKVB7IYVRStN1yMwbcbJx9
# WlmaeZhXAyNDqbD/WRad60L/46VrBBrHjsUGimlAYrWwU+y/grGHltG7+OuxKlxT
# S2eBxCVnrj8lRE20Clpnyms/j4OxZsqI780pWHklrDL0YpUhMYIEDTCCBAkCAQEw
# gZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
# B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UE
# AxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAHg1PwfExUffl0A
# AQAAAeAwDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0B
# CRABBDAvBgkqhkiG9w0BCQQxIgQgUsv+jYKvWeayHcNIwBJJMn1s7wEvfpPCq+FT
# cG/bd38wgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCDj7lK/8jnlbTjPvc77
# DCCSb4TZApY9nJm5whsK/2kKwTCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwAhMzAAAB4NT8HxMVH35dAAEAAAHgMCIEIFi0Ze1l7+aQqE8n46ps
# 7bF0rOt6gEndliti4YM5ihDxMA0GCSqGSIb3DQEBCwUABIICABQsZAEcxaezAFpm
# krI07/MbAICHlR75J61ivpUAm3a3TTuHQhjag1Wka6Gnn3wyonVXGXrNLCHPRqAd
# BskiURtfOK6WuNgnxeFoharHFSxyX5TnEwbu5S9k1C7mESm31Jsj0Oa5//6YXRQr
# QmQhuNqG+VbBMFtlTxQm/OuiF4jusm+JHP0WbCkxERA1Egl71yTzPK8YrwIBiNbk
# b3c8+VSXTRiNOswma7MjgoY9XKexGKRRy1zm9KderObBp8poiKyrcITUzgbJmCgO
# yhbUCqTx2zyCoB/maWx+BB0L6bj8lghRoqzq6XKjujI+vO7LM5giVi7hiFdKHZqc
# xXGcbVPwdrwWfWH34kDYdoH6j0eDjFQgYil75zbY8Nm1jFxVpmOaPRAhdpWJpclW
# /PuFzbe+t8tPK6uIVDD025H0NXBlnMjs0Vuzhia0qz66UO6wNPTxcG1ACByrV50M
# CbfmzF4Avl3U9T3B3uRMuyHIAYYTzpuVpLWsgdZcFfrO5DVN5SD6w8OXsd7SZF0u
# ti5k+NDsaJdEAjUMi092YgC2/6VYshMew/P0c0D+Nsg9enLPpkDvYMaFTxLgZNXS
# IvwC2VoDuptuVypV8oM3AIKNFf0NbFfUCmdQbHWfl8XFfhs43C+QT6yimkoUMcXt
# MtUoguVRIsr6B65tMiSgjuxLETOH
# SIG # End signature block
