#
# Module manifest for module 'Microsoft.Graph.Beta.Files'
#
# Generated by: Microsoft Corporation
#
# Generated on: 3/7/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.Files.psm1'

# Version number of this module.
ModuleVersion = '2.16.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd6278476-f9b5-4d1e-909c-110aff851952'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.16.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Beta.Files.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Beta.Files.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgBetaDriveListContentTypeCopy', 
               'Add-MgBetaDriveListContentTypeCopyFromContentTypeHub', 
               'Add-MgBetaShareListContentTypeCopy', 
               'Add-MgBetaShareListContentTypeCopyFromContentTypeHub', 
               'Copy-MgBetaDriveItem', 
               'Copy-MgBetaDriveListContentTypeToDefaultContentLocation', 
               'Copy-MgBetaDriveRoot', 
               'Copy-MgBetaShareListContentTypeToDefaultContentLocation', 
               'Get-MgBetaDrive', 'Get-MgBetaDriveActivity', 'Get-MgBetaDriveBundle', 
               'Get-MgBetaDriveBundleContent', 'Get-MgBetaDriveBundleCount', 
               'Get-MgBetaDriveContentTypeBase', 
               'Get-MgBetaDriveContentTypeBaseType', 
               'Get-MgBetaDriveContentTypeBaseTypeCount', 
               'Get-MgBetaDriveCreatedByUser', 
               'Get-MgBetaDriveCreatedByUserMailboxSetting', 
               'Get-MgBetaDriveCreatedByUserServiceProvisioningError', 
               'Get-MgBetaDriveCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveFollowing', 'Get-MgBetaDriveFollowingContent', 
               'Get-MgBetaDriveFollowingCount', 'Get-MgBetaDriveItem', 
               'Get-MgBetaDriveItemActivity', 
               'Get-MgBetaDriveItemActivityByInterval', 
               'Get-MgBetaDriveItemAnalytic', 
               'Get-MgBetaDriveItemAnalyticItemActivityStat', 
               'Get-MgBetaDriveItemAnalyticItemActivityStatActivity', 
               'Get-MgBetaDriveItemAnalyticItemActivityStatCount', 
               'Get-MgBetaDriveItemAnalyticLastSevenDay', 
               'Get-MgBetaDriveItemAnalyticTime', 'Get-MgBetaDriveItemChild', 
               'Get-MgBetaDriveItemChildContent', 'Get-MgBetaDriveItemChildCount', 
               'Get-MgBetaDriveItemContent', 'Get-MgBetaDriveItemCount', 
               'Get-MgBetaDriveItemCreatedByUser', 
               'Get-MgBetaDriveItemCreatedByUserMailboxSetting', 
               'Get-MgBetaDriveItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaDriveItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveItemDelta', 
               'Get-MgBetaDriveItemItemLastModifiedByUser', 
               'Get-MgBetaDriveItemItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaDriveItemItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaDriveItemItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveItemLastModifiedByUser', 
               'Get-MgBetaDriveItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaDriveItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaDriveItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveItemListItem', 
               'Get-MgBetaDriveItemListItemActivity', 
               'Get-MgBetaDriveItemListItemActivityByInterval', 
               'Get-MgBetaDriveItemListItemAnalytic', 
               'Get-MgBetaDriveItemListItemCreatedByUser', 
               'Get-MgBetaDriveItemListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaDriveItemListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaDriveItemListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveItemListItemDocumentSetVersion', 
               'Get-MgBetaDriveItemListItemDocumentSetVersionCount', 
               'Get-MgBetaDriveItemListItemDocumentSetVersionField', 
               'Get-MgBetaDriveItemListItemDriveItem', 
               'Get-MgBetaDriveItemListItemDriveItemContent', 
               'Get-MgBetaDriveItemListItemField', 
               'Get-MgBetaDriveItemListItemVersion', 
               'Get-MgBetaDriveItemListItemVersionCount', 
               'Get-MgBetaDriveItemListItemVersionField', 
               'Get-MgBetaDriveItemPermission', 
               'Get-MgBetaDriveItemPermissionCount', 
               'Get-MgBetaDriveItemRetentionLabel', 
               'Get-MgBetaDriveItemSubscription', 
               'Get-MgBetaDriveItemSubscriptionCount', 
               'Get-MgBetaDriveItemThumbnail', 'Get-MgBetaDriveItemThumbnailCount', 
               'Get-MgBetaDriveItemVersion', 'Get-MgBetaDriveItemVersionContent', 
               'Get-MgBetaDriveItemVersionCount', 
               'Get-MgBetaDriveLastModifiedByUser', 
               'Get-MgBetaDriveLastModifiedByUserMailboxSetting', 
               'Get-MgBetaDriveLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaDriveLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveList', 'Get-MgBetaDriveListActivity', 
               'Get-MgBetaDriveListColumn', 'Get-MgBetaDriveListColumnCount', 
               'Get-MgBetaDriveListColumnSourceColumn', 
               'Get-MgBetaDriveListContentType', 
               'Get-MgBetaDriveListContentTypeColumn', 
               'Get-MgBetaDriveListContentTypeColumnCount', 
               'Get-MgBetaDriveListContentTypeColumnLink', 
               'Get-MgBetaDriveListContentTypeColumnLinkCount', 
               'Get-MgBetaDriveListContentTypeColumnPosition', 
               'Get-MgBetaDriveListContentTypeColumnPositionCount', 
               'Get-MgBetaDriveListContentTypeColumnSourceColumn', 
               'Get-MgBetaDriveListContentTypeCompatibleHubContentType', 
               'Get-MgBetaDriveListContentTypeCount', 
               'Get-MgBetaDriveListCreatedByUser', 
               'Get-MgBetaDriveListCreatedByUserMailboxSetting', 
               'Get-MgBetaDriveListCreatedByUserServiceProvisioningError', 
               'Get-MgBetaDriveListCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveListDrive', 'Get-MgBetaDriveListItem', 
               'Get-MgBetaDriveListItemActivity', 
               'Get-MgBetaDriveListItemActivityByInterval', 
               'Get-MgBetaDriveListItemAnalytic', 'Get-MgBetaDriveListItemCount', 
               'Get-MgBetaDriveListItemCreatedByUser', 
               'Get-MgBetaDriveListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaDriveListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaDriveListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveListItemDelta', 
               'Get-MgBetaDriveListItemDocumentSetVersion', 
               'Get-MgBetaDriveListItemDocumentSetVersionCount', 
               'Get-MgBetaDriveListItemDocumentSetVersionField', 
               'Get-MgBetaDriveListItemDriveItem', 
               'Get-MgBetaDriveListItemDriveItemContent', 
               'Get-MgBetaDriveListItemField', 'Get-MgBetaDriveListItemVersion', 
               'Get-MgBetaDriveListItemVersionCount', 
               'Get-MgBetaDriveListItemVersionField', 
               'Get-MgBetaDriveListOperation', 'Get-MgBetaDriveListOperationCount', 
               'Get-MgBetaDriveListSubscription', 
               'Get-MgBetaDriveListSubscriptionCount', 'Get-MgBetaDriveRoot', 
               'Get-MgBetaDriveRootActivity', 
               'Get-MgBetaDriveRootActivityByInterval', 
               'Get-MgBetaDriveRootAnalytic', 
               'Get-MgBetaDriveRootAnalyticItemActivityStat', 
               'Get-MgBetaDriveRootAnalyticItemActivityStatActivity', 
               'Get-MgBetaDriveRootAnalyticItemActivityStatCount', 
               'Get-MgBetaDriveRootAnalyticLastSevenDay', 
               'Get-MgBetaDriveRootAnalyticTime', 'Get-MgBetaDriveRootChild', 
               'Get-MgBetaDriveRootChildContent', 'Get-MgBetaDriveRootChildCount', 
               'Get-MgBetaDriveRootContent', 'Get-MgBetaDriveRootCreatedByUser', 
               'Get-MgBetaDriveRootCreatedByUserMailboxSetting', 
               'Get-MgBetaDriveRootCreatedByUserServiceProvisioningError', 
               'Get-MgBetaDriveRootCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveRootDelta', 
               'Get-MgBetaDriveRootItemLastModifiedByUser', 
               'Get-MgBetaDriveRootItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaDriveRootItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaDriveRootItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveRootLastModifiedByUser', 
               'Get-MgBetaDriveRootLastModifiedByUserMailboxSetting', 
               'Get-MgBetaDriveRootLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaDriveRootLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveRootListItem', 
               'Get-MgBetaDriveRootListItemActivity', 
               'Get-MgBetaDriveRootListItemActivityByInterval', 
               'Get-MgBetaDriveRootListItemAnalytic', 
               'Get-MgBetaDriveRootListItemCreatedByUser', 
               'Get-MgBetaDriveRootListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaDriveRootListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaDriveRootListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaDriveRootListItemDocumentSetVersion', 
               'Get-MgBetaDriveRootListItemDocumentSetVersionCount', 
               'Get-MgBetaDriveRootListItemDocumentSetVersionField', 
               'Get-MgBetaDriveRootListItemDriveItem', 
               'Get-MgBetaDriveRootListItemDriveItemContent', 
               'Get-MgBetaDriveRootListItemField', 
               'Get-MgBetaDriveRootListItemVersion', 
               'Get-MgBetaDriveRootListItemVersionCount', 
               'Get-MgBetaDriveRootListItemVersionField', 
               'Get-MgBetaDriveRootPermission', 
               'Get-MgBetaDriveRootPermissionCount', 
               'Get-MgBetaDriveRootRetentionLabel', 
               'Get-MgBetaDriveRootSubscription', 
               'Get-MgBetaDriveRootSubscriptionCount', 
               'Get-MgBetaDriveRootThumbnail', 'Get-MgBetaDriveRootThumbnailCount', 
               'Get-MgBetaDriveRootVersion', 'Get-MgBetaDriveRootVersionContent', 
               'Get-MgBetaDriveRootVersionCount', 'Get-MgBetaDriveSpecial', 
               'Get-MgBetaDriveSpecialContent', 'Get-MgBetaDriveSpecialCount', 
               'Get-MgBetaGroupDefaultDrive', 'Get-MgBetaGroupDrive', 
               'Get-MgBetaGroupDriveActivity', 'Get-MgBetaGroupDriveBundle', 
               'Get-MgBetaGroupDriveBundleContent', 
               'Get-MgBetaGroupDriveBundleCount', 
               'Get-MgBetaGroupDriveContentTypeBase', 
               'Get-MgBetaGroupDriveContentTypeBaseType', 
               'Get-MgBetaGroupDriveContentTypeBaseTypeCount', 
               'Get-MgBetaGroupDriveCount', 'Get-MgBetaGroupDriveCreatedByUser', 
               'Get-MgBetaGroupDriveCreatedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveCreatedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveFollowing', 
               'Get-MgBetaGroupDriveFollowingContent', 
               'Get-MgBetaGroupDriveFollowingCount', 'Get-MgBetaGroupDriveItem', 
               'Get-MgBetaGroupDriveItemActivity', 
               'Get-MgBetaGroupDriveItemAnalytic', 
               'Get-MgBetaGroupDriveItemAnalyticItemActivityStat', 
               'Get-MgBetaGroupDriveItemAnalyticItemActivityStatActivity', 
               'Get-MgBetaGroupDriveItemAnalyticItemActivityStatCount', 
               'Get-MgBetaGroupDriveItemAnalyticLastSevenDay', 
               'Get-MgBetaGroupDriveItemAnalyticTime', 
               'Get-MgBetaGroupDriveItemChild', 
               'Get-MgBetaGroupDriveItemChildContent', 
               'Get-MgBetaGroupDriveItemChildCount', 
               'Get-MgBetaGroupDriveItemContent', 'Get-MgBetaGroupDriveItemCount', 
               'Get-MgBetaGroupDriveItemCreatedByUser', 
               'Get-MgBetaGroupDriveItemCreatedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveItemItemLastModifiedByUser', 
               'Get-MgBetaGroupDriveItemItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveItemItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveItemItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveItemLastModifiedByUser', 
               'Get-MgBetaGroupDriveItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveItemListItem', 
               'Get-MgBetaGroupDriveItemListItemActivity', 
               'Get-MgBetaGroupDriveItemListItemAnalytic', 
               'Get-MgBetaGroupDriveItemListItemCreatedByUser', 
               'Get-MgBetaGroupDriveItemListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveItemListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveItemListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveItemListItemDocumentSetVersion', 
               'Get-MgBetaGroupDriveItemListItemDocumentSetVersionCount', 
               'Get-MgBetaGroupDriveItemListItemDocumentSetVersionField', 
               'Get-MgBetaGroupDriveItemListItemDriveItem', 
               'Get-MgBetaGroupDriveItemListItemDriveItemContent', 
               'Get-MgBetaGroupDriveItemListItemField', 
               'Get-MgBetaGroupDriveItemListItemVersion', 
               'Get-MgBetaGroupDriveItemListItemVersionCount', 
               'Get-MgBetaGroupDriveItemListItemVersionField', 
               'Get-MgBetaGroupDriveItemPermission', 
               'Get-MgBetaGroupDriveItemPermissionCount', 
               'Get-MgBetaGroupDriveItemRetentionLabel', 
               'Get-MgBetaGroupDriveItemSubscription', 
               'Get-MgBetaGroupDriveItemSubscriptionCount', 
               'Get-MgBetaGroupDriveItemThumbnail', 
               'Get-MgBetaGroupDriveItemThumbnailCount', 
               'Get-MgBetaGroupDriveItemVersion', 
               'Get-MgBetaGroupDriveItemVersionContent', 
               'Get-MgBetaGroupDriveItemVersionCount', 
               'Get-MgBetaGroupDriveLastModifiedByUser', 
               'Get-MgBetaGroupDriveLastModifiedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveList', 'Get-MgBetaGroupDriveListActivity', 
               'Get-MgBetaGroupDriveListColumn', 
               'Get-MgBetaGroupDriveListColumnCount', 
               'Get-MgBetaGroupDriveListColumnSourceColumn', 
               'Get-MgBetaGroupDriveListContentType', 
               'Get-MgBetaGroupDriveListContentTypeColumn', 
               'Get-MgBetaGroupDriveListContentTypeColumnCount', 
               'Get-MgBetaGroupDriveListContentTypeColumnLink', 
               'Get-MgBetaGroupDriveListContentTypeColumnLinkCount', 
               'Get-MgBetaGroupDriveListContentTypeColumnPosition', 
               'Get-MgBetaGroupDriveListContentTypeColumnPositionCount', 
               'Get-MgBetaGroupDriveListContentTypeColumnSourceColumn', 
               'Get-MgBetaGroupDriveListContentTypeCount', 
               'Get-MgBetaGroupDriveListCreatedByUser', 
               'Get-MgBetaGroupDriveListCreatedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveListCreatedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveListCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveListDrive', 'Get-MgBetaGroupDriveListItem', 
               'Get-MgBetaGroupDriveListItemActivity', 
               'Get-MgBetaGroupDriveListItemAnalytic', 
               'Get-MgBetaGroupDriveListItemCreatedByUser', 
               'Get-MgBetaGroupDriveListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveListItemDocumentSetVersion', 
               'Get-MgBetaGroupDriveListItemDocumentSetVersionCount', 
               'Get-MgBetaGroupDriveListItemDocumentSetVersionField', 
               'Get-MgBetaGroupDriveListItemDriveItem', 
               'Get-MgBetaGroupDriveListItemDriveItemContent', 
               'Get-MgBetaGroupDriveListItemField', 
               'Get-MgBetaGroupDriveListItemVersion', 
               'Get-MgBetaGroupDriveListItemVersionCount', 
               'Get-MgBetaGroupDriveListItemVersionField', 
               'Get-MgBetaGroupDriveListOperation', 
               'Get-MgBetaGroupDriveListOperationCount', 
               'Get-MgBetaGroupDriveListSubscription', 
               'Get-MgBetaGroupDriveListSubscriptionCount', 
               'Get-MgBetaGroupDriveRoot', 'Get-MgBetaGroupDriveRootActivity', 
               'Get-MgBetaGroupDriveRootAnalytic', 
               'Get-MgBetaGroupDriveRootAnalyticItemActivityStat', 
               'Get-MgBetaGroupDriveRootAnalyticItemActivityStatActivity', 
               'Get-MgBetaGroupDriveRootAnalyticItemActivityStatCount', 
               'Get-MgBetaGroupDriveRootAnalyticLastSevenDay', 
               'Get-MgBetaGroupDriveRootAnalyticTime', 
               'Get-MgBetaGroupDriveRootChild', 
               'Get-MgBetaGroupDriveRootChildContent', 
               'Get-MgBetaGroupDriveRootChildCount', 
               'Get-MgBetaGroupDriveRootContent', 
               'Get-MgBetaGroupDriveRootCreatedByUser', 
               'Get-MgBetaGroupDriveRootCreatedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveRootCreatedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveRootCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveRootItemLastModifiedByUser', 
               'Get-MgBetaGroupDriveRootItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveRootItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveRootItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveRootLastModifiedByUser', 
               'Get-MgBetaGroupDriveRootLastModifiedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveRootLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveRootLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveRootListItem', 
               'Get-MgBetaGroupDriveRootListItemActivity', 
               'Get-MgBetaGroupDriveRootListItemAnalytic', 
               'Get-MgBetaGroupDriveRootListItemCreatedByUser', 
               'Get-MgBetaGroupDriveRootListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaGroupDriveRootListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaGroupDriveRootListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaGroupDriveRootListItemDocumentSetVersion', 
               'Get-MgBetaGroupDriveRootListItemDocumentSetVersionCount', 
               'Get-MgBetaGroupDriveRootListItemDocumentSetVersionField', 
               'Get-MgBetaGroupDriveRootListItemDriveItem', 
               'Get-MgBetaGroupDriveRootListItemDriveItemContent', 
               'Get-MgBetaGroupDriveRootListItemField', 
               'Get-MgBetaGroupDriveRootListItemVersion', 
               'Get-MgBetaGroupDriveRootListItemVersionCount', 
               'Get-MgBetaGroupDriveRootListItemVersionField', 
               'Get-MgBetaGroupDriveRootPermission', 
               'Get-MgBetaGroupDriveRootPermissionCount', 
               'Get-MgBetaGroupDriveRootRetentionLabel', 
               'Get-MgBetaGroupDriveRootSubscription', 
               'Get-MgBetaGroupDriveRootSubscriptionCount', 
               'Get-MgBetaGroupDriveRootThumbnail', 
               'Get-MgBetaGroupDriveRootThumbnailCount', 
               'Get-MgBetaGroupDriveRootVersion', 
               'Get-MgBetaGroupDriveRootVersionContent', 
               'Get-MgBetaGroupDriveRootVersionCount', 
               'Get-MgBetaGroupDriveSpecial', 'Get-MgBetaGroupDriveSpecialContent', 
               'Get-MgBetaGroupDriveSpecialCount', 
               'Get-MgBetaShareContentTypeBase', 
               'Get-MgBetaShareContentTypeBaseType', 
               'Get-MgBetaShareContentTypeBaseTypeCount', 'Get-MgBetaShareCount', 
               'Get-MgBetaShareCreatedByUser', 
               'Get-MgBetaShareCreatedByUserMailboxSetting', 
               'Get-MgBetaShareCreatedByUserServiceProvisioningError', 
               'Get-MgBetaShareCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaShareDriveItem', 'Get-MgBetaShareDriveItemContent', 
               'Get-MgBetaShareItem', 'Get-MgBetaShareItemContent', 
               'Get-MgBetaShareItemCount', 'Get-MgBetaShareItemLastModifiedByUser', 
               'Get-MgBetaShareItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaShareItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaShareItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaShareLastModifiedByUser', 
               'Get-MgBetaShareLastModifiedByUserMailboxSetting', 
               'Get-MgBetaShareLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaShareLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaShareList', 'Get-MgBetaShareListActivity', 
               'Get-MgBetaShareListColumn', 'Get-MgBetaShareListColumnCount', 
               'Get-MgBetaShareListColumnSourceColumn', 
               'Get-MgBetaShareListContentType', 
               'Get-MgBetaShareListContentTypeColumn', 
               'Get-MgBetaShareListContentTypeColumnCount', 
               'Get-MgBetaShareListContentTypeColumnLink', 
               'Get-MgBetaShareListContentTypeColumnLinkCount', 
               'Get-MgBetaShareListContentTypeColumnPosition', 
               'Get-MgBetaShareListContentTypeColumnPositionCount', 
               'Get-MgBetaShareListContentTypeColumnSourceColumn', 
               'Get-MgBetaShareListContentTypeCompatibleHubContentType', 
               'Get-MgBetaShareListContentTypeCount', 
               'Get-MgBetaShareListCreatedByUser', 
               'Get-MgBetaShareListCreatedByUserMailboxSetting', 
               'Get-MgBetaShareListCreatedByUserServiceProvisioningError', 
               'Get-MgBetaShareListCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaShareListDrive', 'Get-MgBetaShareListItem', 
               'Get-MgBetaShareListItemActivity', 
               'Get-MgBetaShareListItemActivityByInterval', 
               'Get-MgBetaShareListItemAnalytic', 
               'Get-MgBetaShareListItemCreatedByUser', 
               'Get-MgBetaShareListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaShareListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaShareListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaShareListItemDelta', 
               'Get-MgBetaShareListItemDocumentSetVersion', 
               'Get-MgBetaShareListItemDocumentSetVersionCount', 
               'Get-MgBetaShareListItemDocumentSetVersionField', 
               'Get-MgBetaShareListItemDriveItem', 
               'Get-MgBetaShareListItemDriveItemContent', 
               'Get-MgBetaShareListItemField', 'Get-MgBetaShareListItemVersion', 
               'Get-MgBetaShareListItemVersionCount', 
               'Get-MgBetaShareListItemVersionField', 
               'Get-MgBetaShareListOperation', 'Get-MgBetaShareListOperationCount', 
               'Get-MgBetaShareListSubscription', 
               'Get-MgBetaShareListSubscriptionCount', 'Get-MgBetaSharePermission', 
               'Get-MgBetaShareRoot', 'Get-MgBetaShareRootContent', 
               'Get-MgBetaShareSharedDriveItemSharedDriveItem', 
               'Get-MgBetaShareSite', 'Get-MgBetaUserDefaultDrive', 
               'Get-MgBetaUserDrive', 'Get-MgBetaUserDriveActivity', 
               'Get-MgBetaUserDriveBundle', 'Get-MgBetaUserDriveBundleContent', 
               'Get-MgBetaUserDriveBundleCount', 
               'Get-MgBetaUserDriveContentTypeBase', 
               'Get-MgBetaUserDriveContentTypeBaseType', 
               'Get-MgBetaUserDriveContentTypeBaseTypeCount', 
               'Get-MgBetaUserDriveCount', 'Get-MgBetaUserDriveCreatedByUser', 
               'Get-MgBetaUserDriveCreatedByUserMailboxSetting', 
               'Get-MgBetaUserDriveCreatedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveFollowing', 
               'Get-MgBetaUserDriveFollowingContent', 
               'Get-MgBetaUserDriveFollowingCount', 'Get-MgBetaUserDriveItem', 
               'Get-MgBetaUserDriveItemActivity', 
               'Get-MgBetaUserDriveItemAnalytic', 
               'Get-MgBetaUserDriveItemAnalyticItemActivityStat', 
               'Get-MgBetaUserDriveItemAnalyticItemActivityStatActivity', 
               'Get-MgBetaUserDriveItemAnalyticItemActivityStatCount', 
               'Get-MgBetaUserDriveItemAnalyticLastSevenDay', 
               'Get-MgBetaUserDriveItemAnalyticTime', 
               'Get-MgBetaUserDriveItemChild', 
               'Get-MgBetaUserDriveItemChildContent', 
               'Get-MgBetaUserDriveItemChildCount', 
               'Get-MgBetaUserDriveItemContent', 'Get-MgBetaUserDriveItemCount', 
               'Get-MgBetaUserDriveItemCreatedByUser', 
               'Get-MgBetaUserDriveItemCreatedByUserMailboxSetting', 
               'Get-MgBetaUserDriveItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveItemItemLastModifiedByUser', 
               'Get-MgBetaUserDriveItemItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaUserDriveItemItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveItemItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveItemLastModifiedByUser', 
               'Get-MgBetaUserDriveItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaUserDriveItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveItemListItem', 
               'Get-MgBetaUserDriveItemListItemActivity', 
               'Get-MgBetaUserDriveItemListItemAnalytic', 
               'Get-MgBetaUserDriveItemListItemCreatedByUser', 
               'Get-MgBetaUserDriveItemListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaUserDriveItemListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveItemListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveItemListItemDocumentSetVersion', 
               'Get-MgBetaUserDriveItemListItemDocumentSetVersionCount', 
               'Get-MgBetaUserDriveItemListItemDocumentSetVersionField', 
               'Get-MgBetaUserDriveItemListItemDriveItem', 
               'Get-MgBetaUserDriveItemListItemDriveItemContent', 
               'Get-MgBetaUserDriveItemListItemField', 
               'Get-MgBetaUserDriveItemListItemVersion', 
               'Get-MgBetaUserDriveItemListItemVersionCount', 
               'Get-MgBetaUserDriveItemListItemVersionField', 
               'Get-MgBetaUserDriveItemPermission', 
               'Get-MgBetaUserDriveItemPermissionCount', 
               'Get-MgBetaUserDriveItemRetentionLabel', 
               'Get-MgBetaUserDriveItemSubscription', 
               'Get-MgBetaUserDriveItemSubscriptionCount', 
               'Get-MgBetaUserDriveItemThumbnail', 
               'Get-MgBetaUserDriveItemThumbnailCount', 
               'Get-MgBetaUserDriveItemVersion', 
               'Get-MgBetaUserDriveItemVersionContent', 
               'Get-MgBetaUserDriveItemVersionCount', 
               'Get-MgBetaUserDriveLastModifiedByUser', 
               'Get-MgBetaUserDriveLastModifiedByUserMailboxSetting', 
               'Get-MgBetaUserDriveLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveList', 'Get-MgBetaUserDriveListActivity', 
               'Get-MgBetaUserDriveListColumn', 
               'Get-MgBetaUserDriveListColumnCount', 
               'Get-MgBetaUserDriveListColumnSourceColumn', 
               'Get-MgBetaUserDriveListContentType', 
               'Get-MgBetaUserDriveListContentTypeColumn', 
               'Get-MgBetaUserDriveListContentTypeColumnCount', 
               'Get-MgBetaUserDriveListContentTypeColumnLink', 
               'Get-MgBetaUserDriveListContentTypeColumnLinkCount', 
               'Get-MgBetaUserDriveListContentTypeColumnPosition', 
               'Get-MgBetaUserDriveListContentTypeColumnPositionCount', 
               'Get-MgBetaUserDriveListContentTypeColumnSourceColumn', 
               'Get-MgBetaUserDriveListContentTypeCount', 
               'Get-MgBetaUserDriveListCreatedByUser', 
               'Get-MgBetaUserDriveListCreatedByUserMailboxSetting', 
               'Get-MgBetaUserDriveListCreatedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveListCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveListDrive', 'Get-MgBetaUserDriveListItem', 
               'Get-MgBetaUserDriveListItemActivity', 
               'Get-MgBetaUserDriveListItemAnalytic', 
               'Get-MgBetaUserDriveListItemCreatedByUser', 
               'Get-MgBetaUserDriveListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaUserDriveListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveListItemDocumentSetVersion', 
               'Get-MgBetaUserDriveListItemDocumentSetVersionCount', 
               'Get-MgBetaUserDriveListItemDocumentSetVersionField', 
               'Get-MgBetaUserDriveListItemDriveItem', 
               'Get-MgBetaUserDriveListItemDriveItemContent', 
               'Get-MgBetaUserDriveListItemField', 
               'Get-MgBetaUserDriveListItemVersion', 
               'Get-MgBetaUserDriveListItemVersionCount', 
               'Get-MgBetaUserDriveListItemVersionField', 
               'Get-MgBetaUserDriveListOperation', 
               'Get-MgBetaUserDriveListOperationCount', 
               'Get-MgBetaUserDriveListSubscription', 
               'Get-MgBetaUserDriveListSubscriptionCount', 
               'Get-MgBetaUserDriveRoot', 'Get-MgBetaUserDriveRootActivity', 
               'Get-MgBetaUserDriveRootAnalytic', 
               'Get-MgBetaUserDriveRootAnalyticItemActivityStat', 
               'Get-MgBetaUserDriveRootAnalyticItemActivityStatActivity', 
               'Get-MgBetaUserDriveRootAnalyticItemActivityStatCount', 
               'Get-MgBetaUserDriveRootAnalyticLastSevenDay', 
               'Get-MgBetaUserDriveRootAnalyticTime', 
               'Get-MgBetaUserDriveRootChild', 
               'Get-MgBetaUserDriveRootChildContent', 
               'Get-MgBetaUserDriveRootChildCount', 
               'Get-MgBetaUserDriveRootContent', 
               'Get-MgBetaUserDriveRootCreatedByUser', 
               'Get-MgBetaUserDriveRootCreatedByUserMailboxSetting', 
               'Get-MgBetaUserDriveRootCreatedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveRootCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveRootItemLastModifiedByUser', 
               'Get-MgBetaUserDriveRootItemLastModifiedByUserMailboxSetting', 
               'Get-MgBetaUserDriveRootItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveRootItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveRootLastModifiedByUser', 
               'Get-MgBetaUserDriveRootLastModifiedByUserMailboxSetting', 
               'Get-MgBetaUserDriveRootLastModifiedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveRootLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveRootListItem', 
               'Get-MgBetaUserDriveRootListItemActivity', 
               'Get-MgBetaUserDriveRootListItemAnalytic', 
               'Get-MgBetaUserDriveRootListItemCreatedByUser', 
               'Get-MgBetaUserDriveRootListItemCreatedByUserMailboxSetting', 
               'Get-MgBetaUserDriveRootListItemCreatedByUserServiceProvisioningError', 
               'Get-MgBetaUserDriveRootListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgBetaUserDriveRootListItemDocumentSetVersion', 
               'Get-MgBetaUserDriveRootListItemDocumentSetVersionCount', 
               'Get-MgBetaUserDriveRootListItemDocumentSetVersionField', 
               'Get-MgBetaUserDriveRootListItemDriveItem', 
               'Get-MgBetaUserDriveRootListItemDriveItemContent', 
               'Get-MgBetaUserDriveRootListItemField', 
               'Get-MgBetaUserDriveRootListItemVersion', 
               'Get-MgBetaUserDriveRootListItemVersionCount', 
               'Get-MgBetaUserDriveRootListItemVersionField', 
               'Get-MgBetaUserDriveRootPermission', 
               'Get-MgBetaUserDriveRootPermissionCount', 
               'Get-MgBetaUserDriveRootRetentionLabel', 
               'Get-MgBetaUserDriveRootSubscription', 
               'Get-MgBetaUserDriveRootSubscriptionCount', 
               'Get-MgBetaUserDriveRootThumbnail', 
               'Get-MgBetaUserDriveRootThumbnailCount', 
               'Get-MgBetaUserDriveRootVersion', 
               'Get-MgBetaUserDriveRootVersionContent', 
               'Get-MgBetaUserDriveRootVersionCount', 'Get-MgBetaUserDriveSpecial', 
               'Get-MgBetaUserDriveSpecialContent', 
               'Get-MgBetaUserDriveSpecialCount', 
               'Grant-MgBetaDriveItemPermission', 
               'Grant-MgBetaDriveRootPermission', 'Grant-MgBetaSharePermission', 
               'Invoke-MgBetaCheckinDriveItem', 'Invoke-MgBetaCheckinDriveRoot', 
               'Invoke-MgBetaCheckoutDriveItem', 'Invoke-MgBetaCheckoutDriveRoot', 
               'Invoke-MgBetaExtractDriveItemSensitivityLabel', 
               'Invoke-MgBetaExtractDriveRootSensitivityLabel', 
               'Invoke-MgBetaFollowDriveItem', 'Invoke-MgBetaFollowDriveRoot', 
               'Invoke-MgBetaGraphDrive', 'Invoke-MgBetaInviteDriveItem', 
               'Invoke-MgBetaInviteDriveRoot', 'Invoke-MgBetaPreviewDriveItem', 
               'Invoke-MgBetaPreviewDriveRoot', 
               'Invoke-MgBetaReauthorizeDriveItemSubscription', 
               'Invoke-MgBetaReauthorizeDriveListSubscription', 
               'Invoke-MgBetaReauthorizeDriveRootSubscription', 
               'Invoke-MgBetaReauthorizeShareListSubscription', 
               'Invoke-MgBetaRecentDrive', 'Invoke-MgBetaUnfollowDriveItem', 
               'Invoke-MgBetaUnfollowDriveRoot', 
               'Join-MgBetaDriveListContentTypeWithHubSite', 
               'Join-MgBetaShareListContentTypeWithHubSite', 'New-MgBetaDrive', 
               'New-MgBetaDriveBundle', 'New-MgBetaDriveItem', 
               'New-MgBetaDriveItemAnalyticItemActivityStat', 
               'New-MgBetaDriveItemChild', 'New-MgBetaDriveItemLink', 
               'New-MgBetaDriveItemListItemDocumentSetVersion', 
               'New-MgBetaDriveItemListItemLink', 
               'New-MgBetaDriveItemListItemVersion', 
               'New-MgBetaDriveItemPermission', 'New-MgBetaDriveItemSubscription', 
               'New-MgBetaDriveItemThumbnail', 'New-MgBetaDriveItemUploadSession', 
               'New-MgBetaDriveItemVersion', 'New-MgBetaDriveListColumn', 
               'New-MgBetaDriveListContentType', 
               'New-MgBetaDriveListContentTypeColumn', 
               'New-MgBetaDriveListContentTypeColumnLink', 
               'New-MgBetaDriveListItem', 
               'New-MgBetaDriveListItemDocumentSetVersion', 
               'New-MgBetaDriveListItemLink', 'New-MgBetaDriveListItemVersion', 
               'New-MgBetaDriveListOperation', 'New-MgBetaDriveListSubscription', 
               'New-MgBetaDriveRootAnalyticItemActivityStat', 
               'New-MgBetaDriveRootChild', 'New-MgBetaDriveRootLink', 
               'New-MgBetaDriveRootListItemDocumentSetVersion', 
               'New-MgBetaDriveRootListItemLink', 
               'New-MgBetaDriveRootListItemVersion', 
               'New-MgBetaDriveRootPermission', 'New-MgBetaDriveRootSubscription', 
               'New-MgBetaDriveRootThumbnail', 'New-MgBetaDriveRootUploadSession', 
               'New-MgBetaDriveRootVersion', 'New-MgBetaGroupDrive', 
               'New-MgBetaGroupDriveBundle', 'New-MgBetaGroupDriveItem', 
               'New-MgBetaGroupDriveItemAnalyticItemActivityStat', 
               'New-MgBetaGroupDriveItemChild', 
               'New-MgBetaGroupDriveItemListItemDocumentSetVersion', 
               'New-MgBetaGroupDriveItemListItemVersion', 
               'New-MgBetaGroupDriveItemPermission', 
               'New-MgBetaGroupDriveItemSubscription', 
               'New-MgBetaGroupDriveItemThumbnail', 
               'New-MgBetaGroupDriveItemVersion', 'New-MgBetaGroupDriveListColumn', 
               'New-MgBetaGroupDriveListContentType', 
               'New-MgBetaGroupDriveListContentTypeColumn', 
               'New-MgBetaGroupDriveListContentTypeColumnLink', 
               'New-MgBetaGroupDriveListItem', 
               'New-MgBetaGroupDriveListItemDocumentSetVersion', 
               'New-MgBetaGroupDriveListItemVersion', 
               'New-MgBetaGroupDriveListOperation', 
               'New-MgBetaGroupDriveListSubscription', 
               'New-MgBetaGroupDriveRootAnalyticItemActivityStat', 
               'New-MgBetaGroupDriveRootChild', 
               'New-MgBetaGroupDriveRootListItemDocumentSetVersion', 
               'New-MgBetaGroupDriveRootListItemVersion', 
               'New-MgBetaGroupDriveRootPermission', 
               'New-MgBetaGroupDriveRootSubscription', 
               'New-MgBetaGroupDriveRootThumbnail', 
               'New-MgBetaGroupDriveRootVersion', 'New-MgBetaShareListColumn', 
               'New-MgBetaShareListContentType', 
               'New-MgBetaShareListContentTypeColumn', 
               'New-MgBetaShareListContentTypeColumnLink', 
               'New-MgBetaShareListItem', 
               'New-MgBetaShareListItemDocumentSetVersion', 
               'New-MgBetaShareListItemVersion', 'New-MgBetaShareListOperation', 
               'New-MgBetaShareListSubscription', 
               'New-MgBetaShareSharedDriveItemSharedDriveItem', 
               'New-MgBetaUserDrive', 'New-MgBetaUserDriveBundle', 
               'New-MgBetaUserDriveItem', 
               'New-MgBetaUserDriveItemAnalyticItemActivityStat', 
               'New-MgBetaUserDriveItemChild', 
               'New-MgBetaUserDriveItemListItemDocumentSetVersion', 
               'New-MgBetaUserDriveItemListItemVersion', 
               'New-MgBetaUserDriveItemPermission', 
               'New-MgBetaUserDriveItemSubscription', 
               'New-MgBetaUserDriveItemThumbnail', 
               'New-MgBetaUserDriveItemVersion', 'New-MgBetaUserDriveListColumn', 
               'New-MgBetaUserDriveListContentType', 
               'New-MgBetaUserDriveListContentTypeColumn', 
               'New-MgBetaUserDriveListContentTypeColumnLink', 
               'New-MgBetaUserDriveListItem', 
               'New-MgBetaUserDriveListItemDocumentSetVersion', 
               'New-MgBetaUserDriveListItemVersion', 
               'New-MgBetaUserDriveListOperation', 
               'New-MgBetaUserDriveListSubscription', 
               'New-MgBetaUserDriveRootAnalyticItemActivityStat', 
               'New-MgBetaUserDriveRootChild', 
               'New-MgBetaUserDriveRootListItemDocumentSetVersion', 
               'New-MgBetaUserDriveRootListItemVersion', 
               'New-MgBetaUserDriveRootPermission', 
               'New-MgBetaUserDriveRootSubscription', 
               'New-MgBetaUserDriveRootThumbnail', 
               'New-MgBetaUserDriveRootVersion', 
               'Publish-MgBetaDriveListContentType', 
               'Publish-MgBetaShareListContentType', 'Remove-MgBetaDrive', 
               'Remove-MgBetaDriveItem', 'Remove-MgBetaDriveItemAnalytic', 
               'Remove-MgBetaDriveItemAnalyticItemActivityStat', 
               'Remove-MgBetaDriveItemListItem', 
               'Remove-MgBetaDriveItemListItemDocumentSetVersion', 
               'Remove-MgBetaDriveItemListItemDocumentSetVersionField', 
               'Remove-MgBetaDriveItemListItemField', 
               'Remove-MgBetaDriveItemListItemVersion', 
               'Remove-MgBetaDriveItemListItemVersionField', 
               'Remove-MgBetaDriveItemPermanent', 
               'Remove-MgBetaDriveItemPermission', 
               'Remove-MgBetaDriveItemRetentionLabel', 
               'Remove-MgBetaDriveItemSubscription', 
               'Remove-MgBetaDriveItemThumbnail', 'Remove-MgBetaDriveItemVersion', 
               'Remove-MgBetaDriveList', 'Remove-MgBetaDriveListColumn', 
               'Remove-MgBetaDriveListContentType', 
               'Remove-MgBetaDriveListContentTypeColumn', 
               'Remove-MgBetaDriveListContentTypeColumnLink', 
               'Remove-MgBetaDriveListItem', 
               'Remove-MgBetaDriveListItemDocumentSetVersion', 
               'Remove-MgBetaDriveListItemDocumentSetVersionField', 
               'Remove-MgBetaDriveListItemField', 
               'Remove-MgBetaDriveListItemVersion', 
               'Remove-MgBetaDriveListItemVersionField', 
               'Remove-MgBetaDriveListOperation', 
               'Remove-MgBetaDriveListSubscription', 'Remove-MgBetaDriveRoot', 
               'Remove-MgBetaDriveRootAnalytic', 
               'Remove-MgBetaDriveRootAnalyticItemActivityStat', 
               'Remove-MgBetaDriveRootListItem', 
               'Remove-MgBetaDriveRootListItemDocumentSetVersion', 
               'Remove-MgBetaDriveRootListItemDocumentSetVersionField', 
               'Remove-MgBetaDriveRootListItemField', 
               'Remove-MgBetaDriveRootListItemVersion', 
               'Remove-MgBetaDriveRootListItemVersionField', 
               'Remove-MgBetaDriveRootPermanent', 
               'Remove-MgBetaDriveRootPermission', 
               'Remove-MgBetaDriveRootRetentionLabel', 
               'Remove-MgBetaDriveRootSubscription', 
               'Remove-MgBetaDriveRootThumbnail', 'Remove-MgBetaDriveRootVersion', 
               'Remove-MgBetaGroupDrive', 'Remove-MgBetaGroupDriveItem', 
               'Remove-MgBetaGroupDriveItemAnalytic', 
               'Remove-MgBetaGroupDriveItemAnalyticItemActivityStat', 
               'Remove-MgBetaGroupDriveItemListItem', 
               'Remove-MgBetaGroupDriveItemListItemDocumentSetVersion', 
               'Remove-MgBetaGroupDriveItemListItemDocumentSetVersionField', 
               'Remove-MgBetaGroupDriveItemListItemField', 
               'Remove-MgBetaGroupDriveItemListItemVersion', 
               'Remove-MgBetaGroupDriveItemListItemVersionField', 
               'Remove-MgBetaGroupDriveItemPermission', 
               'Remove-MgBetaGroupDriveItemRetentionLabel', 
               'Remove-MgBetaGroupDriveItemSubscription', 
               'Remove-MgBetaGroupDriveItemThumbnail', 
               'Remove-MgBetaGroupDriveItemVersion', 'Remove-MgBetaGroupDriveList', 
               'Remove-MgBetaGroupDriveListColumn', 
               'Remove-MgBetaGroupDriveListContentType', 
               'Remove-MgBetaGroupDriveListContentTypeColumn', 
               'Remove-MgBetaGroupDriveListContentTypeColumnLink', 
               'Remove-MgBetaGroupDriveListItem', 
               'Remove-MgBetaGroupDriveListItemDocumentSetVersion', 
               'Remove-MgBetaGroupDriveListItemDocumentSetVersionField', 
               'Remove-MgBetaGroupDriveListItemField', 
               'Remove-MgBetaGroupDriveListItemVersion', 
               'Remove-MgBetaGroupDriveListItemVersionField', 
               'Remove-MgBetaGroupDriveListOperation', 
               'Remove-MgBetaGroupDriveListSubscription', 
               'Remove-MgBetaGroupDriveRoot', 
               'Remove-MgBetaGroupDriveRootAnalytic', 
               'Remove-MgBetaGroupDriveRootAnalyticItemActivityStat', 
               'Remove-MgBetaGroupDriveRootListItem', 
               'Remove-MgBetaGroupDriveRootListItemDocumentSetVersion', 
               'Remove-MgBetaGroupDriveRootListItemDocumentSetVersionField', 
               'Remove-MgBetaGroupDriveRootListItemField', 
               'Remove-MgBetaGroupDriveRootListItemVersion', 
               'Remove-MgBetaGroupDriveRootListItemVersionField', 
               'Remove-MgBetaGroupDriveRootPermission', 
               'Remove-MgBetaGroupDriveRootRetentionLabel', 
               'Remove-MgBetaGroupDriveRootSubscription', 
               'Remove-MgBetaGroupDriveRootThumbnail', 
               'Remove-MgBetaGroupDriveRootVersion', 'Remove-MgBetaShareList', 
               'Remove-MgBetaShareListColumn', 'Remove-MgBetaShareListContentType', 
               'Remove-MgBetaShareListContentTypeColumn', 
               'Remove-MgBetaShareListContentTypeColumnLink', 
               'Remove-MgBetaShareListItem', 
               'Remove-MgBetaShareListItemDocumentSetVersion', 
               'Remove-MgBetaShareListItemDocumentSetVersionField', 
               'Remove-MgBetaShareListItemField', 
               'Remove-MgBetaShareListItemVersion', 
               'Remove-MgBetaShareListItemVersionField', 
               'Remove-MgBetaShareListOperation', 
               'Remove-MgBetaShareListSubscription', 
               'Remove-MgBetaSharePermission', 
               'Remove-MgBetaShareSharedDriveItemSharedDriveItem', 
               'Remove-MgBetaUserDrive', 'Remove-MgBetaUserDriveItem', 
               'Remove-MgBetaUserDriveItemAnalytic', 
               'Remove-MgBetaUserDriveItemAnalyticItemActivityStat', 
               'Remove-MgBetaUserDriveItemListItem', 
               'Remove-MgBetaUserDriveItemListItemDocumentSetVersion', 
               'Remove-MgBetaUserDriveItemListItemDocumentSetVersionField', 
               'Remove-MgBetaUserDriveItemListItemField', 
               'Remove-MgBetaUserDriveItemListItemVersion', 
               'Remove-MgBetaUserDriveItemListItemVersionField', 
               'Remove-MgBetaUserDriveItemPermission', 
               'Remove-MgBetaUserDriveItemRetentionLabel', 
               'Remove-MgBetaUserDriveItemSubscription', 
               'Remove-MgBetaUserDriveItemThumbnail', 
               'Remove-MgBetaUserDriveItemVersion', 'Remove-MgBetaUserDriveList', 
               'Remove-MgBetaUserDriveListColumn', 
               'Remove-MgBetaUserDriveListContentType', 
               'Remove-MgBetaUserDriveListContentTypeColumn', 
               'Remove-MgBetaUserDriveListContentTypeColumnLink', 
               'Remove-MgBetaUserDriveListItem', 
               'Remove-MgBetaUserDriveListItemDocumentSetVersion', 
               'Remove-MgBetaUserDriveListItemDocumentSetVersionField', 
               'Remove-MgBetaUserDriveListItemField', 
               'Remove-MgBetaUserDriveListItemVersion', 
               'Remove-MgBetaUserDriveListItemVersionField', 
               'Remove-MgBetaUserDriveListOperation', 
               'Remove-MgBetaUserDriveListSubscription', 
               'Remove-MgBetaUserDriveRoot', 'Remove-MgBetaUserDriveRootAnalytic', 
               'Remove-MgBetaUserDriveRootAnalyticItemActivityStat', 
               'Remove-MgBetaUserDriveRootListItem', 
               'Remove-MgBetaUserDriveRootListItemDocumentSetVersion', 
               'Remove-MgBetaUserDriveRootListItemDocumentSetVersionField', 
               'Remove-MgBetaUserDriveRootListItemField', 
               'Remove-MgBetaUserDriveRootListItemVersion', 
               'Remove-MgBetaUserDriveRootListItemVersionField', 
               'Remove-MgBetaUserDriveRootPermission', 
               'Remove-MgBetaUserDriveRootRetentionLabel', 
               'Remove-MgBetaUserDriveRootSubscription', 
               'Remove-MgBetaUserDriveRootThumbnail', 
               'Remove-MgBetaUserDriveRootVersion', 'Restore-MgBetaDriveItem', 
               'Restore-MgBetaDriveItemListItemDocumentSetVersion', 
               'Restore-MgBetaDriveItemListItemVersion', 
               'Restore-MgBetaDriveItemVersion', 
               'Restore-MgBetaDriveListItemDocumentSetVersion', 
               'Restore-MgBetaDriveListItemVersion', 'Restore-MgBetaDriveRoot', 
               'Restore-MgBetaDriveRootListItemDocumentSetVersion', 
               'Restore-MgBetaDriveRootListItemVersion', 
               'Restore-MgBetaDriveRootVersion', 
               'Restore-MgBetaShareListItemDocumentSetVersion', 
               'Restore-MgBetaShareListItemVersion', 
               'Revoke-MgBetaDriveItemPermissionGrant', 
               'Revoke-MgBetaDriveRootPermissionGrant', 
               'Revoke-MgBetaSharePermissionGrant', 'Search-MgBetaDrive', 
               'Search-MgBetaDriveItem', 'Search-MgBetaDriveRoot', 
               'Set-MgBetaDriveBundleContent', 'Set-MgBetaDriveFollowingContent', 
               'Set-MgBetaDriveItemChildContent', 'Set-MgBetaDriveItemContent', 
               'Set-MgBetaDriveItemListItemDriveItemContent', 
               'Set-MgBetaDriveItemSensitivityLabel', 
               'Set-MgBetaDriveItemVersionContent', 
               'Set-MgBetaDriveListItemDriveItemContent', 
               'Set-MgBetaDriveRootChildContent', 'Set-MgBetaDriveRootContent', 
               'Set-MgBetaDriveRootListItemDriveItemContent', 
               'Set-MgBetaDriveRootSensitivityLabel', 
               'Set-MgBetaDriveRootVersionContent', 
               'Set-MgBetaDriveSpecialContent', 
               'Set-MgBetaGroupDriveBundleContent', 
               'Set-MgBetaGroupDriveFollowingContent', 
               'Set-MgBetaGroupDriveItemChildContent', 
               'Set-MgBetaGroupDriveItemContent', 
               'Set-MgBetaGroupDriveItemListItemDriveItemContent', 
               'Set-MgBetaGroupDriveItemVersionContent', 
               'Set-MgBetaGroupDriveListItemDriveItemContent', 
               'Set-MgBetaGroupDriveRootChildContent', 
               'Set-MgBetaGroupDriveRootContent', 
               'Set-MgBetaGroupDriveRootListItemDriveItemContent', 
               'Set-MgBetaGroupDriveRootVersionContent', 
               'Set-MgBetaGroupDriveSpecialContent', 
               'Set-MgBetaShareDriveItemContent', 'Set-MgBetaShareItemContent', 
               'Set-MgBetaShareListItemDriveItemContent', 
               'Set-MgBetaShareRootContent', 'Set-MgBetaUserDriveBundleContent', 
               'Set-MgBetaUserDriveFollowingContent', 
               'Set-MgBetaUserDriveItemChildContent', 
               'Set-MgBetaUserDriveItemContent', 
               'Set-MgBetaUserDriveItemListItemDriveItemContent', 
               'Set-MgBetaUserDriveItemVersionContent', 
               'Set-MgBetaUserDriveListItemDriveItemContent', 
               'Set-MgBetaUserDriveRootChildContent', 
               'Set-MgBetaUserDriveRootContent', 
               'Set-MgBetaUserDriveRootListItemDriveItemContent', 
               'Set-MgBetaUserDriveRootVersionContent', 
               'Set-MgBetaUserDriveSpecialContent', 
               'Test-MgBetaDriveItemPermission', 
               'Test-MgBetaDriveListContentTypePublished', 
               'Test-MgBetaDriveRootPermission', 
               'Test-MgBetaShareListContentTypePublished', 
               'Unpublish-MgBetaDriveListContentType', 
               'Unpublish-MgBetaShareListContentType', 'Update-MgBetaDrive', 
               'Update-MgBetaDriveCreatedByUserMailboxSetting', 
               'Update-MgBetaDriveItem', 'Update-MgBetaDriveItemAnalytic', 
               'Update-MgBetaDriveItemAnalyticItemActivityStat', 
               'Update-MgBetaDriveItemCreatedByUserMailboxSetting', 
               'Update-MgBetaDriveItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaDriveItemListItem', 
               'Update-MgBetaDriveItemListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaDriveItemListItemDocumentSetVersion', 
               'Update-MgBetaDriveItemListItemDocumentSetVersionField', 
               'Update-MgBetaDriveItemListItemField', 
               'Update-MgBetaDriveItemListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaDriveItemListItemVersion', 
               'Update-MgBetaDriveItemListItemVersionField', 
               'Update-MgBetaDriveItemPermission', 
               'Update-MgBetaDriveItemRetentionLabel', 
               'Update-MgBetaDriveItemSubscription', 
               'Update-MgBetaDriveItemThumbnail', 'Update-MgBetaDriveItemVersion', 
               'Update-MgBetaDriveLastModifiedByUserMailboxSetting', 
               'Update-MgBetaDriveList', 'Update-MgBetaDriveListColumn', 
               'Update-MgBetaDriveListContentType', 
               'Update-MgBetaDriveListContentTypeColumn', 
               'Update-MgBetaDriveListContentTypeColumnLink', 
               'Update-MgBetaDriveListCreatedByUserMailboxSetting', 
               'Update-MgBetaDriveListItem', 
               'Update-MgBetaDriveListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaDriveListItemDocumentSetVersion', 
               'Update-MgBetaDriveListItemDocumentSetVersionField', 
               'Update-MgBetaDriveListItemField', 
               'Update-MgBetaDriveListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaDriveListItemVersion', 
               'Update-MgBetaDriveListItemVersionField', 
               'Update-MgBetaDriveListLastModifiedByUserMailboxSetting', 
               'Update-MgBetaDriveListOperation', 
               'Update-MgBetaDriveListSubscription', 'Update-MgBetaDriveRoot', 
               'Update-MgBetaDriveRootAnalytic', 
               'Update-MgBetaDriveRootAnalyticItemActivityStat', 
               'Update-MgBetaDriveRootCreatedByUserMailboxSetting', 
               'Update-MgBetaDriveRootLastModifiedByUserMailboxSetting', 
               'Update-MgBetaDriveRootListItem', 
               'Update-MgBetaDriveRootListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaDriveRootListItemDocumentSetVersion', 
               'Update-MgBetaDriveRootListItemDocumentSetVersionField', 
               'Update-MgBetaDriveRootListItemField', 
               'Update-MgBetaDriveRootListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaDriveRootListItemVersion', 
               'Update-MgBetaDriveRootListItemVersionField', 
               'Update-MgBetaDriveRootPermission', 
               'Update-MgBetaDriveRootRetentionLabel', 
               'Update-MgBetaDriveRootSubscription', 
               'Update-MgBetaDriveRootThumbnail', 'Update-MgBetaDriveRootVersion', 
               'Update-MgBetaGroupDrive', 
               'Update-MgBetaGroupDriveCreatedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveItem', 
               'Update-MgBetaGroupDriveItemAnalytic', 
               'Update-MgBetaGroupDriveItemAnalyticItemActivityStat', 
               'Update-MgBetaGroupDriveItemCreatedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveItemListItem', 
               'Update-MgBetaGroupDriveItemListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveItemListItemDocumentSetVersion', 
               'Update-MgBetaGroupDriveItemListItemDocumentSetVersionField', 
               'Update-MgBetaGroupDriveItemListItemField', 
               'Update-MgBetaGroupDriveItemListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveItemListItemVersion', 
               'Update-MgBetaGroupDriveItemListItemVersionField', 
               'Update-MgBetaGroupDriveItemPermission', 
               'Update-MgBetaGroupDriveItemRetentionLabel', 
               'Update-MgBetaGroupDriveItemSubscription', 
               'Update-MgBetaGroupDriveItemThumbnail', 
               'Update-MgBetaGroupDriveItemVersion', 
               'Update-MgBetaGroupDriveLastModifiedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveList', 'Update-MgBetaGroupDriveListColumn', 
               'Update-MgBetaGroupDriveListContentType', 
               'Update-MgBetaGroupDriveListContentTypeColumn', 
               'Update-MgBetaGroupDriveListContentTypeColumnLink', 
               'Update-MgBetaGroupDriveListCreatedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveListItem', 
               'Update-MgBetaGroupDriveListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveListItemDocumentSetVersion', 
               'Update-MgBetaGroupDriveListItemDocumentSetVersionField', 
               'Update-MgBetaGroupDriveListItemField', 
               'Update-MgBetaGroupDriveListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveListItemVersion', 
               'Update-MgBetaGroupDriveListItemVersionField', 
               'Update-MgBetaGroupDriveListLastModifiedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveListOperation', 
               'Update-MgBetaGroupDriveListSubscription', 
               'Update-MgBetaGroupDriveRoot', 
               'Update-MgBetaGroupDriveRootAnalytic', 
               'Update-MgBetaGroupDriveRootAnalyticItemActivityStat', 
               'Update-MgBetaGroupDriveRootCreatedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveRootLastModifiedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveRootListItem', 
               'Update-MgBetaGroupDriveRootListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveRootListItemDocumentSetVersion', 
               'Update-MgBetaGroupDriveRootListItemDocumentSetVersionField', 
               'Update-MgBetaGroupDriveRootListItemField', 
               'Update-MgBetaGroupDriveRootListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaGroupDriveRootListItemVersion', 
               'Update-MgBetaGroupDriveRootListItemVersionField', 
               'Update-MgBetaGroupDriveRootPermission', 
               'Update-MgBetaGroupDriveRootRetentionLabel', 
               'Update-MgBetaGroupDriveRootSubscription', 
               'Update-MgBetaGroupDriveRootThumbnail', 
               'Update-MgBetaGroupDriveRootVersion', 
               'Update-MgBetaShareCreatedByUserMailboxSetting', 
               'Update-MgBetaShareLastModifiedByUserMailboxSetting', 
               'Update-MgBetaShareList', 'Update-MgBetaShareListColumn', 
               'Update-MgBetaShareListContentType', 
               'Update-MgBetaShareListContentTypeColumn', 
               'Update-MgBetaShareListContentTypeColumnLink', 
               'Update-MgBetaShareListCreatedByUserMailboxSetting', 
               'Update-MgBetaShareListItem', 
               'Update-MgBetaShareListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaShareListItemDocumentSetVersion', 
               'Update-MgBetaShareListItemDocumentSetVersionField', 
               'Update-MgBetaShareListItemField', 
               'Update-MgBetaShareListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaShareListItemVersion', 
               'Update-MgBetaShareListItemVersionField', 
               'Update-MgBetaShareListLastModifiedByUserMailboxSetting', 
               'Update-MgBetaShareListOperation', 
               'Update-MgBetaShareListSubscription', 
               'Update-MgBetaSharePermission', 
               'Update-MgBetaShareSharedDriveItemSharedDriveItem', 
               'Update-MgBetaUserDrive', 
               'Update-MgBetaUserDriveCreatedByUserMailboxSetting', 
               'Update-MgBetaUserDriveItem', 'Update-MgBetaUserDriveItemAnalytic', 
               'Update-MgBetaUserDriveItemAnalyticItemActivityStat', 
               'Update-MgBetaUserDriveItemCreatedByUserMailboxSetting', 
               'Update-MgBetaUserDriveItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaUserDriveItemListItem', 
               'Update-MgBetaUserDriveItemListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaUserDriveItemListItemDocumentSetVersion', 
               'Update-MgBetaUserDriveItemListItemDocumentSetVersionField', 
               'Update-MgBetaUserDriveItemListItemField', 
               'Update-MgBetaUserDriveItemListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaUserDriveItemListItemVersion', 
               'Update-MgBetaUserDriveItemListItemVersionField', 
               'Update-MgBetaUserDriveItemPermission', 
               'Update-MgBetaUserDriveItemRetentionLabel', 
               'Update-MgBetaUserDriveItemSubscription', 
               'Update-MgBetaUserDriveItemThumbnail', 
               'Update-MgBetaUserDriveItemVersion', 
               'Update-MgBetaUserDriveLastModifiedByUserMailboxSetting', 
               'Update-MgBetaUserDriveList', 'Update-MgBetaUserDriveListColumn', 
               'Update-MgBetaUserDriveListContentType', 
               'Update-MgBetaUserDriveListContentTypeColumn', 
               'Update-MgBetaUserDriveListContentTypeColumnLink', 
               'Update-MgBetaUserDriveListCreatedByUserMailboxSetting', 
               'Update-MgBetaUserDriveListItem', 
               'Update-MgBetaUserDriveListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaUserDriveListItemDocumentSetVersion', 
               'Update-MgBetaUserDriveListItemDocumentSetVersionField', 
               'Update-MgBetaUserDriveListItemField', 
               'Update-MgBetaUserDriveListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaUserDriveListItemVersion', 
               'Update-MgBetaUserDriveListItemVersionField', 
               'Update-MgBetaUserDriveListLastModifiedByUserMailboxSetting', 
               'Update-MgBetaUserDriveListOperation', 
               'Update-MgBetaUserDriveListSubscription', 
               'Update-MgBetaUserDriveRoot', 'Update-MgBetaUserDriveRootAnalytic', 
               'Update-MgBetaUserDriveRootAnalyticItemActivityStat', 
               'Update-MgBetaUserDriveRootCreatedByUserMailboxSetting', 
               'Update-MgBetaUserDriveRootLastModifiedByUserMailboxSetting', 
               'Update-MgBetaUserDriveRootListItem', 
               'Update-MgBetaUserDriveRootListItemCreatedByUserMailboxSetting', 
               'Update-MgBetaUserDriveRootListItemDocumentSetVersion', 
               'Update-MgBetaUserDriveRootListItemDocumentSetVersionField', 
               'Update-MgBetaUserDriveRootListItemField', 
               'Update-MgBetaUserDriveRootListItemLastModifiedByUserMailboxSetting', 
               'Update-MgBetaUserDriveRootListItemVersion', 
               'Update-MgBetaUserDriveRootListItemVersionField', 
               'Update-MgBetaUserDriveRootPermission', 
               'Update-MgBetaUserDriveRootRetentionLabel', 
               'Update-MgBetaUserDriveRootSubscription', 
               'Update-MgBetaUserDriveRootThumbnail', 
               'Update-MgBetaUserDriveRootVersion'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInzQYJKoZIhvcNAQcCoIInvjCCJ7oCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBLVdp1IXLZGwZR
# dYqANnkSeSKuoqFDAUANaCOjQOubnqCCDYUwggYDMIID66ADAgECAhMzAAADri01
# UchTj1UdAAAAAAOuMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMxMTE2MTkwODU5WhcNMjQxMTE0MTkwODU5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQD0IPymNjfDEKg+YyE6SjDvJwKW1+pieqTjAY0CnOHZ1Nj5irGjNZPMlQ4HfxXG
# yAVCZcEWE4x2sZgam872R1s0+TAelOtbqFmoW4suJHAYoTHhkznNVKpscm5fZ899
# QnReZv5WtWwbD8HAFXbPPStW2JKCqPcZ54Y6wbuWV9bKtKPImqbkMcTejTgEAj82
# 6GQc6/Th66Koka8cUIvz59e/IP04DGrh9wkq2jIFvQ8EDegw1B4KyJTIs76+hmpV
# M5SwBZjRs3liOQrierkNVo11WuujB3kBf2CbPoP9MlOyyezqkMIbTRj4OHeKlamd
# WaSFhwHLJRIQpfc8sLwOSIBBAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUhx/vdKmXhwc4WiWXbsf0I53h8T8w
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMTgzNjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AGrJYDUS7s8o0yNprGXRXuAnRcHKxSjFmW4wclcUTYsQZkhnbMwthWM6cAYb/h2W
# 5GNKtlmj/y/CThe3y/o0EH2h+jwfU/9eJ0fK1ZO/2WD0xi777qU+a7l8KjMPdwjY
# 0tk9bYEGEZfYPRHy1AGPQVuZlG4i5ymJDsMrcIcqV8pxzsw/yk/O4y/nlOjHz4oV
# APU0br5t9tgD8E08GSDi3I6H57Ftod9w26h0MlQiOr10Xqhr5iPLS7SlQwj8HW37
# ybqsmjQpKhmWul6xiXSNGGm36GarHy4Q1egYlxhlUnk3ZKSr3QtWIo1GGL03hT57
# xzjL25fKiZQX/q+II8nuG5M0Qmjvl6Egltr4hZ3e3FQRzRHfLoNPq3ELpxbWdH8t
# Nuj0j/x9Crnfwbki8n57mJKI5JVWRWTSLmbTcDDLkTZlJLg9V1BIJwXGY3i2kR9i
# 5HsADL8YlW0gMWVSlKB1eiSlK6LmFi0rVH16dde+j5T/EaQtFz6qngN7d1lvO7uk
# 6rtX+MLKG4LDRsQgBTi6sIYiKntMjoYFHMPvI/OMUip5ljtLitVbkFGfagSqmbxK
# 7rJMhC8wiTzHanBg1Rrbff1niBbnFbbV4UDmYumjs1FIpFCazk6AADXxoKCo5TsO
# zSHqr9gHgGYQC2hMyX9MGLIpowYCURx3L7kUiGbOiMwaMIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGZ4wghmaAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAOuLTVRyFOPVR0AAAAA
# A64wDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIMuj
# 5hD5IoFZlS55h9POKX5GZajFxRq7ris+zxUvqey6MEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAtbL7G40u+Jrp/iEmwKCyzpi/9nfswpcQl5tA
# 8lsbj9CYF4tTdd/jePDulItN5cKrTIar02eXDm0OjJi/seWl96PxM224rL9G/i6j
# 9068EcOdZvpLpgEmMg6aFmBCaicNN6bNCmUdHos5WvJuQp8miY68/QGAWeQLG/36
# eIx5xmCrljrU+XnH4jK8usgXi3gD3dXPG0rgZV6mxTA1x2sxc7lvrl/ykV+4Ayhg
# dqu73QQ8H00CHyrGgqOJWhLJIm5ssgkkwKx/4jSIalfaF8yhHHB/vGWStCope91K
# BA002OZ97nLsIL/wUsiIbRJjzMNj09g8BYeRIwdNIr3SclGD5qGCFygwghckBgor
# BgEEAYI3AwMBMYIXFDCCFxAGCSqGSIb3DQEHAqCCFwEwghb9AgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFYBgsqhkiG9w0BCRABBKCCAUcEggFDMIIBPwIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCCa9rCu33t0HVccJc358HIDJOoALyqzWmak
# u6JZi2JQFAIGZdXv+ubYGBIyMDI0MDMwNzE4NTA1MC40NVowBIACAfSggdikgdUw
# gdIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsT
# JE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEmMCQGA1UECxMd
# VGhhbGVzIFRTUyBFU046OEQ0MS00QkY3LUIzQjcxJTAjBgNVBAMTHE1pY3Jvc29m
# dCBUaW1lLVN0YW1wIFNlcnZpY2WgghF4MIIHJzCCBQ+gAwIBAgITMwAAAePfvZua
# HGiDIgABAAAB4zANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQ
# Q0EgMjAxMDAeFw0yMzEwMTIxOTA3MjlaFw0yNTAxMTAxOTA3MjlaMIHSMQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3Nv
# ZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBU
# U1MgRVNOOjhENDEtNEJGNy1CM0I3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1T
# dGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvqQN
# aB5Gn5/FIFQPo3/K4QmleCDMF40bkoHwz0BshZ4SiQmA6CGUyDwmaqQ2wHhaXU0R
# dHtwvq+U8KxYYsyHKqaxxC7fr/yHZvHpNTgzx1VkR3pXhT6X2Cm175UX3WQ4jfl8
# 6onp5AMzBIFDlz0SU8VSKNMDvNXtjk9FitLgUv2nj3hOJ0KkEQfk3oA7m7zA0D+M
# o73hmR+OC7uwsXxJR2tzUZE0STYX3UvenFH7fYWy5BNmLyGq2sWkQ5HFvJKCJAE/
# dwft8+V43U3KeExF/pPtcLUvQ9HIrL0xnpMFau7Yd5aK+TEi57WctBv87+fSPZBV
# 3jZl/QCtcH9WrniBDwki9QfRxu/JYzw+iaEWLqrYXuF7jeOGvHK+fVeLWnAc5Wxs
# fbpjEMpNbGXbSF9At3PPhFVOjxwVEx1ALGUqRKehw9ap9X/gfkA9I9eTSvwJz9wy
# a9reDgS+6kXgSttI7RQ2cJG/tQPGVIaLCIaSafLneaq0Bns0t4+EW3B/GnoBMiiO
# XwleOvf5udBZQIMJ3k5qnnh8Z4ZhTwrE6iGbPrTgGBPXh7exFYAGlb6hdhILIVDd
# JlDf8s1NVvL0Q2y4SHZQhApZTuW/tyGsGscIPDSMz5bA6NhRLtjEwCFpLI5qGlu5
# 0Au9FRelCEQsWg7q07H/rqHOqCNJM4Rjem7joEUCAwEAAaOCAUkwggFFMB0GA1Ud
# DgQWBBSxrg1mvjUVt6Fnxj56nabZiJipAzAfBgNVHSMEGDAWgBSfpxVdAF5iXYP0
# 5dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIw
# MjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
# U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB
# /wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOC
# AgEAt76bLqnU08wRbW3vRrxjaEbGPqyINK6UYCzhTGaR/PEwCJziPT4ZM9sfGTX3
# eZDQVE9r121tFtp7NXQYuQSxRZMYXa0/pawN2Xn+UPjBRDvoCsU56dwKkrmy8TSw
# 7QXKGskdnEwsI5yW93q8Ag86RkBiKEEf9FdzHNuKWI4Kv//fDtESewu46n/u+Vck
# CwbOYl6wE//QRGrGMq509a4EbP+p1GUm06Xme/01mTIuKDgPmHL2nYRzXNqi2IuI
# ecn2aWwkRxQOFiPw+dicmOOwLG/7InNqjZpQeIhDMxsWr4zTxzy4ER/6zfthtlDt
# cAXHB7YRUkBTClaOa0ndvfNJZMyYVa6cWvZouTq9V5LS7UzIR8S/7RsOT43eOawL
# BsuQz0VoOLurYe1SffPqTsCcRNzbx0C8t/+KipStVhPAGttEfhdUUS9ohD6Lt6wN
# CJxZbV0IMD8nfE6gIQJXrzrXWOuJqN91WDyjRan4UKDkIBS2yWA4W6JhQuBzGerO
# SY/aLnxkRrSubgtnKYcHOwgxTTIya5WYCRjFt0QOLleqVki6k+mqYPr98uMPi5vR
# IQS206mDSenStr8w0J+/+1WEm3PnCCIQgpf6zhqRrAt9j7XrEMHrg2bQegaz8bLz
# be6UibgbKtRyk1nGde8To5kyMj9XUCBICDxT+F4xa5lNZVQwggdxMIIFWaADAgEC
# AhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQg
# Um9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVa
# Fw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
# dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
# YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIIC
# IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
# gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
# RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3X
# D9gmU3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoP
# z130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+
# tVSP3PoFVZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5Jas
# AUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/b
# fV+AutuqfjbsNkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuv
# XsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg
# 8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzF
# a/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqP
# nhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
# IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
# pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBB
# MD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0Rv
# Y3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGC
# NxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8w
# HwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmg
# R4ZFaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWlj
# Um9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEF
# BQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29D
# ZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEs
# H2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
# wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
# btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCg
# vxm2EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsId
# w2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2
# zsZ0/fZMcm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23K
# jgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beu
# yOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/
# tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjm
# jJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBj
# U02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIC1DCCAj0CAQEwggEAoYHYpIHVMIHS
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRN
# aWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRo
# YWxlcyBUU1MgRVNOOjhENDEtNEJGNy1CM0I3MSUwIwYDVQQDExxNaWNyb3NvZnQg
# VGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQA9iJe7w5FDiG8py4Ts
# YrQI6DFaeqCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
# dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
# YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0G
# CSqGSIb3DQEBBQUAAgUA6ZQ0RzAiGA8yMDI0MDMwNzIwNDAzOVoYDzIwMjQwMzA4
# MjA0MDM5WjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDplDRHAgEAMAcCAQACAhMA
# MAcCAQACAhE+MAoCBQDplYXHAgEAMDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQB
# hFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcNAQEFBQADgYEA
# pJEnzKRYJcEBy0IJBKgqvugkt6F2hBRhhWSpf3CmSbISpQrxzPasU2uZqYzenP/6
# J0xzV9OeSxF9rrQYpsm+l5987+DkIqndm1QdUasmmkV0CdZYZX/9dZ5/suP6Y6a3
# 4IEBK2A8wSBA3xVFeOKGcqphEB/SImFTSeIN65NJq6UxggQNMIIECQIBATCBkzB8
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
# aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAePfvZuaHGiDIgABAAAB
# 4zANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEE
# MC8GCSqGSIb3DQEJBDEiBCB6RJG/XePxyTPWSZRWXZPSDYTAZmH7YQY2zJbH3Lc5
# AjCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIDPUI6vlsP5k90SBCNa9wha4
# MlxBt2Crw12PTHIy5iYqMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAHj372bmhxogyIAAQAAAeMwIgQgw5X6icbI+b82Tnfm64Utww+j
# 4oCBxkQ23WlCVwRx7GMwDQYJKoZIhvcNAQELBQAEggIAf9g4RCOMlULrs/vdTUer
# E5yKCTn1jTQjclsPALTFglT/U/b6zosvTWXnnmcGoMkaSCSRVGXVtRFeZnUqHb9g
# LIYZALYpg1Q6WFNPi5MZJAStwv/rOKCw+7HmIM/hsG7F6oI45ZG+ThRil5oOUR6W
# uS9k3eGYMOeVZRxI5dhiNyvLM5hFHl2NYnNPSJAOMita+j+e/G5WKPJ1htST2i6e
# 51bZnXzB/NomGrTPxzXEd3Wf4RTykWAQcdPEphuOhUvozLdY21GuC5NnSb2VOM2t
# bI7QJqlshiX4L30OCkUEwn6YvbQ8wQOdLkulGRX5jFmBlakHAKfyEaZTJz4phQbX
# r275A+dWR6UiGj7+HnoeO7/FvAaIuXIghRAN9XTCB305RVkjMrG0pfZ26yXFeUO3
# M2gj0RXHHlMiY0Q/m/hmpw6lamOchV1TOITOUPob/jzqZ5A+iOVIxIy6fCJE7p62
# h7QM4aRF5/3+0AQ5K09gicPiIFMghtIczYC2hCyTmQp6iX80OoZ0bJ1y0HIu4FsK
# M0+fI+8C6bUdLCilyusWSDDaz8Y8yw9cV3tXoplztdVSWdDZhGb9zApAf3qbL3SH
# 0eIdFao7ziQf/uFHkKIIaCWytKYOD0Kw3DuyfUa0vjNccsn/lSK4RzcYK0GeS5bw
# 5D5Uk0VkPqy+KejrnnWTSoA=
# SIG # End signature block
