#
# Module manifest for module 'Microsoft.Graph.Beta.Identity.Governance'
#
# Generated by: Microsoft Corporation
#
# Generated on: 10/14/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.Identity.Governance.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f62a3a0f-f0ba-487f-99f3-cedc4cecfbdc'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Beta.Identity.Governance.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Beta.Identity.Governance.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgBetaAccessReviewDecision', 
               'Add-MgBetaAccessReviewInstanceDecision', 
               'Add-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecision', 
               'Add-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Export-MgBetaPrivilegedAccessResourcesRoleAssignment', 
               'Export-MgBetaPrivilegedAccessRoleAssignment', 
               'Get-MgBetaAccessReview', 'Get-MgBetaAccessReviewDecision', 
               'Get-MgBetaAccessReviewInstance', 
               'Get-MgBetaAccessReviewInstanceDecision', 
               'Get-MgBetaAccessReviewInstanceMyDecision', 
               'Get-MgBetaAccessReviewInstanceReviewer', 
               'Get-MgBetaAccessReviewMyDecision', 
               'Get-MgBetaAccessReviewReviewer', 'Get-MgBetaAgreement', 
               'Get-MgBetaAgreementAcceptance', 'Get-MgBetaAgreementFile', 
               'Get-MgBetaAgreementFileLocalization', 
               'Get-MgBetaAgreementFileLocalizationVersion', 
               'Get-MgBetaBusinessFlowTemplate', 
               'Get-MgBetaEntitlementManagementAccessPackage', 
               'Get-MgBetaEntitlementManagementAccessPackageApplicablePolicyRequirement', 
               'Get-MgBetaEntitlementManagementAccessPackageAssignment', 
               'Get-MgBetaEntitlementManagementAccessPackageAssignmentAdditional', 
               'Get-MgBetaEntitlementManagementAccessPackageAssignmentPolicy', 
               'Get-MgBetaEntitlementManagementAccessPackageAssignmentPolicyCustomExtensionHandler', 
               'Get-MgBetaEntitlementManagementAccessPackageAssignmentRequest', 
               'Get-MgBetaEntitlementManagementAccessPackageAssignmentResourceRole', 
               'Get-MgBetaEntitlementManagementAccessPackageCatalog', 
               'Get-MgBetaEntitlementManagementAccessPackageCatalogAccessPackageResource', 
               'Get-MgBetaEntitlementManagementAccessPackageCatalogAccessPackageResourceRole', 
               'Get-MgBetaEntitlementManagementAccessPackageCatalogAccessPackageResourceScope', 
               'Get-MgBetaEntitlementManagementAccessPackageCatalogCustomAccessPackageWorkflowExtension', 
               'Get-MgBetaEntitlementManagementAccessPackageIncompatibleAccessPackage', 
               'Get-MgBetaEntitlementManagementAccessPackageIncompatibleAccessPackageByRef', 
               'Get-MgBetaEntitlementManagementAccessPackageIncompatibleGroup', 
               'Get-MgBetaEntitlementManagementAccessPackageIncompatibleGroupByRef', 
               'Get-MgBetaEntitlementManagementAccessPackageIncompatibleWith', 
               'Get-MgBetaEntitlementManagementAccessPackageResource', 
               'Get-MgBetaEntitlementManagementAccessPackageResourceEnvironment', 
               'Get-MgBetaEntitlementManagementAccessPackageResourceRequest', 
               'Get-MgBetaEntitlementManagementConnectedOrganization', 
               'Get-MgBetaEntitlementManagementConnectedOrganizationExternalSponsor', 
               'Get-MgBetaEntitlementManagementConnectedOrganizationExternalSponsorById', 
               'Get-MgBetaEntitlementManagementConnectedOrganizationExternalSponsorByRef', 
               'Get-MgBetaEntitlementManagementConnectedOrganizationExternalSponsorUserOwnedObject', 
               'Get-MgBetaEntitlementManagementConnectedOrganizationInternalSponsor', 
               'Get-MgBetaEntitlementManagementConnectedOrganizationInternalSponsorById', 
               'Get-MgBetaEntitlementManagementConnectedOrganizationInternalSponsorByRef', 
               'Get-MgBetaEntitlementManagementConnectedOrganizationInternalSponsorUserOwnedObject', 
               'Get-MgBetaEntitlementManagementSetting', 
               'Get-MgBetaEntitlementManagementSubject', 
               'Get-MgBetaEntitlementManagementSubjectConnectedOrganization', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecision', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInsight', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInstance', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInstanceContactedReviewer', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecision', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecisionInsight', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDefinition', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStage', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStageDecision', 
               'Get-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStageDecisionInsight', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinition', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinitionInstance', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewer', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecisionInsight', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecisionInstance', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDefinition', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'Get-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceStageDecision', 
               'Get-MgBetaIdentityGovernanceAccessReviewHistoryDefinition', 
               'Get-MgBetaIdentityGovernanceAccessReviewHistoryDefinitionInstance', 
               'Get-MgBetaIdentityGovernanceAccessReviewPolicy', 
               'Get-MgBetaIdentityGovernanceAppConsentRequest', 
               'Get-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequest', 
               'Get-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequestApproval', 
               'Get-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStep', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflow', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtension', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtensionCreatedBy', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtensionLastModifiedBy', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItem', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflow', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowExecutionScope', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowRun', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowTaskReport', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowUserProcessingResult', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowVersion', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowExecutionScope', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowRun', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowRunTaskProcessingResult', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowRunTaskProcessingResultSubject', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowRunTaskProcessingResultTask', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResult', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResultSubject', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResultTaskProcessingResult', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowSetting', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTaskDefinition', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTaskReport', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTaskReportTask', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTaskReportTaskDefinition', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTaskReportTaskProcessingResult', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTaskReportTaskProcessingResultSubject', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTaskReportTaskProcessingResultTask', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTemplate', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTask', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTaskProcessingResult', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTaskProcessingResultSubject', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTaskProcessingResultTask', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResult', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResultSubject', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResultTaskProcessingResult', 
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowVersion', 
               'Get-MgBetaIdentityGovernanceTermOfUseAgreement', 
               'Get-MgBetaIdentityGovernanceTermOfUseAgreementAcceptance', 
               'Get-MgBetaIdentityGovernanceTermOfUseAgreementFile', 
               'Get-MgBetaIdentityGovernanceTermOfUseAgreementFileLocalization', 
               'Get-MgBetaIdentityGovernanceTermOfUseAgreementFileLocalizationVersion', 
               'Get-MgBetaPrivilegedAccess', 'Get-MgBetaPrivilegedAccessResource', 
               'Get-MgBetaPrivilegedAccessResourceParent', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignment', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentLinkedEligibleRoleAssignment', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRequest', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRequestResource', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRequestRoleDefinition', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRequestRoleDefinitionResource', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRequestRoleDefinitionRoleSetting', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRequestSubject', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentResource', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRoleDefinition', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRoleDefinitionResource', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentRoleDefinitionRoleSetting', 
               'Get-MgBetaPrivilegedAccessResourceRoleAssignmentSubject', 
               'Get-MgBetaPrivilegedAccessResourceRoleDefinition', 
               'Get-MgBetaPrivilegedAccessResourceRoleDefinitionResource', 
               'Get-MgBetaPrivilegedAccessResourceRoleDefinitionRoleSetting', 
               'Get-MgBetaPrivilegedAccessResourceRoleSetting', 
               'Get-MgBetaPrivilegedAccessResourceRoleSettingResource', 
               'Get-MgBetaPrivilegedAccessResourceRoleSettingRoleDefinition', 
               'Get-MgBetaPrivilegedAccessResourceRoleSettingRoleDefinitionResource', 
               'Get-MgBetaPrivilegedAccessResourceRoleSettingRoleDefinitionRoleSetting', 
               'Get-MgBetaPrivilegedAccessRoleAssignment', 
               'Get-MgBetaPrivilegedAccessRoleAssignmentLinkedEligibleRoleAssignment', 
               'Get-MgBetaPrivilegedAccessRoleAssignmentRequest', 
               'Get-MgBetaPrivilegedAccessRoleAssignmentRequestResource', 
               'Get-MgBetaPrivilegedAccessRoleAssignmentRequestRoleDefinition', 
               'Get-MgBetaPrivilegedAccessRoleAssignmentRequestSubject', 
               'Get-MgBetaPrivilegedAccessRoleAssignmentResource', 
               'Get-MgBetaPrivilegedAccessRoleAssignmentRoleDefinition', 
               'Get-MgBetaPrivilegedAccessRoleAssignmentSubject', 
               'Get-MgBetaPrivilegedAccessRoleDefinition', 
               'Get-MgBetaPrivilegedAccessRoleDefinitionResource', 
               'Get-MgBetaPrivilegedAccessRoleDefinitionRoleSetting', 
               'Get-MgBetaPrivilegedAccessRoleSetting', 
               'Get-MgBetaPrivilegedAccessRoleSettingResource', 
               'Get-MgBetaPrivilegedAccessRoleSettingRoleDefinition', 
               'Get-MgBetaPrivilegedApproval', 
               'Get-MgBetaPrivilegedApprovalRequest', 
               'Get-MgBetaPrivilegedApprovalRoleInfo', 
               'Get-MgBetaPrivilegedApprovalRoleInfoAssignment', 
               'Get-MgBetaPrivilegedApprovalRoleInfoSetting', 
               'Get-MgBetaPrivilegedApprovalRoleInfoSummary', 
               'Get-MgBetaPrivilegedOperationEvent', 'Get-MgBetaPrivilegedRole', 
               'Get-MgBetaPrivilegedRoleAssignmentRequest', 
               'Get-MgBetaPrivilegedRoleAssignmentRequestRoleInfo', 
               'Get-MgBetaPrivilegedRoleAssignmentRequestRoleInfoAssignment', 
               'Get-MgBetaPrivilegedRoleAssignmentRequestRoleInfoSetting', 
               'Get-MgBetaPrivilegedRoleAssignmentRequestRoleInfoSummary', 
               'Get-MgBetaPrivilegedRoleAssignmentRoleInfo', 
               'Get-MgBetaPrivilegedRoleAssignmentRoleInfoAssignment', 
               'Get-MgBetaPrivilegedRoleAssignmentRoleInfoSetting', 
               'Get-MgBetaPrivilegedRoleAssignmentRoleInfoSummary', 
               'Get-MgBetaPrivilegedRoleRoleAssignment', 
               'Get-MgBetaPrivilegedRoleSetting', 
               'Get-MgBetaPrivilegedRoleSummary', 'Get-MgBetaProgram', 
               'Get-MgBetaProgramControl', 'Get-MgBetaProgramControlProgram', 
               'Get-MgBetaProgramControlType', 'Get-MgBetaRoleManagementDirectory', 
               'Get-MgBetaRoleManagementDirectoryResourceNamespace', 
               'Get-MgBetaRoleManagementDirectoryResourceNamespaceResourceAction', 
               'Get-MgBetaRoleManagementDirectoryResourceNamespaceResourceActionResourceScope', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignment', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentApproval', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentApprovalStep', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentAppScope', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentDirectoryScope', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentPrincipal', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentRoleDefinition', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentSchedule', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleActivatedUsing', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleInstance', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleInstanceActivatedUsing', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequestActivatedUsing', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequestAppScope', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequestDirectoryScope', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequestPrincipal', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequestRoleDefinition', 
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequestTargetSchedule', 
               'Get-MgBetaRoleManagementDirectoryRoleDefinition', 
               'Get-MgBetaRoleManagementDirectoryRoleDefinitionInheritPermissionFrom', 
               'Get-MgBetaRoleManagementDirectoryRoleEligibilitySchedule', 
               'Get-MgBetaRoleManagementDirectoryRoleEligibilityScheduleInstance', 
               'Get-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'Get-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequestAppScope', 
               'Get-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequestDirectoryScope', 
               'Get-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequestPrincipal', 
               'Get-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequestRoleDefinition', 
               'Get-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequestTargetSchedule', 
               'Get-MgBetaRoleManagementDirectoryTransitiveRoleAssignment', 
               'Get-MgBetaRoleManagementDirectoryTransitiveRoleAssignmentAppScope', 
               'Get-MgBetaRoleManagementDirectoryTransitiveRoleAssignmentDirectoryScope', 
               'Get-MgBetaRoleManagementDirectoryTransitiveRoleAssignmentPrincipal', 
               'Get-MgBetaRoleManagementDirectoryTransitiveRoleAssignmentRoleDefinition', 
               'Get-MgBetaRoleManagementEntitlementManagement', 
               'Get-MgBetaRoleManagementEntitlementManagementResourceNamespace', 
               'Get-MgBetaRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'Get-MgBetaRoleManagementEntitlementManagementResourceNamespaceResourceActionResourceScope', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignment', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentApproval', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentApprovalStep', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentAppScope', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentDirectoryScope', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentPrincipal', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentRoleDefinition', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentSchedule', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleActivatedUsing', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleInstance', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleInstanceActivatedUsing', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequestActivatedUsing', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequestAppScope', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequestDirectoryScope', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequestPrincipal', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequestRoleDefinition', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequestTargetSchedule', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleDefinition', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFrom', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleEligibilitySchedule', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleInstance', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequestAppScope', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequestDirectoryScope', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequestPrincipal', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequestRoleDefinition', 
               'Get-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequestTargetSchedule', 
               'Get-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignment', 
               'Get-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignmentAppScope', 
               'Get-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignmentDirectoryScope', 
               'Get-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignmentPrincipal', 
               'Get-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignmentRoleDefinition', 
               'Get-MgBetaUserAgreementAcceptance', 
               'Import-MgBetaRoleManagementCloudPcResourceNamespaceResourceAction', 
               'Import-MgBetaRoleManagementDeviceManagementResourceNamespaceResourceAction', 
               'Import-MgBetaRoleManagementDirectoryResourceNamespaceResourceAction', 
               'Import-MgBetaRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'Initialize-MgBetaIdentityGovernanceLifecycleWorkflowsDeletedItemsWorkflow', 
               'Initialize-MgBetaIdentityGovernanceLifecycleWorkflowsWorkflow', 
               'Invoke-MgBetaAcceptIdentityGovernanceAccessReviewDecisionInstanceRecommendation', 
               'Invoke-MgBetaAcceptIdentityGovernanceAccessReviewDefinitionInstanceRecommendation', 
               'Invoke-MgBetaAssignedRoleManagementCloudPcRoleDefinitionInheritPermissionFromPrincipal', 
               'Invoke-MgBetaAssignedRoleManagementCloudPcRoleDefinitionPrincipal', 
               'Invoke-MgBetaAssignedRoleManagementDeviceManagementRoleDefinitionInheritPermissionFromPrincipal', 
               'Invoke-MgBetaAssignedRoleManagementDeviceManagementRoleDefinitionPrincipal', 
               'Invoke-MgBetaAssignedRoleManagementDirectoryRoleDefinitionInheritPermissionFromPrincipal', 
               'Invoke-MgBetaAssignedRoleManagementDirectoryRoleDefinitionPrincipal', 
               'Invoke-MgBetaAssignedRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFromPrincipal', 
               'Invoke-MgBetaAssignedRoleManagementEntitlementManagementRoleDefinitionPrincipal', 
               'Invoke-MgBetaBatchIdentityGovernanceAccessReviewDecisionInstanceRecordDecision', 
               'Invoke-MgBetaBatchIdentityGovernanceAccessReviewDefinitionInstanceRecordDecision', 
               'Invoke-MgBetaFilterEntitlementManagementAccessPackageAssignmentApprovalByCurrentUser', 
               'Invoke-MgBetaFilterEntitlementManagementAccessPackageAssignmentByCurrentUser', 
               'Invoke-MgBetaFilterEntitlementManagementAccessPackageAssignmentRequestByCurrentUser', 
               'Invoke-MgBetaFilterEntitlementManagementAccessPackageByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAccessReviewDecisionByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAccessReviewDecisionInstanceDecisionByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAccessReviewDecisionInstanceStageByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAccessReviewDecisionInstanceStageDecisionByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAccessReviewDefinitionByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAccessReviewDefinitionInstanceByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAccessReviewDefinitionInstanceDecisionByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAccessReviewDefinitionInstanceStageByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAppConsentRequestByCurrentUser', 
               'Invoke-MgBetaFilterIdentityGovernanceAppConsentRequestUserConsentRequestByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementDirectoryRoleAssignmentApprovalByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementDirectoryRoleAssignmentScheduleByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementDirectoryRoleAssignmentScheduleInstanceByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementDirectoryRoleAssignmentScheduleRequestByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementDirectoryRoleEligibilityScheduleByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementDirectoryRoleEligibilityScheduleInstanceByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementDirectoryRoleEligibilityScheduleRequestByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementEntitlementManagementRoleAssignmentApprovalByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementEntitlementManagementRoleAssignmentScheduleByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementEntitlementManagementRoleAssignmentScheduleInstanceByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementEntitlementManagementRoleAssignmentScheduleRequestByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementEntitlementManagementRoleEligibilityScheduleByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementEntitlementManagementRoleEligibilityScheduleInstanceByCurrentUser', 
               'Invoke-MgBetaFilterRoleManagementEntitlementManagementRoleEligibilityScheduleRequestByCurrentUser', 
               'Invoke-MgBetaMyPrivilegedApprovalRequest', 
               'Invoke-MgBetaMyPrivilegedRoleAssignment', 
               'Invoke-MgBetaMyPrivilegedRoleAssignmentRequest', 
               'Invoke-MgBetaRecordIdentityGovernanceAccessReviewDecision', 
               'Invoke-MgBetaRecordIdentityGovernanceAccessReviewDecisionInstanceDecision', 
               'Invoke-MgBetaRecordIdentityGovernanceAccessReviewDecisionInstanceStageDecision', 
               'Invoke-MgBetaRecordIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Invoke-MgBetaRoleManagementDirectorySchedule', 
               'Invoke-MgBetaRoleManagementEntitlementManagementSchedule', 
               'Invoke-MgBetaScheduleRoleManagementDirectory', 
               'Invoke-MgBetaScheduleRoleManagementEntitlementManagement', 
               'Invoke-MgBetaSelfPrivilegedApprovalRoleInfoActivate', 
               'Invoke-MgBetaSelfPrivilegedApprovalRoleInfoDeactivate', 
               'Invoke-MgBetaSelfPrivilegedRoleActivate', 
               'Invoke-MgBetaSelfPrivilegedRoleAssignmentRequestRoleInfoActivate', 
               'Invoke-MgBetaSelfPrivilegedRoleAssignmentRequestRoleInfoDeactivate', 
               'Invoke-MgBetaSelfPrivilegedRoleAssignmentRoleInfoActivate', 
               'Invoke-MgBetaSelfPrivilegedRoleAssignmentRoleInfoDeactivate', 
               'Invoke-MgBetaSelfPrivilegedRoleDeactivate', 
               'Invoke-MgBetaSummaryIdentityGovernanceLifecycleWorkflowRun', 
               'Invoke-MgBetaSummaryIdentityGovernanceLifecycleWorkflowRunUserProcessingResult', 
               'Invoke-MgBetaSummaryIdentityGovernanceLifecycleWorkflowTaskReport', 
               'Invoke-MgBetaSummaryIdentityGovernanceLifecycleWorkflowUserProcessingResult', 
               'Move-MgBetaEntitlementManagementAccessPackageToCatalog', 
               'New-MgBetaAccessReview', 'New-MgBetaAccessReviewDecision', 
               'New-MgBetaAccessReviewInstance', 
               'New-MgBetaAccessReviewInstanceDecision', 
               'New-MgBetaAccessReviewInstanceMyDecision', 
               'New-MgBetaAccessReviewInstanceReviewer', 
               'New-MgBetaAccessReviewMyDecision', 
               'New-MgBetaAccessReviewReviewer', 'New-MgBetaAgreement', 
               'New-MgBetaAgreementAcceptance', 
               'New-MgBetaAgreementFileLocalization', 
               'New-MgBetaAgreementFileLocalizationVersion', 
               'New-MgBetaBusinessFlowTemplate', 
               'New-MgBetaEntitlementManagementAccessPackage', 
               'New-MgBetaEntitlementManagementAccessPackageAssignment', 
               'New-MgBetaEntitlementManagementAccessPackageAssignmentPolicy', 
               'New-MgBetaEntitlementManagementAccessPackageAssignmentPolicyCustomExtensionHandler', 
               'New-MgBetaEntitlementManagementAccessPackageAssignmentRequest', 
               'New-MgBetaEntitlementManagementAccessPackageCatalog', 
               'New-MgBetaEntitlementManagementAccessPackageCatalogCustomAccessPackageWorkflowExtension', 
               'New-MgBetaEntitlementManagementAccessPackageIncompatibleAccessPackageByRef', 
               'New-MgBetaEntitlementManagementAccessPackageIncompatibleGroupByRef', 
               'New-MgBetaEntitlementManagementAccessPackageResourceRequest', 
               'New-MgBetaEntitlementManagementAccessPackageResourceRoleScope', 
               'New-MgBetaEntitlementManagementConnectedOrganization', 
               'New-MgBetaEntitlementManagementConnectedOrganizationExternalSponsorByRef', 
               'New-MgBetaEntitlementManagementConnectedOrganizationInternalSponsorByRef', 
               'New-MgBetaEntitlementManagementSubject', 
               'New-MgBetaIdentityGovernanceAccessReviewDecision', 
               'New-MgBetaIdentityGovernanceAccessReviewDecisionInsight', 
               'New-MgBetaIdentityGovernanceAccessReviewDecisionInstanceContactedReviewer', 
               'New-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecision', 
               'New-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecisionInsight', 
               'New-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStage', 
               'New-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStageDecision', 
               'New-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStageDecisionInsight', 
               'New-MgBetaIdentityGovernanceAccessReviewDefinition', 
               'New-MgBetaIdentityGovernanceAccessReviewDefinitionInstance', 
               'New-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewer', 
               'New-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'New-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecisionInsight', 
               'New-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'New-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceStageDecision', 
               'New-MgBetaIdentityGovernanceAccessReviewHistoryDefinition', 
               'New-MgBetaIdentityGovernanceAccessReviewHistoryDefinitionInstance', 
               'New-MgBetaIdentityGovernanceAccessReviewHistoryDefinitionInstanceDownloadUri', 
               'New-MgBetaIdentityGovernanceAppConsentRequest', 
               'New-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequest', 
               'New-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStep', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflow', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtension', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflow', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowNewVersion', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowRun', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowTaskReport', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowUserProcessingResult', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowVersion', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowNewVersion', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowRun', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowRunTaskProcessingResult', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResult', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResultTaskProcessingResult', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowTaskDefinition', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowTaskReport', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowTaskReportTaskProcessingResult', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowTemplate', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTask', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTaskProcessingResult', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResult', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResultTaskProcessingResult', 
               'New-MgBetaIdentityGovernanceLifecycleWorkflowVersion', 
               'New-MgBetaIdentityGovernanceTermOfUseAgreement', 
               'New-MgBetaIdentityGovernanceTermOfUseAgreementAcceptance', 
               'New-MgBetaIdentityGovernanceTermOfUseAgreementFileLocalization', 
               'New-MgBetaIdentityGovernanceTermOfUseAgreementFileLocalizationVersion', 
               'New-MgBetaPrivilegedAccess', 'New-MgBetaPrivilegedAccessResource', 
               'New-MgBetaPrivilegedAccessResourceRoleAssignment', 
               'New-MgBetaPrivilegedAccessResourceRoleAssignmentRequest', 
               'New-MgBetaPrivilegedAccessResourceRoleDefinition', 
               'New-MgBetaPrivilegedAccessResourceRoleSetting', 
               'New-MgBetaPrivilegedAccessRoleAssignment', 
               'New-MgBetaPrivilegedAccessRoleAssignmentRequest', 
               'New-MgBetaPrivilegedAccessRoleDefinition', 
               'New-MgBetaPrivilegedAccessRoleSetting', 
               'New-MgBetaPrivilegedApproval', 
               'New-MgBetaPrivilegedOperationEvent', 'New-MgBetaPrivilegedRole', 
               'New-MgBetaPrivilegedRoleAssignment', 
               'New-MgBetaPrivilegedRoleAssignmentEligible', 
               'New-MgBetaPrivilegedRoleAssignmentPermanent', 
               'New-MgBetaPrivilegedRoleAssignmentRequest', 'New-MgBetaProgram', 
               'New-MgBetaProgramControl', 'New-MgBetaProgramControlType', 
               'New-MgBetaRoleManagementDirectoryResourceNamespace', 
               'New-MgBetaRoleManagementDirectoryResourceNamespaceResourceAction', 
               'New-MgBetaRoleManagementDirectoryRoleAssignment', 
               'New-MgBetaRoleManagementDirectoryRoleAssignmentApproval', 
               'New-MgBetaRoleManagementDirectoryRoleAssignmentApprovalStep', 
               'New-MgBetaRoleManagementDirectoryRoleAssignmentSchedule', 
               'New-MgBetaRoleManagementDirectoryRoleAssignmentScheduleInstance', 
               'New-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'New-MgBetaRoleManagementDirectoryRoleDefinition', 
               'New-MgBetaRoleManagementDirectoryRoleDefinitionInheritPermissionFrom', 
               'New-MgBetaRoleManagementDirectoryRoleEligibilitySchedule', 
               'New-MgBetaRoleManagementDirectoryRoleEligibilityScheduleInstance', 
               'New-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'New-MgBetaRoleManagementDirectoryTransitiveRoleAssignment', 
               'New-MgBetaRoleManagementEntitlementManagementResourceNamespace', 
               'New-MgBetaRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'New-MgBetaRoleManagementEntitlementManagementRoleAssignment', 
               'New-MgBetaRoleManagementEntitlementManagementRoleAssignmentApproval', 
               'New-MgBetaRoleManagementEntitlementManagementRoleAssignmentApprovalStep', 
               'New-MgBetaRoleManagementEntitlementManagementRoleAssignmentSchedule', 
               'New-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleInstance', 
               'New-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'New-MgBetaRoleManagementEntitlementManagementRoleDefinition', 
               'New-MgBetaRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFrom', 
               'New-MgBetaRoleManagementEntitlementManagementRoleEligibilitySchedule', 
               'New-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleInstance', 
               'New-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'New-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignment', 
               'Register-MgBetaPrivilegedAccessResource', 
               'Remove-MgBetaAccessReview', 'Remove-MgBetaAccessReviewDecision', 
               'Remove-MgBetaAccessReviewInstance', 
               'Remove-MgBetaAccessReviewInstanceDecision', 
               'Remove-MgBetaAccessReviewInstanceMyDecision', 
               'Remove-MgBetaAccessReviewInstanceReviewer', 
               'Remove-MgBetaAccessReviewMyDecision', 
               'Remove-MgBetaAccessReviewReviewer', 'Remove-MgBetaAgreement', 
               'Remove-MgBetaAgreementAcceptance', 'Remove-MgBetaAgreementFile', 
               'Remove-MgBetaAgreementFileLocalization', 
               'Remove-MgBetaAgreementFileLocalizationVersion', 
               'Remove-MgBetaBusinessFlowTemplate', 
               'Remove-MgBetaEntitlementManagementAccessPackage', 
               'Remove-MgBetaEntitlementManagementAccessPackageAssignment', 
               'Remove-MgBetaEntitlementManagementAccessPackageAssignmentApproval', 
               'Remove-MgBetaEntitlementManagementAccessPackageAssignmentApprovalStep', 
               'Remove-MgBetaEntitlementManagementAccessPackageAssignmentPolicy', 
               'Remove-MgBetaEntitlementManagementAccessPackageAssignmentPolicyCustomExtensionHandler', 
               'Remove-MgBetaEntitlementManagementAccessPackageAssignmentRequest', 
               'Remove-MgBetaEntitlementManagementAccessPackageCatalog', 
               'Remove-MgBetaEntitlementManagementAccessPackageCatalogCustomAccessPackageWorkflowExtension', 
               'Remove-MgBetaEntitlementManagementAccessPackageIncompatibleAccessPackageByRef', 
               'Remove-MgBetaEntitlementManagementAccessPackageIncompatibleGroupByRef', 
               'Remove-MgBetaEntitlementManagementAccessPackageResourceRequest', 
               'Remove-MgBetaEntitlementManagementAccessPackageResourceRoleScope', 
               'Remove-MgBetaEntitlementManagementConnectedOrganization', 
               'Remove-MgBetaEntitlementManagementConnectedOrganizationExternalSponsorByRef', 
               'Remove-MgBetaEntitlementManagementConnectedOrganizationInternalSponsorByRef', 
               'Remove-MgBetaEntitlementManagementSubject', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecision', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecisionInsight', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecisionInstance', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecisionInstanceContactedReviewer', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecision', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecisionInsight', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStage', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStageDecision', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStageDecisionInsight', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinition', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinitionInstance', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewer', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecisionInsight', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecisionInstance', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceStageDecision', 
               'Remove-MgBetaIdentityGovernanceAccessReviewHistoryDefinition', 
               'Remove-MgBetaIdentityGovernanceAccessReviewHistoryDefinitionInstance', 
               'Remove-MgBetaIdentityGovernanceAccessReviewPolicy', 
               'Remove-MgBetaIdentityGovernanceAppConsentRequest', 
               'Remove-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequest', 
               'Remove-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequestApproval', 
               'Remove-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStep', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflow', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtension', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItem', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflow', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowRun', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowTaskReport', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowUserProcessingResult', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowVersion', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowRun', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowRunTaskProcessingResult', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResult', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResultTaskProcessingResult', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowSetting', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowTaskDefinition', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowTaskReport', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowTaskReportTaskProcessingResult', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowTemplate', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTask', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTaskProcessingResult', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResult', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResultTaskProcessingResult', 
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowVersion', 
               'Remove-MgBetaIdentityGovernanceTermOfUseAgreement', 
               'Remove-MgBetaIdentityGovernanceTermOfUseAgreementAcceptance', 
               'Remove-MgBetaIdentityGovernanceTermOfUseAgreementFile', 
               'Remove-MgBetaIdentityGovernanceTermOfUseAgreementFileLocalization', 
               'Remove-MgBetaIdentityGovernanceTermOfUseAgreementFileLocalizationVersion', 
               'Remove-MgBetaPrivilegedAccess', 
               'Remove-MgBetaPrivilegedAccessResource', 
               'Remove-MgBetaPrivilegedAccessResourceRoleAssignment', 
               'Remove-MgBetaPrivilegedAccessResourceRoleAssignmentRequest', 
               'Remove-MgBetaPrivilegedAccessResourceRoleAssignmentRequestRoleDefinition', 
               'Remove-MgBetaPrivilegedAccessResourceRoleAssignmentRequestSubject', 
               'Remove-MgBetaPrivilegedAccessResourceRoleAssignmentRoleDefinition', 
               'Remove-MgBetaPrivilegedAccessResourceRoleAssignmentSubject', 
               'Remove-MgBetaPrivilegedAccessResourceRoleDefinition', 
               'Remove-MgBetaPrivilegedAccessResourceRoleSetting', 
               'Remove-MgBetaPrivilegedAccessResourceRoleSettingRoleDefinition', 
               'Remove-MgBetaPrivilegedAccessRoleAssignment', 
               'Remove-MgBetaPrivilegedAccessRoleAssignmentRequest', 
               'Remove-MgBetaPrivilegedAccessRoleAssignmentRequestRoleDefinition', 
               'Remove-MgBetaPrivilegedAccessRoleAssignmentRequestSubject', 
               'Remove-MgBetaPrivilegedAccessRoleAssignmentRoleDefinition', 
               'Remove-MgBetaPrivilegedAccessRoleAssignmentSubject', 
               'Remove-MgBetaPrivilegedAccessRoleDefinition', 
               'Remove-MgBetaPrivilegedAccessRoleSetting', 
               'Remove-MgBetaPrivilegedAccessRoleSettingRoleDefinition', 
               'Remove-MgBetaPrivilegedApproval', 
               'Remove-MgBetaPrivilegedApprovalRoleInfo', 
               'Remove-MgBetaPrivilegedApprovalRoleInfoSetting', 
               'Remove-MgBetaPrivilegedApprovalRoleInfoSummary', 
               'Remove-MgBetaPrivilegedOperationEvent', 
               'Remove-MgBetaPrivilegedRole', 
               'Remove-MgBetaPrivilegedRoleAssignment', 
               'Remove-MgBetaPrivilegedRoleAssignmentRequest', 
               'Remove-MgBetaPrivilegedRoleAssignmentRequestRoleInfo', 
               'Remove-MgBetaPrivilegedRoleAssignmentRequestRoleInfoSetting', 
               'Remove-MgBetaPrivilegedRoleAssignmentRequestRoleInfoSummary', 
               'Remove-MgBetaPrivilegedRoleAssignmentRoleInfo', 
               'Remove-MgBetaPrivilegedRoleAssignmentRoleInfoSetting', 
               'Remove-MgBetaPrivilegedRoleAssignmentRoleInfoSummary', 
               'Remove-MgBetaPrivilegedRoleSetting', 
               'Remove-MgBetaPrivilegedRoleSummary', 'Remove-MgBetaProgram', 
               'Remove-MgBetaProgramControl', 'Remove-MgBetaProgramControlProgram', 
               'Remove-MgBetaProgramControlType', 
               'Remove-MgBetaRoleManagementDirectory', 
               'Remove-MgBetaRoleManagementDirectoryResourceNamespace', 
               'Remove-MgBetaRoleManagementDirectoryResourceNamespaceResourceAction', 
               'Remove-MgBetaRoleManagementDirectoryResourceNamespaceResourceActionResourceScope', 
               'Remove-MgBetaRoleManagementDirectoryRoleAssignment', 
               'Remove-MgBetaRoleManagementDirectoryRoleAssignmentApproval', 
               'Remove-MgBetaRoleManagementDirectoryRoleAssignmentApprovalStep', 
               'Remove-MgBetaRoleManagementDirectoryRoleAssignmentAppScope', 
               'Remove-MgBetaRoleManagementDirectoryRoleAssignmentSchedule', 
               'Remove-MgBetaRoleManagementDirectoryRoleAssignmentScheduleInstance', 
               'Remove-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'Remove-MgBetaRoleManagementDirectoryRoleDefinition', 
               'Remove-MgBetaRoleManagementDirectoryRoleDefinitionInheritPermissionFrom', 
               'Remove-MgBetaRoleManagementDirectoryRoleEligibilitySchedule', 
               'Remove-MgBetaRoleManagementDirectoryRoleEligibilityScheduleInstance', 
               'Remove-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'Remove-MgBetaRoleManagementDirectoryTransitiveRoleAssignment', 
               'Remove-MgBetaRoleManagementDirectoryTransitiveRoleAssignmentAppScope', 
               'Remove-MgBetaRoleManagementEntitlementManagement', 
               'Remove-MgBetaRoleManagementEntitlementManagementResourceNamespace', 
               'Remove-MgBetaRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'Remove-MgBetaRoleManagementEntitlementManagementResourceNamespaceResourceActionResourceScope', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleAssignment', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleAssignmentApproval', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleAssignmentApprovalStep', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleAssignmentAppScope', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleAssignmentSchedule', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleInstance', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleDefinition', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFrom', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleEligibilitySchedule', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleInstance', 
               'Remove-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'Remove-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignment', 
               'Remove-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignmentAppScope', 
               'Reset-MgBetaAccessReviewDecision', 
               'Reset-MgBetaAccessReviewInstanceDecision', 
               'Reset-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecision', 
               'Reset-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Restore-MgBetaIdentityGovernanceLifecycleWorkflowsDeletedItemsWorkflow', 
               'Restore-MgBetaIdentityGovernanceLifecycleWorkflowsWorkflow', 
               'Resume-MgBetaIdentityGovernanceLifecycleWorkflowsRunsTaskProcessingResult', 
               'Resume-MgBetaIdentityGovernanceLifecycleWorkflowsTaskReportsTaskProcessingResult', 
               'Resume-MgBetaIdentityGovernanceLifecycleWorkflowsWorkflowTemplatesTasksTaskProcessingResult', 
               'Select-MgBetaEntitlementManagementAccessPackage', 
               'Select-MgBetaEntitlementManagementAccessPackageAssignmentPolicy', 
               'Send-MgBetaAccessReviewInstanceReminder', 
               'Send-MgBetaAccessReviewReminder', 
               'Send-MgBetaIdentityGovernanceAccessReviewDecisionInstanceReminder', 
               'Send-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceReminder', 
               'Set-MgBetaEntitlementManagementAccessPackageAssignmentPolicy', 
               'Split-MgBetaEntitlementManagementConnectedOrganization', 
               'Stop-MgBetaAccessReview', 'Stop-MgBetaAccessReviewsInstance', 
               'Stop-MgBetaEntitlementManagementAccessPackageAssignmentRequest', 
               'Stop-MgBetaIdentityGovernanceAccessReviewsDecisionsInstance', 
               'Stop-MgBetaIdentityGovernanceAccessReviewsDecisionsInstanceStage', 
               'Stop-MgBetaIdentityGovernanceAccessReviewsDefinition', 
               'Stop-MgBetaIdentityGovernanceAccessReviewsDefinitionsInstance', 
               'Stop-MgBetaIdentityGovernanceAccessReviewsDefinitionsInstancesStage', 
               'Stop-MgBetaPrivilegedAccessResourcesRoleAssignmentRequest', 
               'Stop-MgBetaPrivilegedAccessRoleAssignmentRequest', 
               'Stop-MgBetaPrivilegedRoleAssignmentRequest', 
               'Stop-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'Stop-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'Stop-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'Stop-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'Test-MgBetaEntitlementManagementConnectedOrganizationExternalSponsorProperty', 
               'Test-MgBetaEntitlementManagementConnectedOrganizationInternalSponsorProperty', 
               'Update-MgBetaAccessReview', 'Update-MgBetaAccessReviewDecision', 
               'Update-MgBetaAccessReviewInstance', 
               'Update-MgBetaAccessReviewInstanceDecision', 
               'Update-MgBetaAccessReviewInstanceMyDecision', 
               'Update-MgBetaAccessReviewInstanceReviewer', 
               'Update-MgBetaAccessReviewMyDecision', 
               'Update-MgBetaAccessReviewReviewer', 'Update-MgBetaAgreement', 
               'Update-MgBetaAgreementAcceptance', 'Update-MgBetaAgreementFile', 
               'Update-MgBetaAgreementFileLocalization', 
               'Update-MgBetaAgreementFileLocalizationVersion', 
               'Update-MgBetaBusinessFlowTemplate', 
               'Update-MgBetaEntitlementManagementAccessPackage', 
               'Update-MgBetaEntitlementManagementAccessPackageAssignment', 
               'Update-MgBetaEntitlementManagementAccessPackageAssignmentApproval', 
               'Update-MgBetaEntitlementManagementAccessPackageAssignmentApprovalStep', 
               'Update-MgBetaEntitlementManagementAccessPackageAssignmentPolicy', 
               'Update-MgBetaEntitlementManagementAccessPackageAssignmentPolicyCustomExtensionHandler', 
               'Update-MgBetaEntitlementManagementAccessPackageAssignmentRequest', 
               'Update-MgBetaEntitlementManagementAccessPackageCatalog', 
               'Update-MgBetaEntitlementManagementAccessPackageCatalogCustomAccessPackageWorkflowExtension', 
               'Update-MgBetaEntitlementManagementAccessPackageResourceRequest', 
               'Update-MgBetaEntitlementManagementAccessPackageResourceRoleScope', 
               'Update-MgBetaEntitlementManagementConnectedOrganization', 
               'Update-MgBetaEntitlementManagementSetting', 
               'Update-MgBetaEntitlementManagementSubject', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecision', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecisionInsight', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecisionInstance', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecisionInstanceContactedReviewer', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecision', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecisionInstanceDecisionInsight', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStage', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStageDecision', 
               'Update-MgBetaIdentityGovernanceAccessReviewDecisionInstanceStageDecisionInsight', 
               'Update-MgBetaIdentityGovernanceAccessReviewDefinition', 
               'Update-MgBetaIdentityGovernanceAccessReviewDefinitionInstance', 
               'Update-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewer', 
               'Update-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Update-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecisionInsight', 
               'Update-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceDecisionInstance', 
               'Update-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'Update-MgBetaIdentityGovernanceAccessReviewDefinitionInstanceStageDecision', 
               'Update-MgBetaIdentityGovernanceAccessReviewHistoryDefinition', 
               'Update-MgBetaIdentityGovernanceAccessReviewHistoryDefinitionInstance', 
               'Update-MgBetaIdentityGovernanceAccessReviewPolicy', 
               'Update-MgBetaIdentityGovernanceAppConsentRequest', 
               'Update-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequest', 
               'Update-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequestApproval', 
               'Update-MgBetaIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStep', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflow', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtension', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItem', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflow', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowRun', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowTaskReport', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowUserProcessingResult', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowDeletedItemWorkflowVersion', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowRun', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowRunTaskProcessingResult', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResult', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowRunUserProcessingResultTaskProcessingResult', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowSetting', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowTaskDefinition', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowTaskReport', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowTaskReportTaskProcessingResult', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowTemplate', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTask', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowTemplateTaskProcessingResult', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResult', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowUserProcessingResultTaskProcessingResult', 
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowVersion', 
               'Update-MgBetaIdentityGovernanceTermOfUseAgreement', 
               'Update-MgBetaIdentityGovernanceTermOfUseAgreementAcceptance', 
               'Update-MgBetaIdentityGovernanceTermOfUseAgreementFile', 
               'Update-MgBetaIdentityGovernanceTermOfUseAgreementFileLocalization', 
               'Update-MgBetaIdentityGovernanceTermOfUseAgreementFileLocalizationVersion', 
               'Update-MgBetaPrivilegedAccess', 
               'Update-MgBetaPrivilegedAccessResource', 
               'Update-MgBetaPrivilegedAccessResourceRoleAssignment', 
               'Update-MgBetaPrivilegedAccessResourceRoleAssignmentRequest', 
               'Update-MgBetaPrivilegedAccessResourceRoleAssignmentRequestRoleDefinition', 
               'Update-MgBetaPrivilegedAccessResourceRoleAssignmentRequestSubject', 
               'Update-MgBetaPrivilegedAccessResourceRoleAssignmentRoleDefinition', 
               'Update-MgBetaPrivilegedAccessResourceRoleAssignmentSubject', 
               'Update-MgBetaPrivilegedAccessResourceRoleDefinition', 
               'Update-MgBetaPrivilegedAccessResourceRoleSetting', 
               'Update-MgBetaPrivilegedAccessResourceRoleSettingRoleDefinition', 
               'Update-MgBetaPrivilegedAccessRoleAssignment', 
               'Update-MgBetaPrivilegedAccessRoleAssignmentRequest', 
               'Update-MgBetaPrivilegedAccessRoleAssignmentRequestRoleDefinition', 
               'Update-MgBetaPrivilegedAccessRoleAssignmentRequestSubject', 
               'Update-MgBetaPrivilegedAccessRoleAssignmentRoleDefinition', 
               'Update-MgBetaPrivilegedAccessRoleAssignmentSubject', 
               'Update-MgBetaPrivilegedAccessRoleDefinition', 
               'Update-MgBetaPrivilegedAccessRoleSetting', 
               'Update-MgBetaPrivilegedAccessRoleSettingRoleDefinition', 
               'Update-MgBetaPrivilegedApproval', 
               'Update-MgBetaPrivilegedApprovalRoleInfo', 
               'Update-MgBetaPrivilegedApprovalRoleInfoSetting', 
               'Update-MgBetaPrivilegedApprovalRoleInfoSummary', 
               'Update-MgBetaPrivilegedOperationEvent', 
               'Update-MgBetaPrivilegedRole', 
               'Update-MgBetaPrivilegedRoleAssignment', 
               'Update-MgBetaPrivilegedRoleAssignmentRequest', 
               'Update-MgBetaPrivilegedRoleAssignmentRequestRoleInfo', 
               'Update-MgBetaPrivilegedRoleAssignmentRequestRoleInfoSetting', 
               'Update-MgBetaPrivilegedRoleAssignmentRequestRoleInfoSummary', 
               'Update-MgBetaPrivilegedRoleAssignmentRoleInfo', 
               'Update-MgBetaPrivilegedRoleAssignmentRoleInfoSetting', 
               'Update-MgBetaPrivilegedRoleAssignmentRoleInfoSummary', 
               'Update-MgBetaPrivilegedRoleSetting', 
               'Update-MgBetaPrivilegedRoleSummary', 'Update-MgBetaProgram', 
               'Update-MgBetaProgramControl', 'Update-MgBetaProgramControlProgram', 
               'Update-MgBetaProgramControlType', 
               'Update-MgBetaRoleManagementDirectory', 
               'Update-MgBetaRoleManagementDirectoryResourceNamespace', 
               'Update-MgBetaRoleManagementDirectoryResourceNamespaceResourceAction', 
               'Update-MgBetaRoleManagementDirectoryResourceNamespaceResourceActionResourceScope', 
               'Update-MgBetaRoleManagementDirectoryRoleAssignment', 
               'Update-MgBetaRoleManagementDirectoryRoleAssignmentApproval', 
               'Update-MgBetaRoleManagementDirectoryRoleAssignmentApprovalStep', 
               'Update-MgBetaRoleManagementDirectoryRoleAssignmentAppScope', 
               'Update-MgBetaRoleManagementDirectoryRoleAssignmentSchedule', 
               'Update-MgBetaRoleManagementDirectoryRoleAssignmentScheduleInstance', 
               'Update-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'Update-MgBetaRoleManagementDirectoryRoleDefinition', 
               'Update-MgBetaRoleManagementDirectoryRoleDefinitionInheritPermissionFrom', 
               'Update-MgBetaRoleManagementDirectoryRoleEligibilitySchedule', 
               'Update-MgBetaRoleManagementDirectoryRoleEligibilityScheduleInstance', 
               'Update-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'Update-MgBetaRoleManagementDirectoryTransitiveRoleAssignment', 
               'Update-MgBetaRoleManagementDirectoryTransitiveRoleAssignmentAppScope', 
               'Update-MgBetaRoleManagementEntitlementManagement', 
               'Update-MgBetaRoleManagementEntitlementManagementResourceNamespace', 
               'Update-MgBetaRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'Update-MgBetaRoleManagementEntitlementManagementResourceNamespaceResourceActionResourceScope', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleAssignment', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleAssignmentApproval', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleAssignmentApprovalStep', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleAssignmentAppScope', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleAssignmentSchedule', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleInstance', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleDefinition', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFrom', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleEligibilitySchedule', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleInstance', 
               'Update-MgBetaRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'Update-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignment', 
               'Update-MgBetaRoleManagementEntitlementManagementTransitiveRoleAssignmentAppScope'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/master/documentation/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        Prerelease = 'preview3'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInvwYJKoZIhvcNAQcCoIInsDCCJ6wCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDqc7rnBp+8m7ks
# GQNuF775cyDSd5KFetjl1X1he7jdJ6CCDXYwggX0MIID3KADAgECAhMzAAADrzBA
# DkyjTQVBAAAAAAOvMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMxMTE2MTkwOTAwWhcNMjQxMTE0MTkwOTAwWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDOS8s1ra6f0YGtg0OhEaQa/t3Q+q1MEHhWJhqQVuO5amYXQpy8MDPNoJYk+FWA
# hePP5LxwcSge5aen+f5Q6WNPd6EDxGzotvVpNi5ve0H97S3F7C/axDfKxyNh21MG
# 0W8Sb0vxi/vorcLHOL9i+t2D6yvvDzLlEefUCbQV/zGCBjXGlYJcUj6RAzXyeNAN
# xSpKXAGd7Fh+ocGHPPphcD9LQTOJgG7Y7aYztHqBLJiQQ4eAgZNU4ac6+8LnEGAL
# go1ydC5BJEuJQjYKbNTy959HrKSu7LO3Ws0w8jw6pYdC1IMpdTkk2puTgY2PDNzB
# tLM4evG7FYer3WX+8t1UMYNTAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQURxxxNPIEPGSO8kqz+bgCAQWGXsEw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMTgyNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAISxFt/zR2frTFPB45Yd
# mhZpB2nNJoOoi+qlgcTlnO4QwlYN1w/vYwbDy/oFJolD5r6FMJd0RGcgEM8q9TgQ
# 2OC7gQEmhweVJ7yuKJlQBH7P7Pg5RiqgV3cSonJ+OM4kFHbP3gPLiyzssSQdRuPY
# 1mIWoGg9i7Y4ZC8ST7WhpSyc0pns2XsUe1XsIjaUcGu7zd7gg97eCUiLRdVklPmp
# XobH9CEAWakRUGNICYN2AgjhRTC4j3KJfqMkU04R6Toyh4/Toswm1uoDcGr5laYn
# TfcX3u5WnJqJLhuPe8Uj9kGAOcyo0O1mNwDa+LhFEzB6CB32+wfJMumfr6degvLT
# e8x55urQLeTjimBQgS49BSUkhFN7ois3cZyNpnrMca5AZaC7pLI72vuqSsSlLalG
# OcZmPHZGYJqZ0BacN274OZ80Q8B11iNokns9Od348bMb5Z4fihxaBWebl8kWEi2O
# PvQImOAeq3nt7UWJBzJYLAGEpfasaA3ZQgIcEXdD+uwo6ymMzDY6UamFOfYqYWXk
# ntxDGu7ngD2ugKUuccYKJJRiiz+LAUcj90BVcSHRLQop9N8zoALr/1sJuwPrVAtx
# HNEgSW+AKBqIxYWM4Ev32l6agSUAezLMbq5f3d8x9qzT031jMDT+sUAoCw0M5wVt
# CUQcqINPuYjbS1WgJyZIiEkBMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGZ8wghmbAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAOvMEAOTKNNBUEAAAAAA68wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEILG/draGmHe8EPJj9petWfxc
# Z7nm+szPhgi1i1st08u7MEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAacUg457LCG4aXl/TVXCpjL6lKUQ68OkcLosiEnrMTqUsZG8ihqm9I/Eo
# zZmlXBU+aBP0IFRi+UAWFmR6NGLZ473xX1JqbYA2GYWhP9YSDrNGyJpsNNEv7HLg
# i94T7+Rg03aBB5LaS50WQ1GHwtEaOUb41aH5Py53Sycx7XtJUzT1YJYIl1zZhpPx
# if2AcpbDnrxWdeUgLv9s8MpGfStchrKdqJcfoei6qwdv5vCj28kvOxV2J2QbgUpG
# RrkdxoUBIDdFHXUE1WJbGvAJ823cKFnyaFt97Y9SCtgbaxRWv/Jc32pQxBdqvyji
# 4lQM+uO1hXGC9LXdwehlKoxEDhPiaKGCFykwghclBgorBgEEAYI3AwMBMYIXFTCC
# FxEGCSqGSIb3DQEHAqCCFwIwghb+AgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsq
# hkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCCgA8koUl5tyHsZRhYpZ1DGoICEgQlUsB75HQh9QB0b+gIGZfxxCXcY
# GBMyMDI0MDQxMTA5NDY1Ni4xNDFaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNO
# OjA4NDItNEJFNi1DMjlBMSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBT
# ZXJ2aWNloIIReDCCBycwggUPoAMCAQICEzMAAAHajtXJWgDREbEAAQAAAdowDQYJ
# KoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjMx
# MDEyMTkwNjU5WhcNMjUwMTEwMTkwNjU5WjCB0jELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3Bl
# cmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjowODQyLTRC
# RTYtQzI5QTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAJOQBgh2tVFR1j8jQA4NDf8b
# cVrXSN080CNKPSQo7S57sCnPU0FKF47w2L6qHtwm4EnClF2cruXFp/l7PpMQg25E
# 7X8xDmvxr8BBE6iASAPCfrTebuvAsZWcJYhy7prgCuBf7OidXpgsW1y8p6Vs7sD2
# aup/0uveYxeXlKtsPjMCplHkk0ba+HgLho0J68Kdji3DM2K59wHy9xrtsYK+X9er
# bDGZ2mmX3765aS5Q7/ugDxMVgzyj80yJn6ULnknD9i4kUQxVhqV1dc/DF6UBeuzf
# ukkMed7trzUEZMRyla7qhvwUeQlgzCQhpZjz+zsQgpXlPczvGd0iqr7lACwfVGog
# 5plIzdExvt1TA8Jmef819aTKwH1IVEIwYLA6uvS8kRdA6RxvMcb//ulNjIuGceyy
# kMAXEynVrLG9VvK4rfrCsGL3j30Lmidug+owrcCjQagYmrGk1hBykXilo9YB8Qyy
# 5Q1KhGuH65V3zFy8a0kwbKBRs8VR4HtoPYw9z1DdcJfZBO2dhzX3yAMipCGm6Smv
# mvavRsXhy805jiApDyN+s0/b7os2z8iRWGJk6M9uuT2493gFV/9JLGg5YJJCJXI+
# yxkO/OXnZJsuGt0+zWLdHS4XIXBG17oPu5KsFfRTHREloR2dI6GwaaxIyDySHYOt
# vIydla7u4lfnfCjY/qKTAgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQUoXyNyVE9ZhOV
# izEUVwhNgL8PX0UwHwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYD
# VR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
# CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIw
# MjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBALmDVdTtuI0jAEt4
# 1O2OM8CU237TGMyhrGr7FzKCEFaXxtoqk/IObQriq1caHVh2vyuQ24nz3TdOBv7r
# cs/qnPjOxnXFLyZPeaWLsNuARVmUViyVYXjXYB5DwzaWZgScY8GKL7yGjyWrh78W
# JUgh7rE1+5VD5h0/6rs9dBRqAzI9fhZz7spsjt8vnx50WExbBSSH7rfabHendpeq
# bTmW/RfcaT+GFIsT+g2ej7wRKIq/QhnsoF8mpFNPHV1q/WK/rF/ChovkhJMDvlqt
# ETWi97GolOSKamZC9bYgcPKfz28ed25WJy10VtQ9P5+C/2dOfDaz1RmeOb27Kbeg
# ha0SfPcriTfORVvqPDSa3n9N7dhTY7+49I8evoad9hdZ8CfIOPftwt3xTX2RhMZJ
# CVoFlabHcvfb84raFM6cz5EYk+x1aVEiXtgK6R0xn1wjMXHf0AWlSjqRkzvSnRKz
# FsZwEl74VahlKVhI+Ci9RT9+6Gc0xWzJ7zQIUFE3Jiix5+7KL8ArHfBY9UFLz4sn
# boJ7Qip3IADbkU4ZL0iQ8j8Ixra7aSYfToUefmct3dM69ff4Eeh2Kh9NsKiiph58
# 9Ap/xS1jESlrfjL/g/ZboaS5d9a2fA598mubDvLD5x5PP37700vm/Y+PIhmp2fTv
# uS2sndeZBmyTqcUNHRNmCk+njV3nMIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJ
# mQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
# dGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgzMjI1
# WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjK
# NVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhg
# fWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJp
# rx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/d
# vI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6BVWYbWg7mka9
# 7aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdbZ2De+JKR
# Hh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn427DZM9itu
# qBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEzOUyO
# ArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2ZItb
# oKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
# bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
# AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQW
# BBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacb
# UzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYz
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnku
# aHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
# QwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFNX2
# VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwu
# bWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
# MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
# XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6
# U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVt
# I1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis
# 9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTp
# kbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0
# sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lUZNlz138e
# W0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQTHa1V1QJ
# sWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLBgqJ7
# Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0llOZ0
# dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
# tB1VM1izoXBm8qGCAtQwggI9AgEBMIIBAKGB2KSB1TCB0jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjow
# ODQyLTRCRTYtQzI5QTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
# dmljZaIjCgEBMAcGBSsOAwIaAxUAQqIfIYljHUbNoY0/wjhXRn/sSA2ggYMwgYCk
# fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQUFAAIF
# AOnB89wwIhgPMjAyNDA0MTExMzMwMDRaGA8yMDI0MDQxMjEzMzAwNFowdDA6Bgor
# BgEEAYRZCgQBMSwwKjAKAgUA6cHz3AIBADAHAgEAAgIWujAHAgEAAgISZDAKAgUA
# 6cNFXAIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAID
# B6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUAA4GBAC1WQFlGgaA4Vpcyr4fa
# O0uezx6H3cXrTFNodyixxO//HiTeMVurGt2C1548zWKZz3C3KAfQjMoDd99yC6R8
# E/atWeTWadWoejXE4f+ctRoifDiKyT6zF9ABOUAqheZ2FRNMAAsh8Bjif4RspBOE
# bVE/fLgVKCkYn8OU3AqFrS00MYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgUENBIDIwMTACEzMAAAHajtXJWgDREbEAAQAAAdowDQYJYIZIAWUDBAIB
# BQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQx
# IgQgtJfAYAnFPheszB0wl1UHpKuBWlHh20CZAyJ9MbKi3gcwgfoGCyqGSIb3DQEJ
# EAIvMYHqMIHnMIHkMIG9BCAipaNpYsDvnqTe95Dj1C09020I5ljibrW/ndICOxg9
# xjCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB2o7V
# yVoA0RGxAAEAAAHaMCIEIIwzJSHyW5ParBX2OIxGtjpwzte+e60n5Whjj9enNGAr
# MA0GCSqGSIb3DQEBCwUABIICAAlDGyiXjIIcpVuVfqCqpEPOiPkr7tDFyq7gQ1tT
# /wuesX2695rlIfEey34yJdwE29bOC4Nn3foSRjctldppy9/qJV30cClomEpEa/ac
# UCJ4LYffQpDou1ljg7DnqGBNAxGo3XaZ1/gHvfyS7y0YZlnHdO8KwIbhDYMv9Sp3
# GnW2ZCOm/MC1N6sjaMGHin7LVgl1nFasRYVdU/zvBokighP3+Ix169tUGOmHweKR
# HCeeY/0z5foRkUfHZa1VP4lA7JJhjabsAc9Rq9+s0vFWOVmTe8KZISkIz3n1/d5l
# 8TV3VMmVaExzRMn3B4o8X1smgAw8jmwFIjHRqZ6DiY/kr9pnzpsLe+2pSIs/x6vP
# lia1Ildm0F1hhLGU96mODSPaUjM371iXNALhAOy73fVy14ode4EDFDmavr/Snjvn
# S3TxVfGMd4toNgNyTPJIPdkav9lxcqfB4npttxrV++Ju3DWnBSCu+vzlWCEu+Ytg
# yuNJuULLeQ9xteJIlVi2y/Jew3Un6XmjWSRXLZBN8xbjAWX4qs2CsOUb7XjOWq37
# boTwfQUyWlJR1bflugfFNBtKFmL3zFyfpAb+8BErY+t+uRyP97LQLw73U8sbcfy0
# lY+vx6zC7DFc9XkKa+oM6Nk9/J6jZ1LYrrB12z+ivCvIKrPHhbthk8pL015QA+GI
# xEER
# SIG # End signature block
